### ISSUE TITLE
Tests: DeadCodeEliminationTest.testFloatingPoint() depends on locale setting

### ISSUE THREAD

**Issue by jnehlmeier** [gwtproject/gwt#10067]
##### Description

`DeadCodeEliminationTest.testFloatingPoint()` fails if your default locale uses `,` instead of `.` in floating point numbers.

I don't like adding `-Duser.country=US -Duser.language=en` to `common.ant.xml -> gwt.junit` as I think tests should work without any special configuration, e.g. when running from the IDE directly without ANT.

Instead the test should use `DecimalFormatSymbols.getInstance().getDecimalSeparator()` to build the expected result when `String.format()` is used. 

##### Steps to reproduce

Run ant tests using `-Duser.country=DE -Duser.language=de` to simulate such a locale setting.

##### Known workarounds

Run ant tests using `-Duser.country=US -Duser.language=en`

**Comment by niloc132** [comment]
Stack trace for this failure - make sure to edit the test jvm args and not ant's own args to reproduce:
```
Testcase: testFloatingPoint took 0,044 sec
	FAILED
return 1.1f; expected:<return 1[,]100000023841858;> but was:<return 1[.]100000023841858;>
junit.framework.ComparisonFailure: return 1.1f; expected:<return 1[,]100000023841858;> but was:<return 1[.]100000023841858;>
	at com.google.gwt.dev.jjs.impl.OptimizerTestBase$Result.intoString(OptimizerTestBase.java:140)
	at com.google.gwt.dev.jjs.impl.DeadCodeEliminationTest.testFloatingPoint(DeadCodeEliminationTest.java:468)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

The test is definitely at fault here, using Locale.ROOT or so resolves it.
