### ISSUE TITLE
CellPanel setCellWidth 0px causes exception in IE

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#2071]
Originally reported on Google Code with ID 2065

```
Found in GWT Release:  1.4.61

Detailed description:

I have an application where I use a HorizontalPanel for layout, wherein under certain

circumstances I want to set the width of certain cells to a width of "0px".  This works
perfectly in Safari (both Win and Mac) and in Firefox (both Win and Mac).  In IE6 and
IE7,
however, I get an exception:

[ERROR] [FATAL] Uncaught Exception:
com.google.gwt.core.client.JavaScriptException: JavaScript Error exception: Invalid
argument.
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:481)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:270)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:137)
    at com.google.gwt.user.client.impl.DOMImpl.setElementProperty(DOMImpl.java:344)
    at com.google.gwt.user.client.DOM.setElementProperty(DOM.java:1038)
    at com.google.gwt.user.client.ui.CellPanel.setCellWidth(CellPanel.java:110)
    at net.nanonation.ui.client.MainPage.addLeftMargin(MainPage.java:73)

From reading GWT source, it appears that in DOMImpl.setElementProperty()  the JavaScript
called via JSNI is causing an exception in IE.  In particular, that line is

        elem[prop] = value;

In this case, the element is CellPanel's td that contains the widget in question. 
(In my
case, the child widget is a SimplePanel).   The "prop" is  "width", and the value is
"0px".


Workaround if you have one:
It appears that if I can live with a "1px" width, I can avoid this exception, at the
small
cost of imprecise layout.   It would be lovely if this browser limitation could be
solved
at the toolkit level.  Failing that, a proper warning in the Javadoc for CellPanel's

setCellWidth method could save others much heartache.

It appears that "auto" can also cause this problem, although I expect to file a separate
issue to track that case. 
```

Reported by `pohl.longsine` on 2008-02-06 23:03:22

**Comment by zbynek** [comment]
IE only
