### ISSUE TITLE
include the method name in the stack when there is a problem in a JSO

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#6556]
Originally reported on Google Code with ID 6557
```
Found in GWT Release (e.g. 1.5.3, 1.6 RC):
2.3.0

Encountered on OS / Browser (e.g. WinXP, IE6-7, FF3):
DevMode


Detailed description (please be as specific as possible):

I am using JSO's where I added some extra functions through native code to do conversion
from maps(objects) to Iterables.

When these method fail for some reason I sometimes get a very annoying stacktrace in
the console that does not tell me what method on what object he was trying to invoke.

I always have to go to the debugger (which takes a lot of time to start) and put a
breakpoint in BrowserChannelServer just to find out what the called was.

This could be easily be improved by including the methodName parameter of the invokeJavascript
function!

This is the "oeps there is an error" stack that I get ... nothing that helps me here.

com.google.gwt.core.client.JavaScriptException: (TypeError): Object doesn't support
this property or method
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:237)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:132)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:214)
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:167)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:281)
	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:531)
	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:352)
	at java.lang.Thread.run(Thread.java:662)

```

Reported by `david.nouls` on 2011-07-07 08:41:25

**Comment by dankurka** [comment]
Since devmode is being phased out this won't get addressed.
