### ISSUE TITLE
JavaScriptException: (Error): Unspecified error using Image in IE8

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#6839]
Originally reported on Google Code with ID 6840

```
Found in GWT Release (e.g. 1.5.3, 1.6 RC):

2.3

Encountered on OS / Browser (e.g. WinXP, IE6-7, FF3):

Windows XP, IE8

Detailed description (please be as specific as possible):

Creating and attaching an image causes IE8 to throw the following javascript exception
(in dev as well as in web mode):


com.google.gwt.core.client.JavaScriptException: (Error): Unspecified error.
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:237)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:132)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:214)
    at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:167)
    at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:281)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:531)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:352)
    at java.lang.Thread.run(Thread.java:662)

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

   // Does not work
   Image image = new Image(<DataResource>.getUrl());
   cell.setWidget(image);

   // Workaround
   Image image = new Image();
   cell.setWidget(image);
   image.setUrl(<DataResource>.getUrl());

Workaround if you have one:

http://code.google.com/p/google-web-toolkit/issues/detail?id=5181#c17
Tried that out. Works fine. How ever this seems to bee a bug.

Links to relevant GWT Developer Forum posts:

http://code.google.com/p/google-web-toolkit/issues/detail?id=5181
```

Reported by `hhumml` on 2011-09-29 12:07:41

**Comment by niloc132** [comment]
IE8 is unsupported, closing as stale.
