### ISSUE TITLE
devmode broken if there are a lot of jso classes

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7478]
Originally reported on Google Code with ID 7481

```
Summary: devmode broken if there are a lot of jso classes, especially, if elemental.jar
is included.

Found in GWT Release: 2.5.0 RC1

Detailed description:
To dispatch JSNI method calls in devmode, CompilingClassLoader uses dispId = (classId
<< 16) | memberId. classId and memberId are set for every jso class in DispatchClassInfo
which has every method of this class down to his superclasses. If project has a lot
of jso classes + elemental module is included(which consists of jso classes), list
field of DispatchClassInfo memberId has a lot of entries and memberId.size() can be
a big number (it uses position of method in this list as method id) which collides
with classId<<16 number in CompilingClassLoader and therefore CompilingClassLoader
resolves invalid classId from dispId.

For example: 
className: com.google.gwt.user.client.ui.PotentialElement
classId=16
memberName:
memberId=87657

dispId= (16 << 16)+87657=1136233

So if we want to extract classId from dispId:
classId=(dispId >> 16) & 0xffff = 17
we get classId 17 which is wrong (should be 16), memberId overflows classId.

Here is the exception thrown
Caused by: java.lang.IndexOutOfBoundsException: Index: 17, Size: 17
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at com.google.gwt.dev.shell.CompilingClassLoader$DispatchClassInfoOracle.getClassInfoByDispId(CompilingClassLoader.java:123)


```

Reported by `a.korzhevskiy` on 2012-07-03 10:46:20

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/#/c/2210/ concluded that the discussed patch wouldn't actually solve the problem, and a wire format change would be necessary to actually resolve this. Especially in light of the fact that legacy dev mode is deprecated and Google never opened up build steps for the browser plugins, I'm closing this as won't fix slash stale.
