### ISSUE TITLE
GWT 2.5.0-rc1 && IBM JDK failures with .gwtar and compile

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7527]
Originally reported on Google Code with ID 7530

```
Found in GWT Release (e.g. 2.4.0, 2.5.0 RC): 2.5.0-rc1


Encountered on OS / Browser (e.g. WinXP, IE8-9, FF7): *

Detailed description (please be as specific as possible): GWT attempts to load pre-compiled
GWT module archive (.gwtar) files to increase performance; there are some JDKs where
this causes a problem, namely IBM JDK.


Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result): Use an IBM JDK and attempt to GWT compile
any sample application, shown here is output from Hello app:

Compiling module com.google.gwt.sample.hello.Hello
   [WARN] Unable to read: jar:file:/path/com/google/gwt/gwt-user/2.5.0-rc1/gwt-user-2.5.0-rc1.jar!/com/google/gwt/user/User.gwtar.
Skipping: java.io.InvalidClassException: com.google.gwt.dev.jjs.SourceOrigin$1; local
class incompatible: stream classdesc serialVersionUID = -2407201776821563037, local
class serialVersionUID = 4713379764594032837
   [WARN] Unable to read: jar:file:/path/com/google/gwt/gwt-user/2.5.0-rc1/gwt-user-2.5.0-rc1.jar!/com/google/gwt/core/Core.gwtar.
Skipping: java.io.InvalidClassException: com.google.gwt.dev.jjs.SourceOrigin$1; local
class incompatible: stream classdesc serialVersionUID = -2407201776821563037, local
class serialVersionUID = 4713379764594032837
   [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
    at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:109)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:116)
    at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:41)
    at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:170)
    at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
    at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:83)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:133)
    at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:82)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:426)
    at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:395)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
    at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:902)
    at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:627)
    at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:604)
    at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:33)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:278)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:141)
    at com.google.gwt.dev.Compiler.run(Compiler.java:232)
    at com.google.gwt.dev.Compiler.run(Compiler.java:198)
    at com.google.gwt.dev.Compiler$1.run(Compiler.java:170)
    at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:88)
    at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:82)
    at com.google.gwt.dev.Compiler.main(Compiler.java:177)
Caused by: java.lang.RuntimeException: Unexpected IOException on in-memory stream
    at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:324)
    at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:672)
    at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeByBinary(UnifyAst.java:970)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1033)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1024)
    at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:940)
    at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:678)
    at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeByBinary(UnifyAst.java:970)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1033)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1024)
    at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:940)
    at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:678)
    at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeByBinary(UnifyAst.java:970)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1033)
    at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:944)
    at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:678)
    at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeByBinary(UnifyAst.java:970)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1033)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1024)
    at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:940)
    at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateUnit(UnifyAst.java:678)
    at com.google.gwt.dev.jjs.impl.UnifyAst.searchForTypeByBinary(UnifyAst.java:970)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1033)
    at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1085)
    at com.google.gwt.dev.jjs.impl.UnifyAst.access$800(UnifyAst.java:120)
    at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:333)
    at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:240)
    at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
    at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
    ... 32 more
Caused by: java.io.InvalidClassException: com.google.gwt.dev.jjs.SourceOrigin$1; local
class incompatible: stream classdesc serialVersionUID = -2407201776821563037, local
class serialVersionUID = 4713379764594032837
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1589)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1502)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1738)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1335)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1953)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1877)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1759)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1335)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1953)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1877)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1759)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1335)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:354)
    at java.util.ArrayList.readObject(ArrayList.java:731)
    at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:600)
    at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1030)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1855)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1759)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1335)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:354)
    at com.google.gwt.dev.jjs.ast.JDeclaredType.readMembers(JDeclaredType.java:294)
    at com.google.gwt.dev.jjs.ast.JProgram.deserializeTypes(JProgram.java:202)
    at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:322)
    ... 60 more
      [ERROR] at Hello.java(37): RootPanel.get().add(b)
         com.google.gwt.dev.jjs.ast.JMethodCall
      [ERROR] at Hello.java(37): RootPanel.get().add(b)
         com.google.gwt.dev.jjs.ast.JExpressionStatement
      [ERROR] at Hello.java(30): {
  Button b = new Button("Click me", new Hello$1(this));
  RootPanel.get().add(b);
}
         com.google.gwt.dev.jjs.ast.JBlock
      [ERROR] at Hello.java(30): {
  Button b = new Button("Click me", new Hello$1(this));
  RootPanel.get().add(b);
}
         com.google.gwt.dev.jjs.ast.JMethodBody
      [ERROR] at Hello.java(30): public void onModuleLoad();

         com.google.gwt.dev.jjs.ast.JMethod






Workaround if you have one: none available, not even passing -Dgwt.jjs.javaArgs= as
for other IBM JDK issues will work since GWT is deserializing an archive and that is
failing.



Links to relevant GWT Developer Forum posts: https://groups.google.com/forum/#!topic/gwt-steering/WGs-uiyHQA8/discussion


Link to patch posted at http://gwt-code-reviews.appspot.com: n/a

```

Reported by `jieryn` on 2012-07-18 17:02:26

**Comment by jnehlmeier** [comment]
.gwtar support has been removed from GWT 2.8, so closing this issue.
