### ISSUE TITLE
ClassNotFoundException with source files that have annotations that refer to classes

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7599]
Originally reported on Google Code with ID 7602

```
For example, if you have source that like this:

@SingleJsoImpl(FooImpl.class)
public interface Foo {
  ...
}

It looks like the compiler attempts to resolve the annotation by doing a Class.forName().
This doesn't work when the annotation class is only available as source code, as is
sometimes true in Super Dev Mode. We need to fix TypeOracleMediator so that only looks
at source and never relies on Java reflection.

Relevant stack trace:

java.lang.ClassNotFoundException: com.google.ads.apps.common.client.event.GwtStatsEventOverlay
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.google.gwt.dev.javac.TypeOracleMediator.resolveAnnotationValue(TypeOracleMediator.java:750)
    at com.google.gwt.dev.javac.TypeOracleMediator.createAnnotation(TypeOracleMediator.java:498)
    at com.google.gwt.dev.javac.TypeOracleMediator.resolveAnnotation(TypeOracleMediator.java:648)
    at com.google.gwt.dev.javac.TypeOracleMediator.resolveAnnotations(TypeOracleMediator.java:663)
    at com.google.gwt.dev.javac.TypeOracleMediator.resolveClass(TypeOracleMediator.java:809)
    at com.google.gwt.dev.javac.TypeOracleMediator.addNewTypes(TypeOracleMediator.java:439)
    at com.google.gwt.dev.javac.TypeOracleMediatorFromSource.addNewUnits(TypeOracleMediatorFromSource.java:52)
    at com.google.gwt.dev.javac.CompilationState.assimilateUnits(CompilationState.java:164)
    at com.google.gwt.dev.javac.CompilationState.<init>(CompilationState.java:82)
    at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:466)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:388)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:373)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:246)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:141)
    at com.google.gwt.dev.Compiler.run(Compiler.java:232)
    at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:89)

```

Reported by `skybrian@google.com` on 2012-08-17 22:04:01

**Comment by niloc132** [comment]
Closing as fixed - this has been a warning since 2f8bd043bbf8bcc6f0463097c2766c7b071e3e8e, and was fundamentally refactored in d1a0427875ba850692e22f4d171e12c2ca2a7fa9 as part of the initial jsinterop commit - wrapped with a try/catch and some logging.

**Comment by niloc132** [comment]
I'm reopening and removing my comment because I think I misunderstood what the issue was trying to say - while this hasn't actually thrown an exception since https://github.com/gwtproject/gwt/commit/d52a9ba360e2a6bfb551d177fcf5b57942655aea, it did log the exception and return `null` at that time. In https://github.com/gwtproject/gwt/commit/2f8bd043bbf8bcc6f0463097c2766c7b071e3e8e it was changed to be a warning instead with no stack trace - but it still returns null, which could perhaps be considered incorrect.

As far as I can tell though, this should only apply to Generators and the like, trying to do compile-time reflection over types that happen to not yet be compiled. Annotation processors are definitely preferred here, so the warning should be sufficient, and possible something we want to turn off (see also https://github.com/gwtproject/gwt/issues/6941).
