### ISSUE TITLE
2.5.0 Regression: DevMode can no longer mix ClientBundle and generics

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7732]
Originally reported on Google Code with ID 7735
```
Found in GWT Release (e.g. 2.4.0, 2.5.0 RC):

2.5.0.RC2

Encountered on OS / Browser (e.g. WinXP, IE8-9, FF7):

Win7-x64 / Chrome 22, IE9, FF15 (although this does not seem OS/browser specific)

Detailed description (please be as specific as possible):

We are serving the same images from the server and in the GWT client. To achieve this,
we have something like this in the client (see more code below and attached test case).

public interface ClientImageBundle extends SharedImageBundle< ImageResource >, ClientBundle
{}

Running the DevMode used to work find until 2.4.0, but it fails with 2.5.0-rc2, with
following error.

java.lang.ClassCastException: com.google.gwt.dev.javac.typemodel.JParameterizedType
cannot be cast to com.google.gwt.core.ext.typeinfo.JRealClassType
    at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator$RequirementsImpl.getTypeLastModifiedTimes(AbstractClientBundleGenerator.java:321)
    at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.generateIncrementally(AbstractClientBundleGenerator.java:494)
    at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:651)
    at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:41)
    at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:79)
    at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:276)
    at com.google.gwt.dev.shell.ShellModuleSpaceHost.rebind(ShellModuleSpaceHost.java:141)
    at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:594)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:464)
    at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:49)
    at com.google.gwt.core.shared.GWT.create(GWT.java:57)
    at com.google.gwt.core.client.GWT.create(GWT.java:85)
    at my.example.bug.client.MyEntryPoint.onModuleLoad(MyEntryPoint.java:17)

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

On the shared side:
-------------------

package my.example.bug.shared;
public interface SharedImageBundle< RET >
{
    @Source( "my/example/bug/shared/gwt-logo.png" )
    RET gwtLogo();
}

On the client side:
-------------------
package my.example.bug.client;
public interface ClientImageBundle
    extends SharedImageBundle< ImageResource >, ClientBundle
{
}

On the server side:
-------------------
package my.example.bug.server;
public interface ServerImageBundle
    extends SharedImageBundle< String >
{
}
We then use Java introspection to find the images paths found in the annotations.

There is a test case attached. To run it, you just need to add the gwt-servlet.jar
to the war/WEB-INF/lib folder (I removed it to avoid wasting disk space uselessly).

Thanks for your attention!
Best regards


Workaround if you have one:
None so far


Links to relevant GWT Developer Forum posts:


Link to patch posted at http://gwt-code-reviews.appspot.com:

```

Reported by `jan.vorwerk` on 2012-10-18 09:15:53

<hr>
 * *Attachment: [bug-gwt250rc2.zip](https://storage.googleapis.com/google-code-attachments/google-web-toolkit/issue-7735/comment-0/bug-gwt250rc2.zip)*

**Comment by dankurka** [comment]
Since this issue has been inactive for more than 6 months, we are closing it off.
If you are still affected and feel strongly about this issue, feel free to provide a patch, see: http://gwtproject.gquery.org/makinggwtbetter.html#submittingpatches or reopen with a repro case.
