### ISSUE TITLE
Closure compiler breaks StackTraceDeobfuscator

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7800]
Originally reported on Google Code with ID 7803

```
= Found in GWT Release (e.g. 2.4.0, 2.5.0 RC): =
2.5.0

= Encountered on OS / Browser (e.g. WinXP, IE8-9, FF7): =
Linux, Chrome 24, FF 10.0.2

= Detailed description (please be as specific as possible): =
Activating the closure compiler by adding the -XenableClosureCompiler flag breaks the
stack trace deobfuscation implemented in the class StackTraceDeobfuscator. The annoying
aspect of this issue is that the deobfuscation doesn't break completely but produces
entirely wrong and incomplete results, for example:

java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (TypeError)
: Cannot call method 'Uq' of null
        at com.allen_sauer.gwt.log.client.RemoteLoggerImpl$1.run(RemoteLoggerImpl.java:44)
        at com.google.api.gwt.oauth2.client.Auth.$setToken(Auth.java:207)
        at com.google.api.gwt.oauth2.client.Auth.$login(Auth.java:73)
        at Unknown._.ph(http://192.168.1.100:8888/foo/20FB4D8461AF9C62201051C4AFE6AB42.cache.html@80)
        at Unknown.$ua(http://192.168.1.100:8888/foo/20FB4D8461AF9C62201051C4AFE6AB42.cache.html@341)
        at Unknown.anonymous(http://192.168.1.100:8888/foo/20FB4D8461AF9C62201051C4AFE6AB42.cache.html@237)
        at Unknown.anonymous(http://192.168.1.100:8888/foo/20FB4D8461AF9C62201051C4AFE6AB42.cache.html@232)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot call
method 'Uq' of null
        at Unknown._.Nf(http://192.168.1.100:8888/foo/20FB4D8461AF9C62201051C4AFE6AB42.cache.html@203)
        ... 5 more

Note that none of the classes mentioned in this stack trace are correct. The expected,
deobfuscated stacktrace is:

java.lang.RuntimeException: com.google.gwt.core.client.JavaScriptException: (TypeError)
: Cannot call method 'Uq' of null
        at java.lang.Throwable.fillInStackTrace(Throwable.java:71)
        at java.lang.RuntimeException.RuntimeException(RuntimeException.java:36)
        at de.foo.frontend.client.entrypoint.FooEntryPoint.$uncaughtExceptionHandler(FooEntryPoint.java:218)
        at de.foo.frontend.client.entrypoint.FooEntryPoint$2.$onUncaughtException(FooEntryPoint.java:106)
        at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:212)
        at com.google.gwt.core.client.impl.SchedulerImpl.$flushPostEventPumpCommands(SchedulerImpl.java:379)
        at com.google.gwt.core.client.impl.SchedulerImpl$Flusher.execute(SchedulerImpl.java:76)
        at com.google.gwt.core.client.impl.SchedulerImpl.execute(SchedulerImpl.java:137)
        at com.google.gwt.core.client.impl.Impl.apply(Impl.java:186)
        at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:225)
        at Unknown.anonymous(http://192.168.1.100:8888/foo/A337BCFE4059CD4236107ADAF4046132.cache.html@45)
        at Unknown.anonymous(http://192.168.1.100:8888/foo/A337BCFE4059CD4236107ADAF4046132.cache.html@63)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot call
method 'Uq' of null
        at de.foo.frontend.client.pages.foo.debug.DebugPagePresenter$1.execute(DebugPagePresenter.java:76)
        ... 8 more

I guess the problem is that the GWT compiler does not know about the Closure compiler
when generating the symbolMaps and that the closure compiler messes up all the identifiers
afterwards. I'm OK with this behavior, since the Closure compiler does not proivde
vital performance improvements for us anyway. However, it would be great if you could
turn off the symbolMaps generation and display a big warning, explaining the issue,
if someone activates the closure compiler flag.

= Shortest code snippet which demonstrates issue (please indicate where actual result
differs from expected result): =
  * Setup a global exception handler using GWT.setUncaughtExceptionHandler() and send
all uncaught exceptions to the server using gwt-log.
  * Cause an exception: String foo=null; foo.toString();

= Workaround if you have one: =
Disable closure compiler (remove the -XenableClosureCompiler flag).

```

Reported by `wuertinger.michael` on 2012-11-22 13:46:06

**Comment by jnehlmeier** [comment]
Experimental Closure compiler integration has been removed from GWT 2.8, so closing this issue.
