### ISSUE TITLE
Fix GWTTestCase flakiness by choosing an unused port

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8165]
Originally reported on Google Code with ID 8170

```
Haven't investigated, but it looks like GWTTestCase might be flaky due to using a fixed
port for Jetty. If two tests are run at the same time on the same machine then there's
a possibility of a conflict. If so, we should change it to pick an unused port.

GWT args: -Dgwt-args=' -testBeginTimeout 3 -optimize 9 -style OBFUSCATED -runStyle
HtmlUnit:FF3 -ea -out 
[redacted]
.Starting Jetty on port 17000
   [WARN] failed SelectChannelConnector@0.0.0.0:17000
java.net.BindException: Address already in use
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:344)
    at sun.nio.ch.Net.bind(Net.java:336)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:199)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at com.google.gwt.thirdparty.org.mortbay.jetty.nio.SelectChannelConnector.open(SelectChannelConnector.java:205)
    at com.google.gwt.thirdparty.org.mortbay.jetty.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:304)
    at com.google.gwt.thirdparty.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
    at com.google.gwt.thirdparty.org.mortbay.jetty.Server.doStart(Server.java:233)
    at com.google.gwt.thirdparty.org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:39)
    at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:690)
    at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:511)
    at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:1101)
    at com.google.gwt.junit.JUnitShell.getUnitTestShell(JUnitShell.java:721)
    at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:695)
    at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
    at junit.framework.TestCase.runBare(TestCase.java:134)

```

Reported by `skybrian@google.com` on 2013-06-01 01:19:46

**Comment by niloc132** [comment]
Closing this as stale (as it probably should have been closed more than a decade ago).
