### ISSUE TITLE
Dev Mode FieldSerializer compilation error

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8211]
Originally reported on Google Code with ID 8221
```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):
2.5.1


Encountered on OS / Browser (e.g. WinXP, IE9, FF10):
Win7


Detailed description (please be as specific as possible):
Intermittently, Dev Mode is reporting errors when it compiles "*_FieldSerializer" classes
that share a common base class, either the serialize() or deserialize() method gets
the error indicating the base class cannot be resolved to a type.
 
It appears to happen when the classes are compiled on a browser refresh. It does not
happen all the time and a restart of dev mode fixes the problem until a browser refresh
is done again. 

Caused by: java.lang.ClassNotFoundException: null
 	at com.google.gwt.dev.shell.CompilingClassLoader$MultiParentClassLoader.findClass(CompilingClassLoader.java:365)
 	at com.google.gwt.dev.shell.CompilingClassLoader$MultiParentClassLoader.loadClass(CompilingClassLoader.java:385)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
 	at java.lang.Class.forName0(Native Method)
 	at java.lang.Class.forName(Class.java:171)
 	at com.google.gwt.user.client.rpc.impl.ReflectionHelper.loadClass(ReflectionHelper.java:91)
 	at com.google.gwt.user.client.rpc.impl.SerializerBase.getTypeHandler(SerializerBase.java:160)
 	at com.google.gwt.user.client.rpc.impl.SerializerBase.serialize(SerializerBase.java:125)
 	at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamWriter.serialize(ClientSerializationStreamWriter.java:183)
 	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:126)
 	at com.google.gwt.user.client.rpc.core.java.util.Collection_CustomFieldSerializerBase.serialize(Collection_CustomFieldSerializerBase.java:44)
 	at com.google.gwt.user.client.rpc.core.java.util.HashSet_CustomFieldSerializer.serialize(HashSet_CustomFieldSerializer.java:39)
 	at com.google.gwt.user.client.rpc.core.java.util.HashSet_FieldSerializer.serial(HashSet_FieldSerializer.java:23)
 	at com.google.gwt.user.client.rpc.impl.SerializerBase.serialize(SerializerBase.java:126)
 	at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamWriter.serialize(ClientSerializationStreamWriter.java:183)
 	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:126)
 	at com.mycompany.gwt.ucare.am.domain.CustomerOrderSearchCriteriaGO_FieldSerializer.serialize(CustomerOrderSearchCriteriaGO_FieldSerializer.java:72)
 	at com.mycompany.gwt.ucare.am.domain.CustomerOrderSearchCriteriaGO_FieldSerializer.serial(CustomerOrderSearchCriteriaGO_FieldSerializer.java:88)
 	at com.google.gwt.user.client.rpc.impl.SerializerBase.serialize(SerializerBase.java:126)
 	at com.google.gwt.user.client.rpc.impl.ClientSerializationStreamWriter.serialize(ClientSerializationStreamWriter.java:183)
 	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:126)
 	at com.mycompany.app.client.service.OrderHandlingService_Proxy.searchOrders(OrderHandlingService_Proxy.java:170)
 	at com.mycompany.app.client.layout.order.ManageCustomerOrders.doSearch(ManageCustomerOrders.java:79)
 	at com.mycompany.app.client.widget.SearchWidget$3.load(SearchWidget.java:190)
 	at com.mycompany.app.client.data.ModelHelper$3.load(ModelHelper.java:544)
 	at com.mycompany.app.client.data.ModelHelper$3.load(ModelHelper.java:1)
 	at com.mycompany.app.client.data.ModelHelper$4.load(ModelHelper.java:664)
 	at com.extjs.gxt.ui.client.data.RpcProxy.load(RpcProxy.java:21)
 	at com.extjs.gxt.ui.client.data.BaseLoader.loadData(BaseLoader.java:134)
 	at com.extjs.gxt.ui.client.data.BaseLoader.load(BaseLoader.java:98)
 	at com.extjs.gxt.ui.client.data.BaseLoader.load(BaseLoader.java:92)
 	at com.extjs.gxt.ui.client.data.BasePagingLoader.load(BasePagingLoader.java:59)
 	at com.extjs.gxt.ui.client.widget.toolbar.PagingToolBar.doLoadRequest(PagingToolBar.java:718)
 	at com.extjs.gxt.ui.client.widget.toolbar.PagingToolBar.first(PagingToolBar.java:531)
 	at com.mycompany.app.client.widget.SearchWidget.initialLoad(SearchWidget.java:447)
 	at com.mycompany.app.client.layout.AbstractSearchLayout.doSearch_(AbstractSearchLayout.java:152)
 	at com.mycompany.app.client.layout.AbstractSearchLayout.access$0(AbstractSearchLayout.java:146)
 	at com.mycompany.app.client.layout.AbstractSearchLayout$1.execute(AbstractSearchLayout.java:140)
 	at com.mycompany.app.client.helper.UIInit.execute(UIInit.java:54)
 	at com.google.gwt.core.client.impl.SchedulerImpl$Task$.executeScheduled$(SchedulerImpl.java:50)
 	at com.google.gwt.core.client.impl.SchedulerImpl.runScheduledTasks(SchedulerImpl.java:180)
 	at com.google.gwt.core.client.impl.SchedulerImpl.flushPostEventPumpCommands(SchedulerImpl.java:347)
 	at com.google.gwt.core.client.impl.SchedulerImpl$Flusher.execute(SchedulerImpl.java:78)
 	at com.google.gwt.core.client.impl.SchedulerImpl.execute(SchedulerImpl.java:138)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 	at java.lang.reflect.Method.invoke(Method.java:597)
 	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
 	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
 	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
 	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:338)
 	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:219)
 	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
 	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)
 	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:279)
 	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
 	at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
 	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:242)
 	at sun.reflect.GeneratedMethodAccessor446.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
 	at java.lang.reflect.Method.invoke(Method.java:597)
 	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
 	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
 	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
 	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:293)
 	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:547)
 	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
 	at java.lang.Thread.run(Thread.java:662)

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):



Workaround if you have one:
Restart dev mode


Links to relevant GWT Developer Forum posts:



Link to patch posted at http://gwt-review.googlesource.com

```

Reported by `derek.cornelius` on 2013-06-24 16:31:09

**Comment by dankurka** [comment]
Dev mode is strongly deprecated and will be removed after 2.8. Closing this off.
