### ISSUE TITLE
Type 'java.util.ArrayList' was not included in the set of types which can be deserialized by this SerializationPolicy

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8356]
Originally reported on Google Code with ID 8370
```
Context:
 GWT 2.5.1 and  2.5.0
 Windows professionnel 7, FF 23.0.1, hosted mode.

Detailed description (please be as specific as possible):
I have  RCP method  

  void submitTask(final String taskId,
      final Map<String, Object> taskData) throws Exception;

Object can be String,Boolean,Float,Long,Byte,Short,Double or List<Object>.

I check in GWT RPC whitelist of web project that all type class are  serializable.
but  gwt can't execute a  rcp  method  throw exception

16:43:11,479 [ERROR] [[/test]       :700] http-LOCALHOST/127.0 SimpleService: An IncompatibleRemoteServiceException
was thrown while processing this call.: com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException:
Type 'java.util.ArrayList' was not included in the set of types which can be deserialized
by this SerializationPolicy or its Class object could not be loaded. For security purposes,
this type will not be deserialized.
	at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:323) [gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:206)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
[gwt-user-2.5.0-no-servlet.jar:]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:754) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar:1.0.2.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
[jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
	at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
[jboss-as-jpa-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
	at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
[jboss-as-web-7.2.0.Final-redhat-8.jar:7.2.0.Final-redhat-8]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
[jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final-redhat-1.jar:7.2.0.Final-redhat-1]
	at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_23]
Caused by: com.google.gwt.user.client.rpc.SerializationException: Type 'java.util.ArrayList'
was not included in the set of types which can be deserialized by this SerializationPolicy
or its Class object could not be loaded. For security purposes, this type will not
be deserialized.
	at com.google.gwt.user.server.rpc.impl.StandardSerializationPolicy.validateDeserialize(StandardSerializationPolicy.java:158)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:651)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:567)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.core.java.util.Map_ServerCustomFieldSerializerBase.deserialize(Map_ServerCustomFieldSerializerBase.java:38)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserialize(HashMap_ServerCustomFieldSerializer.java:40)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserializeInstance(HashMap_ServerCustomFieldSerializer.java:54)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserializeInstance(HashMap_ServerCustomFieldSerializer.java:33)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeImpl(ServerSerializationStreamReader.java:859)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:662)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:567)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader$ValueReader$8.readValue(ServerSerializationStreamReader.java:140)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeValue(ServerSerializationStreamReader.java:425)
[gwt-user-2.5.0-no-servlet.jar:]
	at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:312) [gwt-user-2.5.0-no-servlet.jar:]
	... 20 more



```

Reported by `hajer.akaichi` on 2013-09-27 16:02:13

**Comment by dankurka** [comment]
Since this issue has been inactive for more than 6 months, we are closing it off.
If you are still affected and feel strongly about this issue, feel free to provide a patch, see: http://gwtproject.gquery.org/makinggwtbetter.html#submittingpatches or reopen with a repro case.
