### ISSUE TITLE
OutputFileSetOnDirectory cannot handle directory paths containing "/../"

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8483]
Originally reported on Google Code with ID 8500
```
Issue Report Summary: OutputFileSetOnDirectory cannot handle directory paths containing
"/../"

**Found in GWT Release (e.g. 1.5.3, 1.6 RC):**

GWT 2.6.0-rc3

**Encountered on OS / Browser (e.g. WinXP, IE6-7 | Fedora 10, FF3):**

Encoountered while building on OS X 10.9

**Detailed description (please be as specific as possible):**

If a Generator in my project creates a new file using GeneratorContext.tryCreateResource,
and that file has "/../" in the path, I get an IOException while building.

The following code in a generator:

final OutputStream outStream = context.tryCreateResource(logger, "../folder/filename.ext");

gives this stack trace:

[INFO]       Emitting resource ../folder/filename.ext
[INFO]          [ERROR] Fatal error emitting artifact: ../folder/filename.ext
[INFO] java.io.IOException: unable to create directory: /workspace/myproj/target/my-proj/app/MyProj/..
[INFO] 	at com.google.gwt.dev.util.OutputFileSetOnDirectory.mkdirs(OutputFileSetOnDirectory.java:82)
[INFO] 	at com.google.gwt.dev.util.OutputFileSetOnDirectory.mkdirs(OutputFileSetOnDirectory.java:80)
[INFO] 	at com.google.gwt.dev.util.OutputFileSetOnDirectory.mkdirs(OutputFileSetOnDirectory.java:80)
[INFO] 	at com.google.gwt.dev.util.OutputFileSetOnDirectory.mkdirs(OutputFileSetOnDirectory.java:80)
[INFO] 	at com.google.gwt.dev.util.OutputFileSetOnDirectory.createNewOutputStream(OutputFileSetOnDirectory.java:54)
[INFO] 	at com.google.gwt.dev.util.OutputFileSet.openForWrite(OutputFileSet.java:82)
[INFO] 	at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.produceOutput(StandardLinkerContext.java:508)
[INFO] 	at com.google.gwt.dev.Link.doProduceOutput(Link.java:409)
[INFO] 	at com.google.gwt.dev.Link.link(Link.java:178)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:200)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:132)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:99)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:106)


Workaround if you have one:

Continuing to use GWT 2.5.1 where this issue is not present.

Links to relevant GWT Developer Forum posts:

The following post identifies the commit which changed the behaviour.

https://groups.google.com/d/msg/google-web-toolkit/JKcaXM9LK94/Pi69mwUepx4J


```

Reported by `douglas@hosk.co` on 2013-12-20 09:18:21

**Comment by tbroyer** [comment]
> `java.io.FileNotFoundException: […] (File name too long)`

You **did** hit a filesystem limit, and GWT is handling it by just logging and ignoring the exception because it won't affect the outcome of the compilation: https://github.com/gwtproject/gwt/blob/2.8.2/dev/core/src/com/google/gwt/core/ext/linker/impl/StandardLinkerContext.java#L528-L533

In this case, this is a CSV file mapping source CSS class names to obfuscated ones, so you won't be able to have it for debugging (or further post-processing); and GWT logs the error so you won't wonder why you don't find the cssmap file while in other cases it exists.

See #8599 (for this specific case), and other similar issues.
