### ISSUE TITLE
Upgrade Jetty to 9.x

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8712]
Originally reported on Google Code with ID 8747
```
Jetty 8.1 is outdated, please upgrade to the Jetty release 9.x.

Found in GWT Release: trunk

Detailed description (please be as specific as possible):

If project using GWT depends on Jetty 9.1 then it collides with the Jetty 8.1 packaged
in gwt-dev.jar.

Workaround if you have one:

The only known workaround to make it work is to strip Jetty packages from gwt-dev.jar
and use
more recent Jetty 9.1 installation during fetching from Maven repository.

Unfortunately this works only unless gwt-codeserver.jar is used. Trying to set up SuperDevMode

and start codeserver with stripped gwt-dev.jar refuses to work:

Compile completed in 21470 ms
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/nio/SelectChannelConnector
	at com.google.gwt.dev.codeserver.WebServer.start(WebServer.java:108)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:101)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:71)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:49)

 
```

Reported by `David.Ostrovsky` on 2014-06-03 10:43:17

**Comment by pgtaboada** [comment]
What is the status of this issue?

**Comment by wisebaldone** [comment]
Is there anyway that this can be pushed up in priority

**Comment by davido** [comment]
It's done and is ready to be merged: [1].

* [1] https://gwt-review.googlesource.com/7857

**Comment by wisebaldone** [comment]
@davido you still need to put the jetty 9 libs in the tools repo from talking to devs on ##gwt so that the automated tests can work.

**Comment by tbroyer** [comment]
I think you can make a pull request on the [`tools` repo](https://github.com/gwtproject/tools)

**Comment by davido** [comment]
| I think you can make a pull request on the tools repo

https://github.com/gwtproject/tools/pull/3
