### ISSUE TITLE
AutoBean is not able to unparse json

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8765]
Originally reported on Google Code with ID 8802

```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk): 2.6.1



Encountered on OS / Browser (e.g. WinXP, IE9, FF10): dev mode, FF24



Detailed description (please be as specific as possible):

I get his exception when I try to read from json

11:09:29.628 [ERROR] [customer] Unable to load module entry point class fr.onevu.vume.customer.Customer
(see associated exception for details)

com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Incorrect
size: 3
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:203)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at fr.onevu.vume.client.common.VuMePlaceController.goTo(VuMePlaceController.java:83)
    at com.google.gwt.place.shared.PlaceHistoryHandler.handleHistoryToken(PlaceHistoryHandler.java:192)
    at com.google.gwt.place.shared.PlaceHistoryHandler.handleCurrentHistory(PlaceHistoryHandler.java:118)
    at fr.onevu.vume.customer.Customer.initViews(Customer.java:110)
    at fr.onevu.vume.client.common.BaseEntryPoint.onModuleLoad(BaseEntryPoint.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:411)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: Incorrect size: 3
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$CoderCreator.getCoder(AutoBeanCodexImpl.java:124)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyCoderCreator.maybeCreateCoder(AutoBeanCodexImpl.java:354)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyCoderCreator.visitReferenceProperty(AutoBeanCodexImpl.java:341)
    at com.google.web.bindery.autobean.shared.AutoBeanVisitor.visitCollectionProperty(AutoBeanVisitor.java:229)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:440)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getTypeStr(ContextDynamicFieldProxyAutoBean.java:235)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getTypeStr(ContextDynamicFieldProxyAutoBean.java:58)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:424)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getParentDivs(ContextDynamicFieldProxyAutoBean.java:226)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getParentDivs(ContextDynamicFieldProxyAutoBean.java:46)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:397)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getId(ContextDynamicFieldProxyAutoBean.java:214)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getId(ContextDynamicFieldProxyAutoBean.java:30)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:361)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getGroupId(ContextDynamicFieldProxyAutoBean.java:211)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getGroupId(ContextDynamicFieldProxyAutoBean.java:26)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:352)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getSystem(ContextDynamicFieldProxyAutoBean.java:208)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getSystem(ContextDynamicFieldProxyAutoBean.java:22)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:343)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getOrder(ContextDynamicFieldProxyAutoBean.java:204)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getOrder(ContextDynamicFieldProxyAutoBean.java:18)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:334)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getBusinessKey(ContextDynamicFieldProxyAutoBean.java:198)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getBusinessKey(ContextDynamicFieldProxyAutoBean.java:10)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:316)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.isDefaultItem(ContextDynamicFieldProxyAutoBean.java:194)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.isDefaultItem(ContextDynamicFieldProxyAutoBean.java:6)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.traverseProperties(ContextDynamicFieldProxyAutoBean.java:307)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.traverse(AbstractAutoBean.java:166)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.accept(AbstractAutoBean.java:101)
    at com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl.doCoderFor(AutoBeanCodexImpl.java:522)
    at com.google.web.bindery.autobean.shared.impl.AbstractAutoBean.getOrReify(AbstractAutoBean.java:239)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean.access$7(ContextDynamicFieldProxyAutoBean.java:1)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$2.getCategoryiesKeys(ContextDynamicFieldProxyAutoBean.java:244)
    at fr.onevu.vume.client.proxy.ContextDynamicFieldProxyAutoBean$1.getCategoryiesKeys(ContextDynamicFieldProxyAutoBean.java:84)
    at fr.onevu.vume.client.common.Environment$CatgoriesManager.readAllFieldDefinitionsByCategroyKeys(Environment.java:765)
    at fr.onevu.vume.client.common.Environment$CatgoriesManager.readCategories(Environment.java:676)
    at fr.onevu.vume.client.common.Environment.loadCategories(Environment.java:1230)
    at fr.onevu.vume.client.common.Environment.preloadEnvironment(Environment.java:2037)
    at fr.onevu.vume.client.common.Environment.checkEnvironment(Environment.java:2200)
    at fr.onevu.vume.client.common.Environment.onEnvironementEvent(Environment.java:2160)
    at fr.onevu.vume.customer.CustomerEnvironment.onEnvironementEvent(CustomerEnvironment.java:45)
    at fr.onevu.vume.client.event.EnvironmentEvent.dispatch(EnvironmentEvent.java:131)
    at fr.onevu.vume.client.event.EnvironmentEvent.dispatch(EnvironmentEvent.java:1)
    at com.google.gwt.event.shared.GwtEvent.dispatch(GwtEvent.java:1)
    at com.google.web.bindery.event.shared.EventBus.dispatchEvent(EventBus.java:40)
    at com.google.web.bindery.event.shared.SimpleEventBus.doFire(SimpleEventBus.java:193)
    at com.google.web.bindery.event.shared.SimpleEventBus.fireEvent(SimpleEventBus.java:88)
    at fr.onevu.vume.client.common.VuMePlaceController.goTo(VuMePlaceController.java:83)
    at com.google.gwt.place.shared.PlaceHistoryHandler.handleHistoryToken(PlaceHistoryHandler.java:192)
    at com.google.gwt.place.shared.PlaceHistoryHandler.handleCurrentHistory(PlaceHistoryHandler.java:118)
    at fr.onevu.vume.customer.Customer.initViews(Customer.java:110)
    at fr.onevu.vume.client.common.BaseEntryPoint.onModuleLoad(BaseEntryPoint.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:411)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364)
    at java.lang.Thread.run(Thread.java:745)





Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):
this line reads the json
List<ContextDynamicFieldProxy> allFieldDefinitions = AutoBeanCodex.decode(fieldsFactory,
FieldsList.class, fieldsJsonString).as().getFields();

fieldsFactory is defined as follows

public static interface FieldsFactory extends AutoBeanFactory {
            // Factory method for a simple AutoBean
            AutoBean<ContextDynamicFieldProxy> field();

            AutoBean<FieldsList> fieldList();

            AutoBean<ValuePair<VisibleInView, DynamicFieldLabelPosition>> diplayLabelInView();

            // Factory method for a non-simple type or to wrap an existing instance
            AutoBean<ContextDynamicFieldProxy> wrapField(ContextDynamicFieldProxy toWrap);
        }


And the interface is the following

public interface ContextDynamicFieldProxy {
    public Long getId();

    // DynamicFieldLabelPosition labelPosition(VisibleInView view);

    DynamicFieldBusinessKey getBusinessKey();

    void setBusinessKey(DynamicFieldBusinessKey businessKey);

    String getDefaultSimpleValue();

    void setDefaultSimpleValue(String value);

//... other properties
// when I add the following property it crashes

    List<ValuePair<VisibleInView, DynamicFieldLabelPosition>> getPerViewLabelsPositions();

    void setPerViewLabelsPositions(List<ValuePair<VisibleInView, DynamicFieldLabelPosition>>
labelsPerViews);
}
Workaround if you have one:
declare the problematic property as json, and do the job separately
    String getPerViewLabelsPositionsJson();

    void setPerViewLabelsPositionsJson(String perViewLabelsPositions);

where ValuePair is an interface
public interface ValuePair<K, V> {

    V getValue();

    void setValue(V value);

    K getKey();

    void setKey(K key);

}

and VisibleInView, DynamicFieldLabelPosition are enuerations.

Links to relevant GWT Developer Forum posts:
nothing found about this issue 


Link to patch posted at http://gwt-review.googlesource.com


```

Reported by `1vue.eu` on 2014-06-28 10:21:42

**Comment by niloc132** [comment]
Closing as not enough info.
