### ISSUE TITLE
Compiler exception when mixing anonymous classes and lambdas

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8991]
Originally reported on Google Code with ID 9038
```
I posted on issue 8373 but was told to open a separate issue. When using the latest
version from git (Dec 4), there is a compiler exception when compiling code with mixed
anonymous classes and lambdas:

public class GwtTest implements EntryPoint {
    interface Callback { void onCallback(); };
    
    public void onModuleLoad() {
        final String s = new String("123");
        Callback c = () -> new Callback() {
            public void onCallback() {
                String a = s;
            }
        };
        c.onCallback();
    }
}

or:

public class GwtTest implements EntryPoint {
    public void onModuleLoad() {
        Runnable a = new Runnable() {
            public void run() {
                Runnable b = () -> {};
            }
        };
    }
}

Using anonymous inner classes by themselves, or lambdas by themselves works, but nesting
them together doesn't. Sometimes anonymous inner classes are required because we need
to override multiple or non-abstract methods, but it would still be useful to use lambda
expressions within these methods.
```

Reported by `d22344` on 2014-12-04 02:47:09

<hr>
 * *Attachment: [anonymous-stacktrace.txt](https://storage.googleapis.com/google-code-attachments/google-web-toolkit/issue-9038/comment-0/anonymous-stacktrace.txt)*

**Comment by axls** [comment]
Seems proplem is still reproducable when lambda placed in local anonymous class. Code snippet below leads to compile exception:
```java
package test.client;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.user.client.Window;

public class Test implements EntryPoint {
  interface Outer {
    void outerMethod();
  }
  interface Lambda {
    void lambdaMethod();
  }
  public void onModuleLoad() {
    String outerLocalVar = "testValue";
    Outer outer = new Outer() {
      public void outerMethod() {
        Lambda lambda = () -> Window.alert(outerLocalVar);
        lambda.lambdaMethod();
      }
    };
    outer.outerMethod();
  }
}
```

Stacktrace:
```
Compiling module test.Test
[ERROR] Unexpected internal compiler error
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
	at com.google.gwt.thirdparty.guava.common.base.Absent.get(Absent.java:47)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.replaceLambdaWithInnerClassAllocation(GwtAstBuilder.java:1391)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1258)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.traverse(LambdaExpression.java:689)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:309)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:355)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1415)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:609)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:309)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:355)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3825)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3856)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:383)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:488)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:453)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1017)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.run(Compiler.java:197)
	at com.google.gwt.dev.Compiler.run(Compiler.java:156)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:124)
```

The problem is in ```replaceLambdaWithInnerClassAllocation``` where ```outerLocalVar``` SyntheticArgument isn't present in local scope of outerMethod.

**Comment by axls** [comment]
Patch to review https://gwt-review.googlesource.com/#/c/13340
