### ISSUE TITLE
AssertError in draft mode for duplicate method reference symbol

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9119]
Originally reported on Google Code with ID 9190
```


Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

master/b2d397f69cc8ab9b90c1ae7e77827caaca0e73bd

Encountered on OS / Browser (e.g. WinXP, IE9, FF10):

Kubuntu 15.04, Chrome 42.0.2311.82

Detailed description (please be as specific as possible):

AssertError when compiling in draft mode code from sample (below). 

Stacktrace:
      [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
	at com.google.gwt.dev.jjs.ast.JProgram.visitAllTypes(JProgram.java:1157)
	at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$CreateNamesAndScopesVisitor.visit(GenerateJavaScriptAST.java:413)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1129)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.execImpl(GenerateJavaScriptAST.java:3634)
	at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.exec(GenerateJavaScriptAST.java:3296)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:375)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:269)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError
	at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$CreateNamesAndScopesVisitor.recordSymbol(GenerateJavaScriptAST.java:699)
	at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$CreateNamesAndScopesVisitor.visit(GenerateJavaScriptAST.java:519)
	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:114)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
	... 13 more
         [ERROR] at A.java(14): com.google.gwt.core.client.Scheduler$ScheduledCommand$test4$client$A$ma__V$Type
(final extends Object implements Scheduler$ScheduledCommand)
            com.google.gwt.dev.jjs.ast.JClassType
         [ERROR] at Unknown(0): <JProgram>
            com.google.gwt.dev.jjs.ast.JProgram
      [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:436)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:269)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
      [ERROR] Not all permutation were compiled , completed (0/1)


Seems that code lines 

Scheduler.get().scheduleDeferred(this::ma) 

and

Scheduler.get().scheduleDeferred(a::ma)

both generate the same SymbolData for method reference on A.ma()

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

A.java

public class A {

  public void ma() {
    Window.alert("A");
  }

  public void generatesLambdaSymbolDuplicate() {
    Scheduler.get().scheduleDeferred(this::ma);
  }
}

Test.java

public class Test implements EntryPoint {

  private A a = new A();

  public void onModuleLoad() {
    Scheduler.get().scheduleDeferred(a::ma);
  }

}

Workaround if you have one:

I didn't see any logical errors. So, just do not use -ea VM argument when launching
compiler.


Links to relevant GWT Developer Forum posts:



Link to patch posted at http://gwt-review.googlesource.com


```

Reported by `Alexander.Leshkin` on 2015-04-29 14:57:33

**Comment by rluble** [comment]
This one should be fixed by now. Reopen is still reproducible.
