### ISSUE TITLE
AutoBeanFactory instances throw ClassCastException for #toString()

### ISSUE THREAD

**Issue by ankon** [gwtproject/gwt#9150]
When calling `#toString()` on an instance of AutoBeanFactory (i.e. a proxy backed by FactoryHandler) the following exception occurs:

~~~~
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at com.google.web.bindery.autobean.vm.impl.FactoryHandler.invoke(FactoryHandler.java:70)
	at com.sun.proxy.$Proxy4.toString(Unknown Source)
~~~~

This is for the AutoBean code running inside the JVM, I've not tried doing that in generated JS code.

Looking through the code this probably also happens for `#equals()` and `#hashCode()`.

**Comment by ankon** [comment]
Fixed by https://github.com/gwtproject/gwt/commit/f077eee5f7bfbef249f7b2aa03e6c32b0888ad7e
