### ISSUE TITLE
"Internal compiler exception" with GWT 2.8-SNAPSHOT, Guice 4.0

### ISSUE THREAD

**Issue by Leonya** [gwtproject/gwt#9178]
I am trying to move my project to use GWT 2.8-SNAPSHOT in order to use lambdas.

If I drop the snapshot in place of 2.7 the code builds fine. If I convert the codebase to use lambdas the build fails (some kind of injection failure). I tried to upgrade to Guice 4.0 from Guice 3.0, now I'm getting the following exception:

```
Error:GWT Compiler: An internal compiler exception occurred
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:67)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:49)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:693)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:685)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1374)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:875)
Error:GWT Compiler: at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1424)
Error:GWT Compiler: at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1236)
Error:GWT Compiler: at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1156)
Error:GWT Compiler: at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:252)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.run(Compiler.java:197)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.run(Compiler.java:156)
Error:GWT Compiler: at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
Error:GWT Compiler: at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
Error:GWT Compiler: at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.main(Compiler.java:124)
Error:GWT Compiler: at java.lang.Class.getDeclaredMethods0(Native Method)
Error:GWT Compiler: at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
Error:GWT Compiler: at java.lang.Class.getDeclaredMethods(Class.java:1975)
Error:GWT Compiler: at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:132)
Error:GWT Compiler: at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
Error:GWT Compiler: at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
Error:GWT Compiler: at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
Error:GWT Compiler: at com.google.inject.PrivateModule.install(PrivateModule.java:184)
Error:GWT Compiler: at com.google.gwt.inject.rebind.resolution.ResolutionModule.configure(ResolutionModule.java:28)
Error:GWT Compiler: at com.google.inject.PrivateModule.configure(PrivateModule.java:100)
Error:GWT Compiler: at com.google.inject.AbstractModule.install(AbstractModule.java:122)
Error:GWT Compiler: at com.google.gwt.inject.rebind.GinjectorGeneratorModule.configure(GinjectorGeneratorModule.java:67)
Error:GWT Compiler: at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
Error:GWT Compiler: at com.google.inject.spi.Elements.getElements(Elements.java:110)
Error:GWT Compiler: at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
Error:GWT Compiler: at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
Error:GWT Compiler: at com.google.inject.Guice.createInjector(Guice.java:96)
Error:GWT Compiler: at com.google.inject.Guice.createInjector(Guice.java:73)
Error:GWT Compiler: at com.google.inject.Guice.createInjector(Guice.java:62)
Error:GWT Compiler: at com.google.gwt.inject.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:74)
Error:GWT Compiler: at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
Error:GWT Compiler: at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
Error:GWT Compiler: at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
Error:GWT Compiler: at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
Error:GWT Compiler: at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
Error:GWT Compiler: at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
Error:GWT Compiler: at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:493)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:463)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.handleMagicMethodCall(UnifyAst.java:588)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.endVisit(UnifyAst.java:293)
Error:GWT Compiler: at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:251)
Error:GWT Compiler: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Error:GWT Compiler: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Error:GWT Compiler: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
Error:GWT Compiler: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Error:GWT Compiler: at AppLoader.java(9): GWT.create(AppGinjector.class)
Error:GWT Compiler: at AppLoader.java(9): (AppGinjector) GWT.create(AppGinjector.class)
Error:GWT Compiler: at AppLoader.java(9): final AppGinjector injector = (AppGinjector) GWT.create(AppGinjector.class)
Error:GWT Compiler: at AppLoader.java(8): {
Error:GWT Compiler: at AppLoader.java(8): com.jetbrains.upsource.frontend.application.client.AppLoader.start()V
```

I'm guessing, GIN 2.1.2 is not compatible with Guice 4.0... Are there plans to release a GIN update? Or maybe GWT codebases making heavy use of lambdas are supposed to work with Guice 3.0?

**Comment by Leonya** [comment]
My bad, some Guice jars were missing.
