### ISSUE TITLE
reduce compiler memory consumption by initializing StringBuilder initial capacity

### ISSUE THREAD

**Issue by djeanprost** [gwtproject/gwt#9183]
Hello,

I'm meeting a problem during gwt compilation. My application is quite big.

    [INFO] Permutation 8 (strong name BA14D66EEC73FB44262423A88ADFC40E) has an initial download size of 19984060 and total script size of 37457074
    [INFO]   Invoking Linker RPC policy file manifest
    [INFO]    Invoking Linker Cross-Site-Iframe
    [INFO]       [ERROR] Failed to link
    [INFO] java.lang.OutOfMemoryError: Java heap space
    [INFO]  at java.util.Arrays.copyOf(Arrays.java:2367)
    [INFO]  at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
    [INFO]  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
    [INFO]  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
    [INFO]  at java.lang.StringBuilder.append(StringBuilder.java:132)
    [INFO]  at com.google.gwt.core.linker.CrossSiteIframeLinker.wrapPrimaryFragment(CrossSiteIframeLinker.java:700)
    [INFO]  at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.generatePrimaryFragmentString(SelectionScriptLinker.java:406)
    [INFO]  at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.generatePrimaryFragment(SelectionScriptLinker.java:377)
    [INFO]  at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.doEmitCompilation(SelectionScriptLinker.java:254)
    [INFO]  at com.google.gwt.core.ext.linker.impl.SelectionScriptLinker.link(SelectionScriptLinker.java:196)
    [INFO]  at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.invokeLinkForOnePermutation(StandardLinkerContext.java:381)
    [INFO]  at com.google.gwt.dev.Link.finishPermutation(Link.java:489)
    [INFO]  at com.google.gwt.dev.Link.doSimulatedShardingLink(Link.java:450)
    [INFO]  at com.google.gwt.dev.Link.link(Link.java:182)
    [INFO]  at com.google.gwt.dev.Compiler.run(Compiler.java:246)
    [INFO]  at com.google.gwt.dev.Compiler.run(Compiler.java:158)
    [INFO]  at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
    [INFO]  at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
    [INFO]  at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
    [INFO]  at com.google.gwt.dev.Compiler.main(Compiler.java:127)
    [INFO]  [ERROR] Out of memory; to increase the amount of memory, use the -Xmx flag at startup (java -Xmx128M ...)
    [INFO] Shutting down PersistentUnitCache thread

The problem appears while appending String using a StringBuilder which size is not initialized. As permutations size is huge, I guess it would work better (needing less heap) if the initial StringBuilder size was initialized with a big value (in code or through a parameter). 

    AbstractStringBuilder : 

    void More ...expandCapacity(int minimumCapacity) {
    111         int newCapacity = (value.length + 1) * 2;
    112         if (newCapacity < 0) {
    113             newCapacity = Integer.MAX_VALUE;
    114         } else if (minimumCapacity > newCapacity) {
    115             newCapacity = minimumCapacity;
    116         }
    117         value = Arrays.copyOf(value, newCapacity); <-- value exists twice here, doubling memory consumption.
    118     }

If permutation size is known before entering in CrossSiteIframeLinker, I think StringBuilder should be initialized correctly.
I don't even mention the number of array copies needed to allocate several Mb by starting from 16 bytes to final size.

Discussion here : https://groups.google.com/d/msg/google-web-toolkit/ImLEQ75PVj0/i83lwkgoCAAJ

**Comment by tbroyer** [comment]
> I don't even mention the number of array copies needed to allocate several Mb by starting from 16 bytes to final size.

If you look at the code here: https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/core/linker/CrossSiteIframeLinker.java#L674-L706 you can see that in most cases (`shouldIncludeBootstrapInPrimaryFragment` is always `false` in `CrossSiteIframeLinker` itself, and `shouldInstallCode` defaults to whether the output is _compact_ –i.e. minified– or not; in ) there'll be only 4 calls to `append()`. In your case, you executed line 700, so there was only 2 calls to `append`, so only 2 array copies. The problem is that to append a single char (`\n`), `StringBuilder` doubles the allocated memory (which means it temporarily triples it).

So, I totally agree that there's a simple optimization that could save hundreds of Kb of memory, but it's only about the size (and waste) of the allocated memory, not the number of times it has to be done (at least not in this part of the code).

/cc @rluble

**Comment by javexpress** [comment]
I have the same problem. Is there a workaround.

**Comment by javexpress** [comment]
I think my problem is with resource files size. Finally i figured out that when compiling with english no problem, when compiling with my main language it throws Heap Error. English resource files are almost empty. My issue is #9191 

I think the problem is same with this issue.
