### ISSUE TITLE
GWT Compiler Heap Size problem

### ISSUE THREAD

**Issue by javexpress** [gwtproject/gwt#9191]
I have a really big application nearly 700 forms. It was compiling without a problem. But now it raises Heap size error. But in the past i was experienced if some error occurs during compilation it cant report it instead it throws Heap exception (I think reporting causes). Anyway although we set 12GB heap for compiler nothing changed. But last week it was compiling with 7GB heap. How to find out whats going wrong. Since the application is currently being used by our customers we need urgent help or any ideas?

Here is the log tail:

     [java]    Replacing GWT.runAsync with island loader calls
     [java]    Looking up initial load sequence for split points
     [java]    Initial load sequence of split points: (none)
     [java]    removing source artifacts
     [java]    Compiling 6 permutations
     [java]       Creating worker permutation 0 of 6
     [java]       Creating worker permutation 1 of 6
     [java]       Creating worker permutation 2 of 6
     [java]       Creating worker permutation 3 of 6
     [java]       Creating worker permutation 4 of 6
     [java]       Creating worker permutation 5 of 6
     [java]       Creating PermutationWorkerFactory instances
     [java]          Factory impl property is com.google.gwt.dev.ThreadedPermutationWorkerFactory,com.google.gwt.dev.ExternalPermutationWorkerFactory
     [java]          Initializing ThreadedPermutationWorkerFactory
     [java]          Added PermutationWorkerFactory com.google.gwt.dev.ThreadedPermutationWorkerFactory
     [java]          Listening for external workers on port 42609
     [java]          Added PermutationWorkerFactory com.google.gwt.dev.ExternalPermutationWorkerFactory
     [java]       Creating ThreadedPermutationWorkers
     [java]       Compiling permutation 0...
     [java]       Splitting JavaScript for incremental download
     [java]       Permutation took 176305 ms
     [java]       [ERROR] OutOfMemoryError: Increase heap size or lower gwt.jjs.maxThreads
     [java] java.lang.OutOfMemoryError: Java heap space
     [java] 	at java.util.HashMap.resize(HashMap.java:580)
     [java] 	at java.util.HashMap.addEntry(HashMap.java:879)
     [java] 	at java.util.HashMap.put(HashMap.java:505)
     [java] 	at java.util.HashSet.add(HashSet.java:217)
     [java] 	at com.google.gwt.dev.jjs.impl.ControlFlowAnalyzer$RescueVisitor.rescue(ControlFlowAnalyzer.java:613)
     [java] 	at com.google.gwt.dev.jjs.impl.ControlFlowAnalyzer$RescueVisitor.visit(ControlFlowAnalyzer.java:403)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.visit(JVisitor.java:705)
     [java] 	at com.google.gwt.dev.jjs.impl.ControlFlowAnalyzer$RescueVisitor.visit(ControlFlowAnalyzer.java:450)
     [java] 	at com.google.gwt.dev.jjs.ast.JNewInstance.traverse(JNewInstance.java:83)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:156)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.acceptImmutable(JVisitor.java:164)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:255)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:246)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
     [java] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:156)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemove(JVisitor.java:178)
     [java] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:149)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:145)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:600)
     [java] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:569)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
     [java] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
     [java] 	at com.google.gwt.dev.jjs.impl.ControlFlowAnalyzer$RescueVisitor.rescue(ControlFlowAnalyzer.java:619)
     [java] 	at com.google.gwt.dev.jjs.impl.ControlFlowAnalyzer$RescueVisitor.visit(ControlFlowAnalyzer.java:403)
     [java]          [ERROR] Out of memory; to increase the amount of memory, use the -Xmx flag at startup (java -Xmx128M ...)
     [java]       [ERROR] Unrecoverable exception, shutting down
     [java] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
     [java] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:56)
     [java] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java]       [ERROR] Not all permutation were compiled , completed (0/6)
     [java] Shutting down PersistentUnitCache thread

**Comment by jnehlmeier** [comment]
Are you trying to compile all permutations in parallel? 

Try using a lower value for `-localWorkers` command line parameter and/or the system property `gwt.jjs.maxThreads`.

**Comment by javexpress** [comment]
I tried to compile in parallel and not in parallel. It throws Heap exception in both cases. But i found a trick just now. Please see my comment in #9183

**Comment by branflake2267** [comment]
Increasing the heap size actually causes a bigger problem with css resources don't get closed. At least thats what I saw last.

**Comment by heiko-braun** [comment]
@branflake2267 can you elaborate on the css resource problem?

**Comment by symetria-dev** [comment]
Hi, I found this post very useful: http://stackoverflow.com/a/20119958/3192300 , basically you increase the memory heap in the debug / run arguments.

**Comment by sliqiao** [comment]
Wow,here is what you want "https://groups.google.com/forum/#!topic/google-web-toolkit/E2WXihMOCTY"!That is the right solution!

**Comment by kajuga** [comment]
hola.
you can put this in pom.xml of your module
                    <extraJvmArgs>-Xms896m -Xmx896m -Dgwt.jjs.permutationWorkerFactory=com.google.gwt.dev.ThreadedPermutationWorkerFactory</extraJvmArgs>
                    <localWorkers>3</localWorkers>
it's work for me
