### ISSUE TITLE
Increase WebAppCreator maxMemory in build.xml as it fails on windows 7 ant gwtc

### ISSUE THREAD

**Issue by branflake2267** [gwtproject/gwt#9213]
On Windows 7, running `ant gwtc` fails and it throws an out of memory exception.

**Comment by branflake2267** [comment]
I'm running the compile to verify the threshold and I can't replicate it yet.

**Comment by branflake2267** [comment]
Error
```
Buildfile: C:\Users\branflake2267\Desktop\gwt-2.8.0-beta1\TestProject\build.xml

libs:

javac:
    [javac] C:\Users\branflake2267\Desktop\gwt-2.8.0-beta1\TestProject\build.xml:31: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

gwtc:
     [java] Compiling module com.google.gwt.TestProject
     [java] Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
     [java] 	at java.util.HashMap.<init>(HashMap.java:283)
     [java] 	at java.util.HashMap.<init>(HashMap.java:297)
     [java] 	at java.util.HashSet.<init>(HashSet.java:142)
     [java] 	at org.eclipse.jdt.internal.compiler.ClassFile.recordInnerClasses(ClassFile.java:5168)
     [java] 	at org.eclipse.jdt.internal.compiler.util.Util.recordNestedType(Util.java:1071)
     [java] 	at org.eclipse.jdt.internal.compiler.codegen.ConstantPool.literalIndex(ConstantPool.java:360)
     [java] 	at org.eclipse.jdt.internal.compiler.ClassFile.addFieldInfo(ClassFile.java:536)
     [java] 	at org.eclipse.jdt.internal.compiler.ClassFile.addFieldInfos(ClassFile.java:581)
     [java] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:554)
     [java] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:636)
     [java] 	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:368)
     [java] 	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:814)
     [java] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:344)
     [java] 	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:488)
     [java] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:453)
     [java] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1017)
     [java] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
     [java] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
     [java] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
     [java] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
     [java] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
     [java] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
     [java] 	at com.google.gwt.dev.Compiler.run(Compiler.java:197)
     [java] 	at com.google.gwt.dev.Compiler.run(Compiler.java:156)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:124)

**Comment by branflake2267** [comment]
https://gwt-review.googlesource.com/#/c/13955/

**Comment by gkdn** [comment]
This is probably related tp JDT java 8 memory issue that we discussed earlier. Passing -sourceLevel 7 should probably temporarily resolve the issue.

**Comment by branflake2267** [comment]
I used the JDK 1.7 to compile on Windows. I haven't tried Java 8 yet.

**Comment by branflake2267** [comment]
The issue has been merged, so I'll close the issue and reopen if it exists. 
https://gwt-review.googlesource.com/#/c/13955/
