### ISSUE TITLE
XMLParser fails to parse XML documents with spaces and line breaks.

### ISSUE THREAD

**Issue by pybeaudouin** [gwtproject/gwt#9222]
The XMLParser.parse generates a Document instance but trying to access to child attributes generates the exception below.

Accessing these attributes works when removing the indentation spaces and line breaks:

```
---- NO INDENTATION + NO LINE BREAKS ----
Foo node attribute: bar = 'yes'
Child node attribute: a = '15.6'
Child node attribute: b = 'y'
Child node attribute: c = ''
Foo node attribute: bar = 'orange'
Child node attribute: a = '17.5'
Child node attribute: b = 'yearly'
Child node attribute: c = ''
200 - POST /bugs.com.google.gwt.xml.XMLParser.JUnit/junithost (10.2.0.67) 191 bytes
---- NO INDENTATION + LINE BREAKS ----
Foo node attribute: bar = 'yes'
200 - POST /bugs.com.google.gwt.xml.XMLParser.JUnit/junithost (10.2.0.67) 208 bytes
---- INDENTATION + NO LINE BREAKS ----
Foo node attribute: bar = 'yes'
200 - POST /bugs.com.google.gwt.xml.XMLParser.JUnit/junithost (10.2.0.67) 188 bytes
---- INDENTATION + LINE BREAKS ----
Foo node attribute: bar = 'yes'
```

Attachments:
* [XMLParser.gwt.xml.txt](https://github.com/gwtproject/gwt/files/48872/XMLParser.gwt.xml.txt)
* [XMLParserTest.java.txt](https://github.com/gwtproject/gwt/files/48874/XMLParserTest.java.txt)

```
com.google.gwt.core.client.JavaScriptException: (null) @com.google.gwt.xml.client.impl.XMLParserImpl::getLength(Lcom/google/gwt/core/client/JavaScriptObject;)([null]): null
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:252)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeInt(ModuleSpace.java:267)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeInt(JavaScriptHost.java:75)
	at com.google.gwt.xml.client.impl.XMLParserImpl.getLength(XMLParserImpl.java)
	at com.google.gwt.xml.client.impl.NodeListImpl.getLength(NodeListImpl.java:33)
	at com.google.gwt.xml.client.impl.NamedNodeMapImpl.getLength(NamedNodeMapImpl.java:41)
	at bugs.com.google.gwt.xml.client.XMLParserTest.testParseInternal(XMLParserTest.java:84)
	at bugs.com.google.gwt.xml.client.XMLParserTest.testParseNotIndented(XMLParserTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.junit.client.impl.GWTTestAccessor.invoke(GWTTestAccessor.java:39)
	at com.google.gwt.junit.client.impl.GWTRunner.executeTestMethod(GWTRunner.java:226)
	at com.google.gwt.junit.client.GWTTestCase.doRunTest(GWTTestCase.java:157)
	at junit.framework.TestCase.runTest(TestCase.java:59)
	at com.google.gwt.junit.client.GWTTestCase.runBare(GWTTestCase.java:151)
	at com.google.gwt.junit.client.GWTTestCase.__doRunTest(GWTTestCase.java:115)
	at com.google.gwt.junit.client.impl.GWTRunner.runTest(GWTRunner.java:302)
	at com.google.gwt.junit.client.impl.GWTRunner.doRunTest(GWTRunner.java:235)
	at com.google.gwt.junit.client.impl.GWTRunner.access$9(GWTRunner.java:229)
	at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:106)
	at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:1)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
	at com.google.gwt.http.client.Request.fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessagesWhileWaitingForReturn(BrowserChannelServer.java:341)
	at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:222)
	at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:137)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:589)
	at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:293)
	at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
	at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:72)
	at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:172)
	at com.google.gwt.dev.shell.BrowserChannelServer.reactToMessages(BrowserChannelServer.java:296)
	at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:551)
	at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:368)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jnehlmeier** [comment]
Its not really a GWT bug but your code is wrong. I guess the only issue in GWT is that the JavaDoc of `Node.getAttributes()` (and possibly others) isn't great compared to the implementation of that method in GWT.

```java
         NodeList childNodeList = fooNode.getChildNodes();
         int lengthAccrual = childNodeList.getLength();
         for(int k = 0; k < lengthAccrual; k++) {
            Node childNode = childNodeList.item(k);
            childNode.normalize();
            NamedNodeMap childAttributes = childNode.getAttributes();
            Assert.assertNotNull(childAttributes);
            for(int l = 0; l < childAttributes.getLength(); l++) {
               Attr attr = (Attr)childAttributes.item(l);
               System.out.println("Child node attribute: " + attr.getName() + " = '" + attr.getValue() + "'");
            }
            Assert.assertEquals(3, childAttributes.getLength());
         }
```
When you call `fooNode.getChildNodes()` you get a list of nodes of any type. In the indentation example this node list would contain nodes of type `Node.TEXT_NODE` (the spaces) as well as `Node.ELEMENT_NODE` (the `<indentedNode>` element).

A text node does not have attributes so when you call `childNode.getAttributes()` you get an instance of `NamedNodeMap` that does not have any underlying `JavaScriptObject` it could read attributes from. Because of this `childAttributes.getLength()` throws a NPE as it tries to access the non-existent, internal `JavaScriptObject`.

You should only call `Node.getAttributes()` if the node is of type `Node.ELEMENT_NODE`. You can check that by using `Node.getNodeType()`.

For detailed description you could read:

http://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-1950641247

**Comment by pybeaudouin** [comment]
Thanks for the prompt response! Closing the issue.
