### ISSUE TITLE
GWT 2.8-beta1 & Guava 20.0-SNAPSHOT

### ISSUE THREAD

**Issue by spirylics** [gwtproject/gwt#9259]
I have tried guava 20.0-SNAPSHOT with gwt 2.8-beta1.
it works fine with a full compilation but not with dev mode and super dev mode ; I have this exception : 

```java
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:130)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transform(GenerateJavaScriptAST.java:2515)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformExpressionStatement(GenerateJavaScriptAST.java:695)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformExpressionStatement(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:730)
[INFO]  at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:41)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transformIntoExcludingNulls(JTransformer.java:1076)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformBlock(GenerateJavaScriptAST.java:578)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformBlock(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:622)
[INFO]  at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:91)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transform(GenerateJavaScriptAST.java:2523)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodBody(GenerateJavaScriptAST.java:812)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodBody(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:829)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:81)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethod(GenerateJavaScriptAST.java:787)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.generatePrototypeDefinitions(GenerateJavaScriptAST.java:2330)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.generateTypeSetup(GenerateJavaScriptAST.java:1833)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformDeclaredType(GenerateJavaScriptAST.java:641)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformDeclaredType(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transformClassType(JTransformer.java:95)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:670)
[INFO]  at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:140)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformProgram(GenerateJavaScriptAST.java:1202)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformProgram(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:918)
[INFO]  at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1252)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.execImpl(GenerateJavaScriptAST.java:3014)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.exec(GenerateJavaScriptAST.java:2795)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:378)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO]  at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO]  at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO]  at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.NullPointerException
[INFO]  at com.google.gwt.dev.jjs.ast.JMethod.getQualifiedJsName(JMethod.java:118)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.createStaticReference(GenerateJavaScriptAST.java:1707)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.dispatchToStatic(GenerateJavaScriptAST.java:886)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodCall(GenerateJavaScriptAST.java:874)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodCall(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:835)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:246)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  ... 52 more
[INFO]                [ERROR] at MapMaker.java(116): MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis))
[INFO]                   com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]                [ERROR] at MapMaker.java(116): MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis))
[INFO]                   com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]                [ERROR] at MapMaker.java(107): {
[INFO]   MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis));
[INFO] }
[INFO]                   com.google.gwt.dev.jjs.ast.JBlock
[INFO]                [ERROR] at MapMaker.java(107): {
[INFO]   MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis));
[INFO] }
[INFO]                   com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]                [ERROR] at MapMaker.java(42): com.google.common.collect.MapMaker$ExpiringComputingMap (extends LinkedHashMap implements ConcurrentMap)
[INFO]                   com.google.gwt.dev.jjs.ast.JClassType
[INFO]                [ERROR] at Unknown(0): <JProgram>
[INFO]                   com.google.gwt.dev.jjs.ast.JProgram
[INFO]             [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO]  at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO]  at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO]  at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO]  at java.lang.Thread.run(Thread.java:745)
[INFO]             [ERROR] Not all permutation were compiled , completed (0/1)
```

I don't known if the problem is guava side or gwt side, has someone ever met that ?

**Comment by cpovirk** [comment]
Does someone on the GWT side have an idea what might be going on here?

@spirylics, do you have a trivial project that demonstrates this issue that we could play around with? If all else fails, I can try making changes to Guava until it works :)

**Comment by jonl-percsolutions-com** [comment]
I did a bit of investigation and it appears that following the thread from here: at com.google.gwt.dev.jjs.ast.JMethod.getQualifiedJsName(JMethod.java:118)(https://github.com/gwtproject/gwt/blob/0a7b1bdf7411c17feef312b9ac9d0a7b79d1cd4b/dev/core/src/com/google/gwt/dev/jjs/ast/JMethod.java), the one way I could see for this to happen is if somehow there is a JField instantiated with a null name.  I didn't see anything that would prevent that possibility.

**Comment by gkdn** [comment]
Only explanation I can see is; you are passing "-XenableJsinteropMode JS" which is not compatible with Guava and can cause this failure.
This is an experimental flag and is going to be removed in final 2.8 release so you should migrate from it.

**Comment by spirylics** [comment]
yes @gkdn I have forgotten to drop jsinteropmode. 
So, last guava snapshot works fine with gwt 2.8.

Thanks
