### ISSUE TITLE
java.lang.ClassCastException in gwt compiler 2.8.0-20160321

### ISSUE THREAD

**Issue by aove215** [gwtproject/gwt#9305]
This fragment illustrates the problem area of code and how I worked round it

    public static <A, B> ImMap<A, B> from(Lst<B> values, Fn<B, A> getKeyFn)
    {
        Lst<Entry> es = values.map(v -> new Entry<A, B>(getKeyFn.of(v), v));

        // Had to change this line because gwt compiler crashed
        // return es.foldl(empty(), ImMap<A,B>::putEntry);
        return es.foldl(empty(), (entries, newEntry) -> entries.putEntry(newEntry));
    }

and this is the log of the compile as I got the problem and after I worked round it

[I] ~/p/d/drum % ./gradlew gwtCompile
:shared-utils:compileJava
Note: /Users/aove215/projects/drum/drum/shared-utils/src/main/java/com/drum/utils/misc/TextUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:shared-utils:processResources UP-TO-DATE
:shared-utils:classes
:shared-utils:jar
:dto:compileJava
Note: /Users/aove215/projects/drum/drum/dto/src/main/java/com/drum/dto/commands/mods/Mod.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:dto:processResources UP-TO-DATE
:dto:classes
:dto:jar UP-TO-DATE
:push:compileJava
:push:processResources UP-TO-DATE
:push:classes
:push:jar UP-TO-DATE
:server-utils:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:server-utils:processResources UP-TO-DATE
:server-utils:classes
:server-utils:jar
:core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:core:processResources UP-TO-DATE
:core:classes
:core:jar UP-TO-DATE
:browser:gwtCompile
Download https://oss.sonatype.org/content/groups/google/com/google/gwt/gwt-user/2.8.0-SNAPSHOT/gwt-user-2.8.0-20160321.055634-201.jar
Download https://oss.sonatype.org/content/groups/google/com/google/jsinterop/jsinterop-annotations/1.0.0-SNAPSHOT/jsinterop-annotations-1.0.0-20160321.055717-89.jar
Download https://oss.sonatype.org/content/groups/google/com/google/jsinterop/jsinterop-annotations/1.0.0-SNAPSHOT/jsinterop-annotations-1.0.0-20160321.055717-89-sources.jar
Download https://oss.sonatype.org/content/groups/google/com/google/gwt/gwt-dev/2.8.0-SNAPSHOT/gwt-dev-2.8.0-20160321.055625-201.jar
Download https://oss.sonatype.org/content/groups/google/com/google/gwt/gwt-servlet/2.8.0-SNAPSHOT/gwt-servlet-2.8.0-20160321.055641-201.jar
Compiling module com.drum.browser
[ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3869)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1536)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1043)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:388)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:357)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3812)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3843)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:546)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:458)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1022)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.run(Compiler.java:197)
	at com.google.gwt.dev.Compiler.run(Compiler.java:156)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:124)
Caused by: java.lang.ClassCastException: com.google.gwt.dev.jjs.ast.JDeclarationStatement cannot be cast to com.google.gwt.dev.jjs.ast.JExpression
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pop(GwtAstBuilder.java:2555)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1498)
	... 25 more
   [ERROR] at ImMap.java(207): es.foldl(empty(), ImMap<A, B>::putEntry)
      org.eclipse.jdt.internal.compiler.ast.MessageSend
:browser:gwtCompile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':browser:gwtCompile'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 3.665 secs
[I] ~/p/d/drum % ./gradlew gwtCompile
:shared-utils:compileJava UP-TO-DATE
:shared-utils:processResources UP-TO-DATE
:shared-utils:classes UP-TO-DATE
:shared-utils:jar UP-TO-DATE
:dto:compileJava UP-TO-DATE
:dto:processResources UP-TO-DATE
:dto:classes UP-TO-DATE
:dto:jar UP-TO-DATE
:push:compileJava UP-TO-DATE
:push:processResources UP-TO-DATE
:push:classes UP-TO-DATE
:push:jar UP-TO-DATE
:server-utils:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:server-utils:processResources UP-TO-DATE
:server-utils:classes
:server-utils:jar
:core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:core:processResources UP-TO-DATE
:core:classes
:core:jar UP-TO-DATE
:browser:gwtCompile
Compiling module com.drum.browser
   Ignored 17 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   Compiling 1 permutation
      Compiling permutation 0...
   Compile of permutations succeeded
   Compilation succeeded -- 10.880s
Linking into /Users/aove215/projects/drum/drum/browser/war/drum
   Link succeeded
   Linking succeeded -- 0.147s

BUILD SUCCESSFUL

Total time: 14.354 secs
[I] ~/p/d/drum % 

I can supply the full code if you need it

Cheers - Van

**Comment by jnehlmeier** [comment]
Given how you workaround it should the original code line be
```
return es.foldl(empty(), entries::putEntry);
```
or is `ImMap.putEntry` a static method?

**Comment by rluble** [comment]
This should be already fixed in patch https://gwt-review.googlesource.com/#/c/14900/

Marking as closed. Reopen if reproducible in snapshot.
