### ISSUE TITLE
Internal compiler error: NPE when compiling type to compile two modules

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9325]
Current master is at bfa96cd, but I saw this problem back at least three weeks of commits as well (though I haven't attempted to bisect). I have not yet reproduced with a minimal test case (app compiles out to be about 100kb)

What I do know so far is that the error only happens when attempting to compile two modules. Remove either module, and the error goes away. No arguments (`style`, `generateJsInteropExports`, `sourceLevel`, etc) appear to affect this - the app is typically compiled with them, but I've removed each to test if some difference is made.

```
...
   Compiling 1 permutation
      Compiling permutation 0...
      [ERROR] Unexpected internal compiler error
java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.JTypeOracle.recomputeAfterOptimizations(JTypeOracle.java:880)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1526)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1469)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:522)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:360)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
      [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
      [ERROR] Not all permutation were compiled , completed (0/1)
```

The two modules are written with one as a full GWT app, and another as a part of that app exported as a JS library for use elsewhere. The two modules share at least one source directory, and the other then adds several more source directories.

The NPE-ing method:

```
    //   (2) make JSOs singleImpl when all the Java implementors are gone.
    nextDual:
    for (Iterator<String> it = dualImplInterfaces.iterator(); it.hasNext(); ) {
      String dualIntf = it.next();
      for (String implementorName : classesByImplementingInterface.get(dualIntf)) {
        JClassType implementor = (JClassType) referenceTypesByName.get(implementorName);
        assert implementor != null;
        if (isInstantiatedType(implementor) && !implementor.isJsoType()) {
          // This dual is still implemented by a Java class.
          continue nextDual;
        }
      }
      // No Java implementors.
      it.remove();
    }
```

The failure is that `implementor` is null. `implementorName` is `"com.google.gwt.i18n.client.DefaultCurrencyData"`, and `dualIntf` is `"com.google.gwt.i18n.client.CurrencyData"`. `referenceTypesByName` has 979 types in it in this code. `referenceTypesByName` does not contain any value with that key (i.e. it doesn't map to null, it just isn't present). These values are consistently set this way.

I'll continue to debug and will attempt a minimal test case, but was hoping that this might be recognized before I get too deep into it.

---

Do note that the assert should in theory catch this - I attempted briefly to enable assertions, but it seems that just one module _individually_ will blow an assertion much earlier:

```
java.lang.AssertionError
	at com.google.gwt.dev.jjs.impl.JjsUtils.createSyntheticAbstractStub(JjsUtils.java:302)
	at com.google.gwt.dev.jjs.impl.ComputeOverridesAndImplementDefaultMethods.maybeAddSyntheticOverride(ComputeOverridesAndImplementDefaultMethods.java:283)
	at com.google.gwt.dev.jjs.impl.ComputeOverridesAndImplementDefaultMethods.computeOverrides(ComputeOverridesAndImplementDefaultMethods.java:151)
	at com.google.gwt.dev.jjs.impl.ComputeOverridesAndImplementDefaultMethods.exec(ComputeOverridesAndImplementDefaultMethods.java:78)
	at com.google.gwt.dev.jjs.impl.UnifyAst.computeOverrides(UnifyAst.java:1079)
	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:910)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1442)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1254)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1174)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.run(Compiler.java:197)
	at com.google.gwt.dev.Compiler.run(Compiler.java:156)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:124)
```
 I'll attempt to dig in deeper there as well, separately, but it seems unrelated at a glance - this is complaining about a lambda type that happens to implement `com.google.gwt.view.client.ProvidesKey.getKey(Ljava/lang/Object;)Ljava/lang/Object;`.

**Comment by niloc132** [comment]
Okay, I have the NPE nailed down to a very simple project. Directory structure:

 * src
  * main
    * java
      * sample
        * src1
          * Module1EP.java
        * src2
          * Module2EP.java
        * Module1.gwt.xml
        * Module2.gwt.xml

Module1EP.java:

```
package sample.src1;

import com.google.gwt.core.client.EntryPoint;

public class Module1EP implements EntryPoint {
    public void onModuleLoad() {
    }
}
```

Module2EP.java:

```
package sample.src2;

import com.google.gwt.core.client.EntryPoint;

public class Module2EP implements EntryPoint {
    public void onModuleLoad() {
    }
}
```

Module1.gwt.xml:

```
<module>
  <inherits name="com.google.gwt.user.User" />
  <inherits name="com.google.web.bindery.autobean.AutoBean"/>

  <source path="src1" />

  <entry-point class="sample.src1.Module1EP" />
</module>
```

Module2.gwt.xml:

```
<module>
  <inherits name="com.google.gwt.user.User" />

  <source path="src2" />

  <entry-point class="sample.src2.Module2EP" />
</module>
```

To get the error:

    java -cp ... com.google.gwt.dev.Compiler sample.Module1 sample.Module2

If you enable assertions, you'll get this log:

```
Compiling module sample.Module1
   Compiling 5 permutations
      Compiling permutation 0...
      Compiling permutation 1...
      Compiling permutation 2...
      Compiling permutation 3...
      Compiling permutation 4...
   Compile of permutations succeeded
   Compilation succeeded -- 4.629s
Linking into /Users/colin/workspace/gwt-mvn-conflict/war/sample.Module1
   Link succeeded
   Linking succeeded -- 0.148s
Compiling module sample.Module2
   Compiling 5 permutations
      Compiling permutation 0...
      [ERROR] Unexpected internal compiler error
java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.JTypeOracle.recomputeAfterOptimizations(JTypeOracle.java:880)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1526)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1469)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:522)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:360)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
      [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
      [ERROR] Not all permutation were compiled , completed (0/5)
```

Without assertions, its just an NPE. I don't have a good way to hit the other assertion yet.

**Comment by niloc132** [comment]
(whoops, hit send too early)

Changing the order in the Java arguments will not cause the exception. Removing the (unused...) AutoBean inherits statement in Module1.gwt.xml will prevent it as well. 

In this case, `dualIntf` is `"com.google.web.bindery.autobean.shared.Splittable"`, and `implementorName` is `"com.google.web.bindery.autobean.gwt.client.impl.JsoSplittable"`.

**Comment by jnehlmeier** [comment]
Sounds like a duplicate of #9155 ?

**Comment by niloc132** [comment]
Agreed - I'm closing this in favor of the existing one, though this might be helpful for isolating the specific issue.
