### ISSUE TITLE
SuperDevMode recompilation failure - NullPointerException in ZipFile

### ISSUE THREAD

**Issue by mmlleevvyy** [gwtproject/gwt#9339]
Hi, I'm using latest 2.8 SNAPSHOT and for past few days, from time to time I have recompilation failure in SuperDevMode. Below the exception:

```
java.lang.NullPointerException: entry
    at java.util.zip.ZipFile.getInputStream(ZipFile.java:347)
    at com.google.gwt.dev.resource.impl.ZipFileResource.openContents(ZipFileResource.java:74)
    at com.google.gwt.dev.javac.CompilationUnitBuilder$ResourceCompilationUnitBuilder.doGetSource(CompilationUnitBuilder.java:139)
    at com.google.gwt.dev.javac.CompilationUnitBuilder.getSource(CompilationUnitBuilder.java:285)
    at com.google.gwt.dev.javac.JdtCompiler$Adapter.getContents(JdtCompiler.java:221)
    at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11345)
    at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11317)
    at com.google.gwt.dev.javac.JdtCompiler$ParserImpl.parse(JdtCompiler.java:277)
    at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:9732)
    at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:809)
    at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:385)
    at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:428)
    at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1022)
    at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
    at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
    at com.google.gwt.dev.Compiler.run(Compiler.java:197)
    at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362)
    at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
    at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
    at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
    at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
    at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
    at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

I didn't experience that exception few weeks ago (working on 2.8 snapshot as well). Surely that can be related to my Eclipse or my environment, but maybe you are aware of changes in GWT that could cause that issue.

**Comment by tbroyer** [comment]
Could it be somehow due to a JAR file's content changing?

**Comment by lleevvyy** [comment]
@tbroyer Don't think so, cause the file I changed (and cause of that needed to recompile superdevmode) was in gwt project, that was run in superdevmode and so, the source files was read from project's src folder. No other changes, that could cause jar file's content change was made before recompile, at least I don't know anything about that, maybe Eclipse made some changes, but it is very unlikely. As I wrote, then exception is thrown from time to time, I cannot even say how to reproduce it, still that didn't happen few weeks ago, on previous snapshots (and my environment, project etc didn't change).

**Comment by tbroyer** [comment]
@rluble any idea? Maybe you saw that inside Google too?

**Comment by SButterfly** [comment]
@mmlleevvyy Did you find where the problem was?

**Comment by SButterfly** [comment]
I found where the problem was.
I somehow changed gwt code, before gwt compilation. When I rebuilt project the problem has gone.
