### ISSUE TITLE
Primitive/Boxed method reference compiler error

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9340]
Another odd one, fails as of current master, d480b32. Found while rebasing some java8 emulation, but I've managed to reduce it to a fairly minimal test case, no external dependencies. Title is mostly a guess based on the particular class cast exception, and that the generated code in the error appears to think that it is okay to reference an int as an Integer directly (?). 

I'm almost certain that this is a newly (re)introduced bug, and that it was not there a month ago, since this same code used to compile and pass its tests. I think it was fixed around the time that #9307 was fixed, but I'm not certain, will attempt a bisect later.

Test entrypoint, fails with just an inherits on User:

```
public class PrimitiveAndBoxedMethodReferences implements EntryPoint {
    public class ConsumerObject {
        private int total;//a field is required, without it, no bug
        public void primitiveConsumer(int i) {
            total += i;
            GWT.log("#" + total);
        }
    }

    @Override
    public void onModuleLoad() {
        takesObjPrimitiveConsumer(ConsumerObject::primitiveConsumer);
    }

    public void takesObjPrimitiveConsumer(ObjIntConsumer accumulator) {
        takesPrimitiveConsumer((int value) -> accumulator.accept(new ConsumerObject(), value));
    }

    public void takesPrimitiveConsumer(IntConsumer c) {
        c.accept(0);
    }

    public interface IntConsumer {
        void accept(int i);
    }
    public interface ObjIntConsumer {
        void accept(ConsumerObject obj, int i);
    }
}
```

Compiler log, building this as a standalone entrypoint:

```
[INFO] Compiling module sample3.PrimitiveAndBoxedReferences
[INFO]    Compiling 5 permutations
[INFO]       Compiling permutation 0...
[INFO]       [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:130)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JFieldRef.traverse(JFieldRef.java:110)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.acceptImmutable(JVisitor.java:154)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.visitChildren(JMethodCall.java:266)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:257)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemove(JVisitor.java:168)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:788)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:780)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemoveImmutable(JVisitor.java:172)
[INFO] 	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:147)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1284)
[INFO] 	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1249)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation.execImpl(ComputeCastabilityInformation.java:318)
[INFO] 	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation.exec(ComputeCastabilityInformation.java:297)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.normalizeSemantics(JavaToJavaScriptCompiler.java:503)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:364)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.ClassCastException: com.google.gwt.dev.jjs.ast.JPrimitiveType cannot be cast to com.google.gwt.dev.jjs.ast.JReferenceType
[INFO] 	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation$AssignTypeCastabilityVisitor.recordCast(ComputeCastabilityInformation.java:267)
[INFO] 	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation$AssignTypeCastabilityVisitor.endVisit(ComputeCastabilityInformation.java:156)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:74)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	... 40 more
[INFO]          [ERROR] at PrimitiveAndBoxedMethodReferences.java(17): (Integer) 0
[INFO]             com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]          [ERROR] at Integer.java(303): ((Integer) 0).nullField
[INFO]             com.google.gwt.dev.jjs.ast.JFieldRef
[INFO]          [ERROR] at PrimitiveAndBoxedMethodReferences.java(17): PrimitiveAndBoxedMethodReferences$ConsumerObject.$primitiveConsumer(new PrimitiveAndBoxedMethodReferences$ConsumerObject(), ((Integer) 0).nullField)
[INFO]             com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]          [ERROR] at PrimitiveAndBoxedMethodReferences.java(21): PrimitiveAndBoxedMethodReferences$ConsumerObject.$primitiveConsumer(new PrimitiveAndBoxedMethodReferences$ConsumerObject(), ((Integer) 0).nullField)
[INFO]             com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]          [ERROR] at sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder.java(3): {
[INFO]   UserAgentAsserter.scheduleUserAgentCheck();
[INFO]   DocumentModeAsserter.$onModuleLoad();
[INFO]   PrimitiveAndBoxedMethodReferences$ConsumerObject.$primitiveConsumer(new PrimitiveAndBoxedMethodReferences$ConsumerObject(), ((Integer) 0).nullField);
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JBlock
[INFO]          [ERROR] at sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder.java(3): {
[INFO]   UserAgentAsserter.scheduleUserAgentCheck();
[INFO]   DocumentModeAsserter.$onModuleLoad();
[INFO]   PrimitiveAndBoxedMethodReferences$ConsumerObject.$primitiveConsumer(new PrimitiveAndBoxedMethodReferences$ConsumerObject(), ((Integer) 0).nullField);
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]          [ERROR] at sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder.java(3): com.google.gwt.lang.sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder.init()V
[INFO]             com.google.gwt.dev.jjs.ast.JMethod
[INFO]          [ERROR] at sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder.java(2): com.google.gwt.lang.sample3_00046PrimitiveAndBoxedReferences__EntryMethodHolder (extends Object)
[INFO]             com.google.gwt.dev.jjs.ast.JClassType
[INFO]          [ERROR] at Unknown(0): <JProgram>
[INFO]             com.google.gwt.dev.jjs.ast.JProgram
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO] 	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]       [ERROR] Not all permutation were compiled , completed (0/5)
[INFO]       [WARN] Lost communication with remote process
```

In the original unit test for new jre emulation, the exception was a bit different - first, assertions were on, and second the Integer.value field was apparently not null at least once:

```
Caused by: java.lang.AssertionError
	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation$AssignTypeCastabilityVisitor.recordCast(ComputeCastabilityInformation.java:265)
	at com.google.gwt.dev.jjs.impl.ComputeCastabilityInformation$AssignTypeCastabilityVisitor.endVisit(ComputeCastabilityInformation.java:156)
	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:74)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	... 40 more
         [ERROR] at IntStream.java(648): (Integer) arg1
         [ERROR] at Integer.java(303): ((Integer) arg1).value
         [ERROR] at IntStream.java(648): IntSummaryStatistics.$accept((IntSummaryStatistics) arg0, ((Integer) arg1).value)
         [ERROR] at IntStream.java(648): IntSummaryStatistics.$accept((IntSummaryStatistics) arg0, ((Integer) arg1).value)
         [ERROR] at IntStream.java(648): {
  IntSummaryStatistics.$accept((IntSummaryStatistics) arg0, ((Integer) arg1).value);
}
         [ERROR] at IntStream.java(648): {
  IntSummaryStatistics.$accept((IntSummaryStatistics) arg0, ((Integer) arg1).value);
}
         [ERROR] at IntStream.java(648): java.util.stream.java_util_stream_IntStream$$__$$java_util_function_ObjIntConsumer$$__$$static$$java_util_IntSummaryStatistics$$accept__IV$Type.accept(Ljava/lang/Object;I)V
         [ERROR] at IntStream.java(648): java.util.stream.java_util_stream_IntStream$$__$$java_util_function_ObjIntConsumer$$__$$static$$java_util_IntSummaryStatistics$$accept__IV$Type (final extends Object implements ObjIntConsumer)
         [ERROR] at Unknown(0): <JProgram>
```

I'm holding off on sources for this, knowing your preference for not digging into incomplete supersource just yet, but was hoping that this assertion might shed a little more light on the bug.

**Comment by rluble** [comment]
Code review will be here: https://gwt-review.googlesource.com/#/c/14940/
