### ISSUE TITLE
Jetty Exception Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9343]
Started to receive this error message when starting gwt server about a week ago, I had to revert to **snapshot 2.8.0-20160415.055509-222** for it to start working correctly again:

```
...
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   Module setup completed in 16215 ms
2016-05-15 09:13:10.430:INFO:oejs.Server:main: jetty-9.2.14.v20151106
2016-05-15 09:13:10.452:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@850567e{/,null,AVAILABLE}

The code server is ready at http://127.0.0.1:9876/
2016-05-15 09:13:10.517:INFO:oejs.ServerConnector:main: Started ServerConnector@6436d2d8{HTTP/1.1}{127.0.0.1:9876}
2016-05-15 09:13:10.517:INFO:oejs.Server:main: Started @17927ms
Code server started in 16.53 s ms
2016-05-15 09:13:10.930:INFO:oejs.Server:main: jetty-9.2.14.v20151106
Starting Jetty on port 8888
   [WARN] ServletContainerInitializers: detected. Class hierarchy: empty
2016-05-15 09:13:18.133:WARN:oejuc.AbstractLifeCycle:main: FAILED c.g.g.d.s.j.WebAppContextWithReload@7049504b{/,file:/C:/Users/Ben/.IntelliJIdea15/system/gwt/gwt-material-table-sample.c2419020/gwt-material-table-sample.83d4eacb/run/www/,STARTING}{C:\Users\Ben\.IntelliJIdea15\system\gwt\gwt-material-table-sample.c2419020\gwt-material-table-sample.83d4eacb\run\www}: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
	at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
	at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
	at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:552)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:761)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:630)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-15 09:13:18.139:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.handler.RequestLogHandler@da511fb: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
	at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
	at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
	at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:552)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:761)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:630)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
2016-05-15 09:13:18.141:INFO:oejs.ServerConnector:main: Started ServerConnector@c8be200{HTTP/1.1}{127.0.0.1:8888}
2016-05-15 09:13:18.142:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.Server@65593f23: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
	at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
	at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
	at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:552)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:761)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:630)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:426)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
	at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
	at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
	at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:552)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:761)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:630)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
```

**Comment by BenDol** [comment]
My base dependencies are as follows:
```
Maven: com.github.gwtmaterialdesign:gwt-material:1.5.1-SNAPSHOT
Maven: com.google.gwt:gwt-dev:2.8.0-SNAPSHOT
Maven: com.google.gwt:gwt-elemental:2.8.0-SNAPSHOT
Maven: com.google.gwt:gwt-servlet:2.8.0-SNAPSHOT
Maven: com.google.gwt:gwt-user:2.8.0-SNAPSHOT
Maven: com.google.jsinterop:jsinterop-annotations:1.0.0-SNAPSHOT
Maven: com.google.jsinterop:jsinterop-annotations:sources:1.0.0-SNAPSHOT
Maven: com.workingflows.js:jquery:1.0
Maven: com.workingflows.js:jscore:1.0
Maven: javax.validation:validation-api:1.0.0.GA
Maven: javax.validation:validation-api:sources:1.0.0.GA
Maven: junit:junit:4.11
Maven: org.hamcrest:hamcrest-core:1.3
Maven: org.jboss.gwt.elemento:elemento-core:0.1.4
Maven: org.ow2.asm:asm:5.0.3
Maven: org.ow2.asm:asm-commons:5.0.3
Maven: org.ow2.asm:asm-tree:5.0.3
Maven: org.ow2.asm:asm-util:5.0.3
```

**Comment by tbroyer** [comment]
I see you're launching DevMode from IntelliJ, can you copy/paste the actual runtime classpath from the console window?
Also, just in case, do you have any other dependency in your `WEB-INF/lib`?

**Comment by BenDol** [comment]
Here is the output libs in `WEB-INF/lib`
```
asm-5.0.3.jar
asm-commons-5.0.3.jar
asm-tree-5.0.3.jar
asm-util-5.0.3.jar
elemento-core-0.1.4.jar
gwt-dev-2.8.0-20160415.055500-222.jar
gwt-elemental-2.8.0-20160513.060548-247.jar
gwt-material-1.5.1-SNAPSHOT.jar
gwt-servlet-2.8.0-20160513.060537-247.jar
gwt-user-2.8.0-20160415.055509-222.jar
jquery-1.0.jar
jscore-1.0.jar
jsinterop-annotations-1.0.0-20160513.060612-135.jar
jsinterop-annotations-1.0.0-20160513.060612-135-sources.jar
validation-api-1.0.0.GA.jar
validation-api-1.0.0.GA-sources.jar
```

This also happens when I simply run mvn gwt:run. But here is the actual runtime classpath from the console:
```
"C:\Program Files\Java\jdk1.8.0_60\bin\java" -Xmx512m -Didea.launcher.port=7536 "-Didea.launcher.bin.path=E:\Jetbrains\IntelliJ IDEA 15.0.6\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\Ben\.m2\repository\com\google\gwt\gwt-codeserver\2.8.0-20160415.055509-222\gwt-codeserver-2.8.0-20160415.055509-222.jar;C:\Users\Ben\.m2\repository\com\google\gwt\gwt-dev\2.8.0-20160415.055509-222\gwt-dev-2.8.0-20160415.055509-222.jar;E:\Projects\Java\Workspace\gwt-material-table-sample\src\main\java;E:\Projects\Java\Workspace\gwt-material-table-sample\src\main\resources;C:\Users\Ben\.m2\repository\com\workingflows\js\jquery\1.0\jquery-1.0-sources.jar;C:\Users\Ben\.m2\repository\com\workingflows\js\jscore\1.0\jscore-1.0-sources.jar;C:\Users\Ben\.m2\repository\com\github\gwtmaterialdesign\gwt-material-table\1.0-SNAPSHOT\gwt-material-table-1.0-SNAPSHOT-sources.jar;C:\Users\Ben\.m2\repository\com\github\gwtmaterialdesign\gwt-material\1.5.1-SNAPSHOT\gwt-material-1.5.1-SNAPSHOT-sources.jar;C:\Users\Ben\.m2\repository\com\google\jsinterop\jsinterop-annotations\1.0.0-SNAPSHOT\jsinterop-annotations-1.0.0-20160513.060612-135-sources.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_60\jre\lib\ext\zipfs.jar;E:\Projects\Java\Workspace\gwt-material-table-sample\target\gwt-material-table-sample-1.0-SNAPSHOT\WEB-INF\classes;C:\Users\Ben\.m2\repository\com\workingflows\js\jquery\1.0\jquery-1.0.jar;C:\Users\Ben\.m2\repository\com\workingflows\js\jscore\1.0\jscore-1.0.jar;C:\Users\Ben\.m2\repository\com\github\gwtmaterialdesign\gwt-material-table\1.0-SNAPSHOT\gwt-material-table-1.0-SNAPSHOT.jar;C:\Users\Ben\.m2\repository\com\github\gwtmaterialdesign\gwt-material\1.5.1-SNAPSHOT\gwt-material-1.5.1-SNAPSHOT.jar;C:\Users\Ben\.m2\repository\org\jboss\gwt\elemento\elemento-core\0.1.4\elemento-core-0.1.4.jar;C:\Users\Ben\.m2\repository\com\google\gwt\gwt-elemental\2.8.0-SNAPSHOT\gwt-elemental-2.8.0-20160513.060548-247.jar;C:\Users\Ben\.m2\repository\com\google\gwt\gwt-servlet\2.8.0-SNAPSHOT\gwt-servlet-2.8.0-20160513.060537-247.jar;C:\Users\Ben\.m2\repository\com\google\gwt\gwt-user\2.8.0-SNAPSHOT\gwt-user-2.8.0-20160415.055509-222.jar;C:\Users\Ben\.m2\repository\com\google\jsinterop\jsinterop-annotations\1.0.0-SNAPSHOT\jsinterop-annotations-1.0.0-20160513.060612-135.jar;C:\Users\Ben\.m2\repository\javax\validation\validation-api\1.0.0.GA\validation-api-1.0.0.GA.jar;C:\Users\Ben\.m2\repository\javax\validation\validation-api\1.0.0.GA\validation-api-1.0.0.GA-sources.jar;C:\Users\Ben\.m2\repository\com\google\gwt\gwt-dev\2.8.0-SNAPSHOT\gwt-dev-2.8.0-20160415.055500-222.jar;C:\Users\Ben\.m2\repository\org\ow2\asm\asm\5.0.3\asm-5.0.3.jar;C:\Users\Ben\.m2\repository\org\ow2\asm\asm-util\5.0.3\asm-util-5.0.3.jar;C:\Users\Ben\.m2\repository\org\ow2\asm\asm-tree\5.0.3\asm-tree-5.0.3.jar;C:\Users\Ben\.m2\repository\org\ow2\asm\asm-commons\5.0.3\asm-commons-5.0.3.jar;C:\Users\Ben\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\Ben\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Ben\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;E:\Jetbrains\IntelliJ IDEA 15.0.6\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.google.gwt.dev.DevMode -superDevMode -war C:\Users\Ben\.IntelliJIdea15\system\gwt\gwt-material-table-sample.c2419020\gwt-material-table-sample.83d4eacb\run\www -remoteUI 7901:IntelliJIdea -startupUrl index.html gwt.material.design.sample.GwtMaterialTableSample
Running CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.8, -bindAddress, 127.0.0.1, -launcherDir, C:\Users\Ben\.IntelliJIdea15\system\gwt\gwt-material-table-sample.c2419020\gwt-material-table-sample.83d4eacb\run\www, -logLevel, INFO, -style, OBFUSCATED, gwt.material.design.sample.GwtMaterialTableSample]
Super Dev Mode starting up
```

**Comment by BenDol** [comment]
Just realized that I pasted in the working version output, updated the post above.

**Comment by tbroyer** [comment]
I must say I don't understand.
I found https://stackoverflow.com/q/32643530/116472 and https://dev.eclipse.org/mhonarc/lists/jetty-users/msg05760.html but that doesn't seem to match your setup.

Can you debug the process, setting a breakpoint in `java.util.ServiceLoader` (or exception-breakpoint on `java.util.ServiceConfigurationError`) trying to understand what could be happening? (different classloaders, etc.)
And/or maybe if you can share the code or make a repro-case.

Note that, as a workaround, if you don't need JSPs, you can exclude `org.eclipse.jetty:apache-jsp` from the `gwt-dev` dependency (don't forget the `org.codehaus.mojo:gwt-maven-plugin` too, which also has a dependency on `gwt-dev`; you'd have to override/redefine it to add the exclusion); that should solve your problem.

**Comment by BenDol** [comment]
https://github.com/BenDol/jetty-issue

This is strange, it seems my dependency list didn't update property.
Here is a diagram of the dependencies:
![dependency-tree](https://cloud.githubusercontent.com/assets/1935706/15271201/95fbfb48-1a91-11e6-88a5-96b7e08abd5a.png)

**Comment by tbroyer** [comment]
There are several problems with this project:
 * `org.codehaus.mojo:gwt-maven-plugin:2.8.0-SNAPSHOT` depends on GWT 2.8.0-beta1, so you'd need to override the dependencies to use 2.8.0-SNAPSHOT
 * you have a dependency on `gwt-dev` with scope `compile` (same for `gwt-user` btw), so `gwt-dev` ends up into the `WEB-INF/lib`; I suppose this is what ultimately causes the issue, with classes coming from different classloaders (`ServiceLoader` always uses the system classloader)

After I fixed those (also adding the OSSRH snapshot repo for GWT Material Design), I was able to run `mvn gwt:run` without that error.

(also, `com.workingflows.js:jquery:1.0` isn't available in any public repo that I know of, so I had to comment it out, along with the `<inherits/>` in the GWT module)

**Comment by BenDol** [comment]
Thanks for helping out with that. Yeah I missed that when I created the project, I was confused since I wasn't having the issue in older versions of the 2.8.0-SNAPSHOT.

**Comment by BenDol** [comment]
@tbroyer I know its somewhat unrelated, but overriding the `org.codehaus.mojo:gwt-maven-plugin:2.8.0-SNAPSHOT` gwt dependency done like so:
```xml
<!-- GWT -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwt-maven-plugin.version}</version>

        <configuration>
          ...
        </configuration>

       <!-- Override -->
        <dependencies>
          <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-servlet</artifactId>
            <version>${gwt.version}</version>
          </dependency>
          <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${gwt.version}</version>
          </dependency>
          <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <version>${gwt.version}</version>
          </dependency>
        </dependencies>

        <!--Replaced the existing executions block-->
        <executions>
          ...
        </executions>
      </plugin>
```

The reason I ask is that when running SuperDevMode my project works fine, but as soon as a run a `mvn clean install` the compilation is broken full on `null.$_nullMethod` calls all over the place. I found the issue related here https://github.com/gwtproject/gwt/issues/9011 but I'm assuming its because its compiling with the wrong version of GWT. So I tested it as shown above and I have the same issue.

Any ideas? Thanks!

**Comment by BenDol** [comment]
Well it is compiling with 2.8.0-SNAPSHOT, appears to be a bug, posted here #9345

**Comment by branflake2267** [comment]
The error `Jetty Exception Provider org.eclipse.jetty.apache.jsp.JuliLog is not a subtype` showed up on one of my test projects when I tried to start SDM. Turns out I was lazy and didn't scope my dependencies properly, at least that's what it looks like I did. Seem to work after I changed my gwt-dev, gwt-user to scope=provided and wiped the target folder. 
```
<!-- GWT -->
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>gwt-user</artifactId>
  <scope>provided</scope>
</dependency>
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>gwt-elemental</artifactId>
  <scope>provided</scope>
</dependency>
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>gwt-dev</artifactId>
  <scope>provided</scope>
</dependency>
<dependency>
  <groupId>com.google.gwt</groupId>
  <artifactId>gwt-codeserver</artifactId>
  <scope>provided</scope>
</dependency>
```
