### ISSUE TITLE
NullPointer when compiling with GWT 2.8 beta1 or snapshot

### ISSUE THREAD

**Issue by rsallar** [gwtproject/gwt#9351]
The output log is:

```
Loading modules
   cat.contesencatala.contesencatala
      Loading inherited module 'cat.contesencatala.contesencatala'
         Loading inherited module 'gwt.material.design.GwtMaterialWithJQuery'
            Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
               [WARN] Line 40: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that has not been previously defined
Super Dev Mode starting up
   Loading inherited module 'cat.contesencatala.contesencatala'
      Loading inherited module 'gwt.material.design.GwtMaterialWithJQuery'
         Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
            [WARN] Line 40: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that has not been previously defined
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
    at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3099)
    at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:352)
    at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:670)
    at org.eclipse.jdt.internal.compiler.ast.Assignment.traverse(Assignment.java:260)
    at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
    at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
    at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3058)
    at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:141)
    at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
    at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
    at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:985)
    at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:339)
    at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
    at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
    at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
    at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:200)
    at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
    at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
    at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
    at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
    at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
    at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.gwt.dev.shell.SuperDevListener$1.run(SuperDevListener.java:84)
Caused by: java.lang.NullPointerException
    at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
    at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pushNewExpression(GwtAstBuilder.java:2642)
    at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:350)
    ... 26 more

```

You can check the code here:

https://github.com/rsallar/contesencatala/tree/gwt28error

**Comment by ShaunEdiger** [comment]
Using snapshot build #536, I'm hitting an NPE on overloads of ```java.lang.String```'s constructor, including:

- (char value[])
- (char value[], int offset, int count)

```
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3099)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:352)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:670)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:373)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3058)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:141)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:985)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:339)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[INFO] 	at com.google.gwt.dev.Compiler.run(Compiler.java:158)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:127)
[INFO] Caused by: java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pushNewExpression(GwtAstBuilder.java:2642)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:350)
[INFO] 	... 23 more
[INFO]    [ERROR] at TimeZone.java(126): new String(data)
```

**Comment by tbroyer** [comment]
@ShaunEdiger The line numbers in your message don't line up with build 536, which was at 94d05a9c26460f87045bf1f2165253d95ae0b687, but are the same as @rsallar's original report. Is this copypasta or do you have beta1 by mistake in your classpath? (beware that Mojo's Maven Plugin for GWT 2.8.0-SNAPSHOT depends on GWT 2.8.0-beta1; yes, quite counter-intuitive) Could you try again with the latest snapshot?

**Comment by ShaunEdiger** [comment]
Just as you suspected, @tbroyer, 2.8.0-beta1 was being included by mistake.  Once that was resolved, the latest snapshot compiled my project successfully.  Thanks a ton and cheers!

**Comment by tbroyer** [comment]
Thanks for the quick feedback. Closing.

@rsallar: please reopen if you have this issue in the latest snapshot.
