### ISSUE TITLE
DevMode "restart server" is broken in 2.8.0-rc1

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9391]
Clicking "restart server" fails with:

```
java.util.concurrent.RejectedExecutionException: org.eclipse.jetty.annotations.AnnotationConfiguration$1@2a5ec0a4
	at org.eclipse.jetty.util.thread.QueuedThreadPool.execute(QueuedThreadPool.java:362)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:541)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:447)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
```

and the server then returns 503 Service Unavailable.

See https://groups.google.com/d/topic/google-web-toolkit/hEEq9PImFf4/discussion

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/15500
