### ISSUE TITLE
Unable to use css2gss converter

### ISSUE THREAD

**Issue by kmthinkingrock** [gwtproject/gwt#9397]
From the documentation here: (http://www.gwtproject.org/articles/gss_migration.html) This error occurs regardless of whether or not I provide an argument

D:\current2\webdev\gwt-2.8.0-rc2>java -cp gwt-user.jar com.google.gwt.resources.converter.Css2Gss
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gwt/core/ext/TreeLogger
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.google.gwt.core.ext.TreeLogger

        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by gkdn** [comment]
@jDramaix let's take a look if there is a quick fix here before 2.8

**Comment by tbroyer** [comment]
This is only a matter of adding gwt-dev to the classpath, right?

**Comment by jDramaix** [comment]
as @tbroyer mentionned, adding gwt-dev.jar in your classpath should solve the issue.

I'm creating a issue in order to fix the documentation

**Comment by kmthinkingrock** [comment]
Thanks, so this is a documentation issue. Good to know. Thanks for the effort.
