### ISSUE TITLE
2.8 RC2: All GWTTestCase after the first fails

### ISSUE THREAD

**Issue by kstjern** [gwtproject/gwt#9402]
We are testing going from GWT 2.7.0 to GWT 2.8, as it fixes some problems we have. 
However, for some reason, all our GWTTestCase tests after the first just fails with this error:

> 15:19:27.495 [DEBUG] [TestEventLogger] com.code.transcoder.UserTest > testUser FAILED
> 15:19:27.499 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: com.code.transcoder.JUnit:com.code.transcoder.UserTest.testUser: could not instantiate the requested class
> 15:19:27.501 [DEBUG] [TestEventLogger]         at java.lang.Throwable.Throwable(Throwable.java:74)
> 15:19:27.504 [DEBUG] [TestEventLogger]         at java.lang.RuntimeException.RuntimeException(Exception.java:33)
> 15:19:27.506 [DEBUG] [TestEventLogger]         at com.google.gwt.junit.client.impl.GWTRunner.$runTest(GWTRunner.java:294)
> 15:19:27.509 [DEBUG] [TestEventLogger]         at com.google.gwt.junit.client.impl.GWTRunner.$doRunTest(GWTRunner.java:235)
> 15:19:27.512 [DEBUG] [TestEventLogger]         at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.$onSuccess(GWTRunner.java:106)
> 15:19:27.515 [DEBUG] [TestEventLogger]         at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:100)
> 15:19:27.518 [DEBUG] [TestEventLogger]         at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.$onResponseReceived(RequestCallbackAdapter.java:232)
> 15:19:27.521 [DEBUG] [TestEventLogger]         at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
> 15:19:27.524 [DEBUG] [TestEventLogger]         at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
> 15:19:27.528 [DEBUG] [TestEventLogger]         at Unknown.anonymous(XMLHttpRequest.java:329)
> 15:19:27.531 [DEBUG] [TestEventLogger]         at com.google.gwt.core.client.impl.Impl.apply(Impl.java:239)
> 15:19:27.533 [DEBUG] [TestEventLogger]         at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:298)
> 15:19:27.536 [DEBUG] [TestEventLogger]         at Unknown.anonymous(Impl.java:77)
> 15:19:27.540 [DEBUG] [TestEventLogger]
> 15:19:27.543 [DEBUG] [TestEventLogger]         Caused by:
> 15:19:27.546 [DEBUG] [TestEventLogger]         com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot call method "new" of undefined
> 15:19:27.548 [DEBUG] [TestEventLogger]             at com.google.gwt.junit.client.impl.GWTTestAccessor.$invoke(GWTTestAccessor.java:35)
> 15:19:27.551 [DEBUG] [TestEventLogger]             at com.google.gwt.junit.client.impl.GWTRunner.$runTest(GWTTestAccessor.java:31)
> 15:19:27.554 [DEBUG] [TestEventLogger]             ... 10 more

We use gradle to run compile and run our tests:

```
test {
    testLogging.showStandardStreams = true
    systemProperties = ['gwt.args': '-logLevel DEBUG']
    // Gwt tests require src/test dirs on classpath.
    classpath += files(sourceSets.main.java.srcDirs,
                       sourceSets.test.java.srcDirs)
}
```

The first GWTTestCase which runs, finishes without a problem. Same with our normal JUnit test cases. The second GWTTestCase and after all just instantly fail.

We have tried 2.8-beta1, 2.8-rc1 and 2.8-rc2.
The tests all run in beta1(But that still has another problem, which seems to be fixed in rc1+)

Hoping someone have a fix for this?

**Comment by nordligulv** [comment]
Could you please provide sample project to reproduce the problem?

**Comment by kstjern** [comment]
Hey,
I have pushed a minimal project which shows this error here: https://github.com/kstjern/gwt-2.8-testfail
Just run 'gradle test --info' 
For me, that fails on the second test with the error described above.

**Comment by wbabachan** [comment]
I can confirm the bug. If you have e.g.  two testcases then after successfully executing the first test, all other testcases will fail. Simply create two gwttestcases and execute them. 

java.lang.RuntimeException: com.....di.JUnit:com.....WidgetComponentTest.testEventBus: could not instantiate the requested class

Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot call method "new" of undefined

**Comment by tbroyer** [comment]
The workaround is to add the tests to a `GWTTestSuite` (which is a good idea anyway, to speed up test execution), or run them in `-devMode` (if possible).

Actually, the problem might not have been introduced with 2.8, but merely a side-effect of the default now being to run tests in prod mode: there's code in `JUnitShell` that skips compiling a module if it's the same as the one for the previous test, so if `Test2` ran, `Test1` won't lead to a compilation, but the `Test1` class wasn't included in the first compilation. At least this is what happens in the Gradle-based repro case above. This isn't a problem in DevMode as Test1 would be found in the classpath.

This however is due to how Gradle runs tests though, because running them from IntelliJ IDEA for example does not fail. In Gradle, we see `GWTTestCase#setName` called for `test2`, then `JUnitShell#runTestImpl` being called (compiling only `Test2` in the module), then `GWTtestCase#setname` called for `test1` (adding `Test1` to the module, but it's too late) and `JUnitShell#runTestImpl` called again (with `sameTest` being `true`, skipping compilation).
In IntelliJ IDEA however, `GWTTestCase#setName` is called twice first, then `JUnitShell#runTestImpl`, so when the synthetic module is compiled, it contains both test classes.

So actually maybe there's no _bug_, but an _incompatibility_ in how Gradle runs tests that only appears now that prod mode is the default?

At least it does not look like a regression from 2.7 as changing GWT deps to 2.7 (and Guava to 19) and running `./gradlew app:testWeb` reproduces the issue (not the same stacktrace, but probably the same cause; at least there's no trace of `Test1` class in the generated `.cache.js` –I added `-style PRETTY` too). And just to confirm, `./gradle test` (which runs tests in DevMode, the default in 2.7) works.

**Comment by gkdn** [comment]
Is there anything to do here before 2.8? If not lets remove this from the milestone.

**Comment by kstjern** [comment]
Well, a default has been changed, which breaks tests in gradle. Maybe put up a notice in the release notes or something? Or better yet, have it detect this case and give an informative error ;)

Anyway, we ended up doing something like this:
```
@RunWith(AllTests.class)
public class CodeTestSuite extends GWTTestSuite {
    
    public static Test suite() {
        TestSuite suite = new TestSuite("Unit Tests");
        
        Reflections reflections = new Reflections("com.code.transcoder");
        
        //Add GWT tests
        Set<Class<? extends GWTTestCase>> gwtClasses = reflections.getSubTypesOf(GWTTestCase.class);
        for(Class<? extends GWTTestCase> clazz : gwtClasses) {
            suite.addTestSuite(clazz);
        }
        
        //Add normal JUnit tests
        Set<Class<? extends TestCase>> classes = reflections.getSubTypesOf(TestCase.class);
        for(Class<? extends TestCase> clazz : classes) {
            //Ignore Selenium tests
            if(!clazz.getPackage().getName().startsWith("com.code.transcoder.tests"))
                suite.addTestSuite(clazz);
        }
        
        
        return suite;
    }
}
```

**Comment by tbroyer** [comment]
There are two issues here:

 * there's a (long-standing) bug when running `GWTTestCase`s outside a `GWTTestSuite`, depending on the way tests are actually run but provided they share the same class loader.
 * the release notes and documentation should emphasize that you should be using `GWTTestSuite` to group your tests, and possibly that failing to do so might result in test failures depending on how the tests are run.

BTW, I found another issue: the WebAppCreator generated Ant build script expects devmode to be the default, so it doesn't actually work as advertised.

**Comment by gkdn** [comment]
Dropping from 2.8 since doesn't seem like will be addressed soon.
