### ISSUE TITLE
Unexpected java.lang.AssertionError

### ISSUE THREAD

**Issue by samgabriel** [gwtproject/gwt#9413]
Hi There, 
We are preparing a GWT 2.6 application to be upgraded to GWT 2.8 for some reason there is one test case that fails both on Eclipse and on Maven with the same error.

```
java.lang.AssertionError
    at com.google.gwt.dev.Permutation.assertSameAnswers(Permutation.java:111)
    at com.google.gwt.dev.Permutation.mergeFrom(Permutation.java:86)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:285)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
    at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
    at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
    at com.google.gwt.junit.JUnitShell.compileForWebMode(JUnitShell.java:1090)
    at com.google.gwt.junit.JUnitShell.maybeCompileForWebMode(JUnitShell.java:1148)
    at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl2(CompileStrategy.java:183)
    at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl(CompileStrategy.java:113)
    at com.google.gwt.junit.SimpleCompileStrategy.maybeCompileModule(SimpleCompileStrategy.java:36)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1313)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1281)
    at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:670)
    at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by rluble** [comment]
Please reopen with a complete small repro case.

**Comment by samgabriel** [comment]
Hi @dankurka  as per your request. I am attaching a test repository that shows the error. If i run this from Eclipse i always get the exception above. If I run it using maven I don't. However when we run the tests with assertions enabled using maven in our project we get the same error.
Here is the link to the repository 
[https://github.com/Brainfuse/test-assertSame](https://github.com/Brainfuse/test-assertSame)

**Comment by tbroyer** [comment]
OK, so, the problem happens when merging/collapsing the various permutations introduced by the `ie.version` property.
`Permutation.mergeFrom` is called twice.
The first time, `this.propertyAndBindingInfos` has length 1, containing `propertyValueByPropertyName={…, ie.version=edge, …, user.agent=gecko1_8, … }`, and `other.propertyAndBindingInfos` has length 1 too, containing `propertyValueByPropertyName={…, ie.version=edge_mobile, …, user.agent=gecko1_8, … }`. So the `assert` passes and the `other` is merged into `this`.
The second time, `this.propertyAndBindingInfos` contains the two previous values, and `other.propertyAndBindingInfos` has length 1, containing `other.propertyAndBindingInfos` has length 1 too, containing `propertyValueByPropertyName={…, ie.version=other, …, user.agent=gecko1_8, … }`. There, the `assert` fails.

I haven't actually checked but, according to the gwt.xml file, the `reboundTypeByGwtCreateType` from the `PropertyAndBindingInfo` should all be the same.

@rluble I don't have enough knowledge of the compiler's internals to debug further, but it looks like this `assert` is just plain wrong.

----
Note that I couldn't reproduce with Maven at first because you have 2 gwt.xml files with the same name, one defining the `ie.version` property (in `src/main/java`) and the other not (in `src/main/resources`), and Maven puts `target/classes` first in the classpath so the module from `src/main/resources` (copied over) was actually used. Removing that file, leaving only the one in `src/main/java`, triggered the issue.

**Comment by samgabriel** [comment]
@tbroyer thank you for identifying the src main resources duplication. I fixed it in the sample repository. Hopefully this issue will gain some traction and be fixed soon. Otherwise anything we can do as a workaround?
