### ISSUE TITLE
compile bug in 2.8.0-rc2

### ISSUE THREAD

**Issue by roelandmaes** [gwtproject/gwt#9415]
I can compile my project without errors with GWT 2.7.0, but with GWT 2.8.0-RC2 I get this error:

  
 [ERROR] Errors in 'jar:file:/C:/Users/Roeland/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-rc2/ad99b09a626c20cce2bdacf3726a51b2cd16b99e/gwt-user-2.8.0-rc2.jar!/com/google/gwt/emul/java/lang/Float.java'
      [ERROR] Line 134: The method isFinite(float) is undefined for the type Double
   Tracing compile failure path for type 'java.lang.Float'
      [ERROR] Errors in 'jar:file:/C:/Users/Roeland/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0-rc2/ad99b09a626c20cce2bdacf3726a51b2cd16b99e/gwt-user-2.8.0-rc2.jar!/com/google/gwt/emul/java/lang/Float.java'
         [ERROR] Line 134: The method isFinite(float) is undefined for the type Double
   [ERROR] Hint: Check that the type name 'java.lang.Float' is really what you meant
   [ERROR] Hint: Check that your classpath includes all required source roots
   [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')
   [ERROR] Unexpected internal compiler error
java.lang.NullPointerException
        at com.google.gwt.dev.jjs.impl.AutoboxUtils.<init>(AutoboxUtils.java:48)
        at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:853)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
        at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
        at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
        at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
        at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
        at com.google.gwt.dev.Compiler.main(Compiler.java:125)

**Comment by tbroyer** [comment]
Can you share a repro case? (at a minimum share you `build.gradle`)

**Comment by roelandmaes** [comment]
It’s a big project and a large build script, but I’ll try to identity the problem.

**Comment by rluble** [comment]
FWIW, Double.isFinite was introduced in Java 8, so the error might be due to misconfigured classpath or stale caches.

**Comment by rluble** [comment]
Reopen with a small repro case.

**Comment by roelandmaes** [comment]
It is related to jts4gwt. (http://jts4gwt.sourceforge.net/maven/repository/)
JTS4GWT has an emulated Double class, so I think this might be the problem.
I don't know much about emulated classes in GWT.  Does someone know how this could be fixed?
You can find a small reproducible project here: https://yadi.sk/d/sNMQqLuKv5dC8
(unzip -> gradle build)

**Comment by rluble** [comment]
JTS4GWT needs to be updated to work with 2.8. You should file an issue of JTS4GWT.
