### ISSUE TITLE
[2.8-rc2] Servlet error

### ISSUE THREAD

**Issue by hrstoyanov** [gwtproject/gwt#9420]
I upgraded to GWT 2.8-rc2 and started getting the below error when trying to launch the code server. Now, I do substitute on my compilation class path this:
```
javax.servlet:javax.servlet-api:3.1.0 -> javax:javaee-api:7.0 (*)
```
but this should not be causing errors ... This might be an issue of proper packaging of Java EE bundles, outside GWT, but I wonder if GWT 2.8 can play safe here and not look for localization bundles when it tries to start jetty?

```
16:29:03.396 [QUIET] [system.out]       at com.google.gwt.dev.codeserver.WebServer.start(WebServer.java:131)
16:29:03.396 [QUIET] [system.out]       at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:161)
16:29:03.396 [QUIET] [system.out]       at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:102)
16:29:03.396 [QUIET] [system.out]       at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
16:29:03.396 [QUIET] [system.out] Caused by: java.util.MissingResourceException: Can't find bundle for base name javax.servlet.LocalStrings, locale en_US
16:29:03.396 [QUIET] [system.out]       at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
16:29:03.396 [QUIET] [system.out]       at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
16:29:03.396 [QUIET] [system.out]       at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
16:29:03.396 [QUIET] [system.out]       at javax.servlet.GenericServlet.<clinit>(GenericServlet.java:95)
16:29:03.396 [QUIET] [system.out]       ... 4 more
```

**Comment by jnehlmeier** [comment]
Every servlet looks for this bundle because its a static field in `javax.servlet.GenericServlet`. If the bundle is not packaged into `javaee-api:7.0` there is nothing GWT can do. You would need to depend on `servlet-api:3.1.0` which contains the bundle.
