### ISSUE TITLE
2.8.0-rc2: Internal compiler exception with `new Double("2345");`

### ISSUE THREAD

**Issue by stikdragon** [gwtproject/gwt#9424]
To reproduce: Create a new basic web application using the Eclipse plugin, with the default options.  Replace content of onModuleLoad with: 
```java
	public void onModuleLoad() {
		new Double("2345");
	}
```
and run via SDM.  The following stack trace is produced:

```
         Compiling 1 permutation
            Compiling permutation 0...
            [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:130)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemove(JVisitor.java:168)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:785)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:777)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemoveImmutable(JVisitor.java:172)
	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:147)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1284)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1249)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.impl.TypeReferencesRecorder.execImpl(TypeReferencesRecorder.java:151)
	at com.google.gwt.dev.jjs.impl.TypeReferencesRecorder.exec(TypeReferencesRecorder.java:46)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.maybeRecordReferencesAndControlFlow(JavaToJavaScriptCompiler.java:473)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:352)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.impl.TypeReferencesRecorder.processMethodCall(TypeReferencesRecorder.java:188)
	at com.google.gwt.dev.jjs.impl.TypeReferencesRecorder.endVisit(TypeReferencesRecorder.java:96)
	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:268)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	... 32 more
               [ERROR] at DoubleBug.java(8): <source info not available>
                  com.google.gwt.dev.jjs.ast.JMethodCall
               [ERROR] at DoubleBug.java(8): <source info not available>
                  com.google.gwt.dev.jjs.ast.JExpressionStatement
               [ERROR] at DoubleBug.java(7): <source info not available>
                  com.google.gwt.dev.jjs.ast.JBlock
               [ERROR] at DoubleBug.java(7): <source info not available>
                  com.google.gwt.dev.jjs.ast.JMethodBody
               [ERROR] at DoubleBug.java(7): bugs.client.DoubleBug.onModuleLoad()V
                  com.google.gwt.dev.jjs.ast.JMethod
               [ERROR] at DoubleBug.java(6): bugs.client.DoubleBug (extends Object implements EntryPoint)
                  com.google.gwt.dev.jjs.ast.JClassType
               [ERROR] at Unknown(0): <JProgram>
                  com.google.gwt.dev.jjs.ast.JProgram
            [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
            [ERROR] Not all permutation were compiled , completed (0/1)
```

This only occurs in SDM, a full compile succeeds.  It only occurs with `Double`, other boxed simple types are ok.   It does not happen in `2.8.0-rc1`.  `Double.parseDouble("2345");` does not suffer this.

Interestingly, adding `<inherits name="com.google.web.bindery.requestfactory.RequestFactory" />` to gwt.xml "fixes" the issue (found by chance).  Suspect adding other modules might have the same effect.

**Comment by niloc132** [comment]
To clarify slightly further, the `.gwt.xml` should _only_ contain the entrypoint and an inherits for `com.google.gwt.user.User` to most easily reproduce this (though @stikdragon has this reproducible in a large production app as well).

**Comment by rluble** [comment]
Thanks for the small repro case. I'll have a look.

**Comment by rluble** [comment]
Could you upload a simple repro project to Github and command line instructions to launch it (mvn would be fine).

It does not repro in my environment here.

**Comment by rluble** [comment]
Managed to repro in a clean environment.

**Comment by rluble** [comment]
Code is for review at https://gwt-review.googlesource.com/#/c/16882/
