### ISSUE TITLE
2.8.0-rc2: Internal compiler exception with non translatable code

### ISSUE THREAD

**Issue by stikdragon** [gwtproject/gwt#9425]
Issue occurs in `rc2` only.  To reproduce: create a default skeleton application using the Eclipse plugin, modify the `EntryPoint` subtype as follows, and add a second class in `client`:

```java
public class CompilerError implements EntryPoint {
	public void onModuleLoad() {
		new BadClass();
	}
}
// following client side class references Element, which cannot be translated
import org.w3c.dom.Element;
public class BadClass {
	private void loadValues(Element root) {
	}
}
```

the module xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<module rename-to='compilererror'>
	<inherits name='com.google.gwt.user.User' />
 	<!-- <inherits name="com.google.web.bindery.requestfactory.RequestFactory" /> --> 
	<entry-point class='bugs.client.CompilerError' />
	<source path='client' />
	<source path='shared' />
	<add-linker name="xsiframe" />
</module>
```

Running this via SDM produces the following exception trace:
```
         Compiling 1 permutation
            Compiling permutation 0...
            [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:130)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemove(JVisitor.java:168)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:785)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:777)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:146)
	at com.google.gwt.dev.jjs.ast.JVisitor.acceptWithInsertRemoveImmutable(JVisitor.java:172)
	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:147)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1284)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1249)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
	at com.google.gwt.dev.jjs.impl.ControlFlowRecorder.execImpl(ControlFlowRecorder.java:163)
	at com.google.gwt.dev.jjs.impl.ControlFlowRecorder.exec(ControlFlowRecorder.java:46)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.maybeRecordReferencesAndControlFlow(JavaToJavaScriptCompiler.java:474)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:352)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.JMethod.getJsniSignature(JMethod.java:615)
	at com.google.gwt.dev.jjs.impl.ControlFlowRecorder.computeName(ControlFlowRecorder.java:50)
	at com.google.gwt.dev.jjs.impl.ControlFlowRecorder.processMethodCall(ControlFlowRecorder.java:195)
	at com.google.gwt.dev.jjs.impl.ControlFlowRecorder.visit(ControlFlowRecorder.java:158)
	at com.google.gwt.dev.jjs.ast.JVisitor.visit(JVisitor.java:683)
	at com.google.gwt.dev.jjs.ast.JNewInstance.traverse(JNewInstance.java:73)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
	... 32 more
               [ERROR] at CompilerError.java(8): new BadClass()
                  com.google.gwt.dev.jjs.ast.JNewInstance
               [ERROR] at CompilerError.java(8): new BadClass()
                  com.google.gwt.dev.jjs.ast.JExpressionStatement
               [ERROR] at CompilerError.java(7): {
  new BadClass();
}
                  com.google.gwt.dev.jjs.ast.JBlock
               [ERROR] at CompilerError.java(7): {
  new BadClass();
}
                  com.google.gwt.dev.jjs.ast.JMethodBody
               [ERROR] at CompilerError.java(7): bugs.client.CompilerError.onModuleLoad()V
                  com.google.gwt.dev.jjs.ast.JMethod
               [ERROR] at CompilerError.java(6): bugs.client.CompilerError (extends Object implements EntryPoint)
                  com.google.gwt.dev.jjs.ast.JClassType
               [ERROR] at Unknown(0): <JProgram>
                  com.google.gwt.dev.jjs.ast.JProgram
            [ERROR] Unrecoverable exception, shutting down
```

`rc1` does not exhibit this behaviour, it correctly outputs `[ERROR] Line 6: No source code is available for type org.w3c.dom.Element; did you forget to inherit a required module?`.  

Interestingly, as with https://github.com/gwtproject/gwt/issues/9424, adding an `<inherits>` for `RequestFactory` "fixes" this issue.

**Comment by rluble** [comment]
Does it happen with -strict?

**Comment by rluble** [comment]
For the record I got the same behavior with 2.8RC1. But it depends on which files are being edited. If both files are edited you get the right behavior which is the error is reported.

**Comment by rluble** [comment]
code review at https://gwt-review.googlesource.com/#/c/16883
