### ISSUE TITLE
StringIndexOutOfBoundsException for method reference with long type name

### ISSUE THREAD

**Issue by Legioth** [gwtproject/gwt#9426]
The compiler throws exceptions if trying to compile code containing a method reference where the method name is short relative to the name of the type. Shortening the type name or lengthening the method name causes the offset reported in the exception to shrink.

Tested with 2.8.0-RC2

This is the example code causing the problem.
```
package com.vaadin.client;

import java.util.ArrayList;
import com.google.gwt.core.client.EntryPoint;

public class Test implements EntryPoint {

    public interface ThisNameNeedsToBeLongRelativeToTheMethodName {
        void shortName();
    }

    @Override
    public void onModuleLoad() {
        ArrayList<ThisNameNeedsToBeLongRelativeToTheMethodName> handlers = new ArrayList<>();

        handlers.forEach(ThisNameNeedsToBeLongRelativeToTheMethodName::shortName);
    }
}
```

Causes this error when compiling
```
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:785)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:777)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:169)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
[INFO] 	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:147)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1284)
[INFO] 	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1249)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.execImpl(ImplementClassLiteralsAsFields.java:400)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.exec(ImplementClassLiteralsAsFields.java:347)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1170)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -20
[INFO] 	at java.lang.String.substring(String.java:1919)
[INFO] 	at com.google.gwt.dev.jjs.ast.JDeclaredType.getCompoundName(JDeclaredType.java:288)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields$ClassLiteralFactoryMethod.maybeMangleJSOTypeName(ImplementClassLiteralsAsFields.java:194)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields$ClassLiteralFactoryMethod.createBaseCall(ImplementClassLiteralsAsFields.java:184)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields$ClassLiteralFactoryMethod.access$100(ImplementClassLiteralsAsFields.java:97)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields$ClassLiteralFactoryMethod$2.createCall(ImplementClassLiteralsAsFields.java:147)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.createLiteralCall(ImplementClassLiteralsAsFields.java:452)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.resolveClassLiteralField(ImplementClassLiteralsAsFields.java:481)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.resolveClassLiteral(ImplementClassLiteralsAsFields.java:457)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields.access$200(ImplementClassLiteralsAsFields.java:85)
[INFO] 	at com.google.gwt.dev.jjs.impl.ImplementClassLiteralsAsFields$NormalizeVisitor.endVisit(ImplementClassLiteralsAsFields.java:227)
[INFO] 	at com.google.gwt.dev.jjs.ast.JClassLiteral.traverse(JClassLiteral.java:81)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	... 41 more
[INFO]       [ERROR] at Test.java(32): Test$0methodref$shortName$Type.class
[INFO]          com.google.gwt.dev.jjs.ast.JClassLiteral
[INFO]       [ERROR] at Test.java(32): return Test$0methodref$shortName$Type.class
[INFO]          com.google.gwt.dev.jjs.ast.JReturnStatement
[INFO]       [ERROR] at Test.java(32): {
[INFO]   return Test$0methodref$shortName$Type.class;
[INFO] }
[INFO]          com.google.gwt.dev.jjs.ast.JBlock
[INFO]       [ERROR] at Test.java(32): {
[INFO]   return Test$0methodref$shortName$Type.class;
[INFO] }
[INFO]          com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]       [ERROR] at Test.java(32): com.vaadin.client.Test$0methodref$shortName$Type.getClass()Ljava/lang/Class;
[INFO]          com.google.gwt.dev.jjs.ast.JMethod
[INFO]       [ERROR] at Test.java(32): com.vaadin.client.Test$0methodref$shortName$Type (final extends Object implements Consumer)
[INFO]          com.google.gwt.dev.jjs.ast.JClassType
[INFO]       [ERROR] at Unknown(0): <JProgram>
[INFO]          com.google.gwt.dev.jjs.ast.JProgram
```

**Comment by rluble** [comment]
code review at https://gwt-review.googlesource.com/16920

**Comment by rluble** [comment]
The actual problem is that synthetic classes for method references are created with an inconsistent naming pattern, breaking assumptions made elsewhere in the compiler. In this case the name of the inner class does not include the name of its enclosing class.
