### ISSUE TITLE
I met the question which like issue #9413

### ISSUE THREAD

**Issue by okimai** [gwtproject/gwt#9432]
The error is same as #9413 like below:
`java.lang.AssertionError
    at com.google.gwt.dev.Permutation.assertSameAnswers(Permutation.java:111)
    at com.google.gwt.dev.Permutation.mergeFrom(Permutation.java:86)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:285)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
    at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
    at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
    at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
    at com.google.gwt.junit.JUnitShell.compileForWebMode(JUnitShell.java:1090)
    at com.google.gwt.junit.JUnitShell.maybeCompileForWebMode(JUnitShell.java:1148)
    at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl2(CompileStrategy.java:183)
    at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl(CompileStrategy.java:113)
    at com.google.gwt.junit.SimpleCompileStrategy.maybeCompileModule(SimpleCompileStrategy.java:36)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1313)
    at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1281)
    at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:670)
    at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

`
My friend found the reason that in his Admin.gwt.xml, when the three lines below exists, the test class which extends GWTTestCase will cause the error. But if without the lines, it's ok. Is it a bug?
`
    <extend-property name="locale" values="zh"/>
    <extend-property name="locale" values="en"/>
    <set-property-fallback name="locale" value="zh"/>`

**Comment by dankurka** [comment]
Hard to say without seeing the code that triggers this, please reopen with a repro case!
