### ISSUE TITLE
An internal compiler exception occurred - Error constructing Java AST

### ISSUE THREAD

**Issue by Martin-Wegner** [gwtproject/gwt#9447]
I updated from GWT 2.7.0 to 2.8.0 and GWT Maven plugin from 2.7.0 to 2.8.0-rc3 and got this error:

```
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3944)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1567)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1018)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.FieldDeclaration.traverse(FieldDeclaration.java:339)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1481)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1363)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3887)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3918)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.ast.MessageSend.binding()Lorg/eclipse/jdt/internal/compiler/lookup/MethodBinding;
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.isUncheckedGenericMethodCall(GwtAstBuilder.java:4167)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.access$1400(GwtAstBuilder.java:249)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1560)
[INFO] 	... 25 more
[INFO]    [ERROR] at NativeVerticalScrollbar.java(90): GWT.create(UiBinderBundle.class)
[INFO]       org.eclipse.jdt.internal.compiler.ast.MessageSend
```

Sometimes the last error changes:

```
[INFO]    [ERROR] at EditTextCell.java(160): GWT.create(Template.class)
[INFO]       org.eclipse.jdt.internal.compiler.ast.MessageSend
```

Plugin configuration:

```
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>2.8.0-rc3</version>
  <configuration>
    <deploy>${project.build.directory}/deploy</deploy>
    <extraJvmArgs>-Xmx1024m</extraJvmArgs>
    <failOnError>true</failOnError>
    <localWorkers>4</localWorkers>
    <module>${project.groupId}.xxx.xxx</module>
    <optimizationLevel>9</optimizationLevel>
    <style>OBFUSCATED</style>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>compile</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

Dependencies:

```
<dependencies>
  <dependency>
    <groupId>com.google.dagger</groupId>
    <artifactId>dagger</artifactId>
    <version>2.7</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>com.google.dagger</groupId>
    <artifactId>dagger-compiler</artifactId>
    <version>2.7</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>com.google.dagger</groupId>
    <artifactId>dagger-gwt</artifactId>
    <version>2.7</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>com.google.gwt</groupId>
    <artifactId>gwt-user</artifactId>
    <version>2.8.0</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>com.google.gwt.eventbinder</groupId>
    <artifactId>eventbinder</artifactId>
    <version>1.1.0</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>javax.inject</groupId>
    <artifactId>javax.inject</artifactId>
    <scope>provided</scope>
    <version>1</version>
  </dependency>
  <dependency>
    <groupId>javax.ws.rs</groupId>
    <artifactId>javax.ws.rs-api</artifactId>
    <version>2.0.1</version>
    <scope>provided</scope>
  </dependency>
  <dependency>
    <groupId>org.fusesource.restygwt</groupId>
    <artifactId>restygwt</artifactId>
    <version>2.2.0</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
```

**Comment by jnehlmeier** [comment]
Check your dependency tree. Looks like a version conflict with JDT / ECJ and GWT now uses a wrong (most likely older) version.

**Comment by tbroyer** [comment]
The problem here is that both dagger-compiler and gwt-dev bring Eclipse JDT (see https://github.com/google/dagger/issues/228), and those versions conflict.

Because dagger-compiler is an annotation processor, you can use maven-compiler-plugin 3.5.1 and its `annotationProcessorPaths` to cleanly separate things out: dagger-compiler will be in the processor path during JavaC compilation, and gwt-dev will be in classpath during GWT compilation.

**Comment by Martin-Wegner** [comment]
@tbroyer thanks, moving `dagger-compiler` from `dependencies` to `annotationProcessorPaths` and adding
```
<dependency>
  <groupId>com.google.code.findbugs</groupId>
  <artifactId>jsr305</artifactId>
  <version>3.0.0</version>
</dependency>
```
solved the problem.

**Comment by ibaca** [comment]
Not a good option, but kind of curious; if the gwt-dev dependency appears before the dagger-compiler dependency project compiles correctly.

**Comment by BerkeSoysal** [comment]
Hi, this solution results in GC OutOfmemory Error for me...

```
[ERROR] Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Parser.<init>(Parser.java:925)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Scanner$VanguardParser.<init>(Scanner.java:4548)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Scanner.getVanguardParser(Scanner.java:4674)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Scanner.disambiguatedToken(Scanner.java:4826)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Scanner.getNextToken(Scanner.java:1183)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11676)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Parser.parseExpression(Parser.java:12267)
[ERROR] 	at org.eclipse.jdt.internal.compiler.parser.Parser.parseLambdaExpression(Parser.java:12229)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.copy(LambdaExpression.java:1084)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.cachedResolvedCopy(LambdaExpression.java:950)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.isCompatibleWith(LambdaExpression.java:880)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.PolyTypeBinding.isCompatibleWith(PolyTypeBinding.java:43)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.parameterCompatibilityLevel(Scope.java:4940)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.parameterCompatibilityLevel(Scope.java:4907)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:867)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.computeCompatibleMethod(Scope.java:794)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod0(Scope.java:1750)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.findMethod(Scope.java:1651)
[ERROR] 	at org.eclipse.jdt.internal.compiler.lookup.Scope.getMethod(Scope.java:2934)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.findMethodBinding(MessageSend.java:954)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:775)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.resolve(ReturnStatement.java:349)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:641)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:316)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:551)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1262)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1378)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1161)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1387)
[ERROR] 	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:652)
[ERROR] 	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:892)
[ERROR] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:283)
```
