### ISSUE TITLE
InternalCompilerException on compilation default methods with optimization

### ISSUE THREAD

**Issue by hillfox12** [gwtproject/gwt#9453]
When I set opimization level higher then 0, I get compilation error in gwt 2.8.0:
```
[ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Should not encounter a JThisRef within a static method
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner$CloneCalleeExpressionVisitor.visit(MethodInliner.java:72)
[INFO] 	at com.google.gwt.dev.jjs.ast.JThisRef.traverse(JThisRef.java:48)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.impl.CloneExpressionVisitor.cloneExpression(CloneExpressionVisitor.java:77)
[INFO] 	at com.google.gwt.dev.jjs.impl.CloneExpressionVisitor.cloneExpressions(CloneExpressionVisitor.java:93)
[INFO] 	at com.google.gwt.dev.jjs.impl.CloneExpressionVisitor.visit(CloneExpressionVisitor.java:200)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.impl.CloneExpressionVisitor.cloneExpression(CloneExpressionVisitor.java:77)
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner$InliningVisitor.extractExpressionsFromBody(MethodInliner.java:253)
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner$InliningVisitor.tryInlineMethodCall(MethodInliner.java:146)
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner$InliningVisitor.endVisit(MethodInliner.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:268)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:42)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JSwitchStatement.traverse(JSwitchStatement.java:46)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.impl.FullOptimizerContext.traverse(FullOptimizerContext.java:224)
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner.execImpl(MethodInliner.java:604)
[INFO] 	at com.google.gwt.dev.jjs.impl.MethodInliner.exec(MethodInliner.java:581)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaOneTime(JavaToJavaScriptCompiler.java:1506)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJavaToFixedPoint(JavaToJavaScriptCompiler.java:1437)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.optimizeJava(JavaToJavaScriptCompiler.java:522)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:360)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO] 	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO] 	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO] 	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
[INFO]          [ERROR] at ProcessParams.java(26): this
[INFO]             com.google.gwt.dev.jjs.ast.JThisRef
[INFO]          [ERROR] at ProcessParams.java(26): Params.$appendToString(this, sb)
[INFO]             com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]          [ERROR] at PricingParams.java(17): ProcessParams.$appendToString(sb, ParamsKind.PROCESS)
[INFO]             com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]          [ERROR] at PricingParams.java(17): ProcessParams.$appendToString(sb, ParamsKind.PROCESS)
[INFO]             com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]          [ERROR] at PricingParams.java(12): {
[INFO]   case ParamsKind.PRICING.ordinal: 
[INFO]   StringBuilder.$append(sb, this$static.getPrice());
[INFO]   break;
[INFO]   case ParamsKind.PROCESS.ordinal: 
[INFO]   ProcessParams.$appendToString(sb, ParamsKind.PROCESS);
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JBlock
[INFO]          [ERROR] at PricingParams.java(12): switch (kind.ordinal)  {
[INFO]   case ParamsKind.PRICING.ordinal: 
[INFO]   StringBuilder.$append(sb, this$static.getPrice());
[INFO]   break;
[INFO]   case ParamsKind.PROCESS.ordinal: 
[INFO]   ProcessParams.$appendToString(sb, ParamsKind.PROCESS);
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JSwitchStatement
[INFO]          [ERROR] at PricingParams.java(11): {
[INFO]   switch (kind.ordinal)  {
[INFO]     case ParamsKind.PRICING.ordinal: 
[INFO]     StringBuilder.$append(sb, this$static.getPrice());
[INFO]     break;
[INFO]     case ParamsKind.PROCESS.ordinal: 
[INFO]     ProcessParams.$appendToString(sb, ParamsKind.PROCESS);
[INFO]   }
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JBlock
[INFO]          [ERROR] at PricingParams.java(11): {
[INFO]   switch (kind.ordinal)  {
[INFO]     case ParamsKind.PRICING.ordinal: 
[INFO]     StringBuilder.$append(sb, this$static.getPrice());
[INFO]     break;
[INFO]     case ParamsKind.PROCESS.ordinal: 
[INFO]     ProcessParams.$appendToString(sb, ParamsKind.PROCESS);
[INFO]   }
[INFO] }
[INFO]             com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]          [ERROR] at PricingParams.java(11): com.mycompany.tests.client.PricingParams.$appendToString(Lcom/mycompany/tests/client/PricingParams;Ljava/lang/StringBuilder;Lcom/mycompany/tests/client/ParamsKind;)V
[INFO]             com.google.gwt.dev.jjs.ast.JMethod
[INFO]       [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
```
I compile this code:
```
public interface Params {

    default double get(PricingVariable var) {
        return Double.NaN;
    }

    Collection<PricingVariable> toStringVariables();

    default void appendToString(StringBuilder sb, ParamsKind kind) {
        for (PricingVariable var : toStringVariables()) {
            double value = get(var);
            sb.append(value);
        }
    }
}
```

```
public interface ProcessParams extends Params {

    double getUnderlying();

    @Override
    default double get(PricingVariable var) {
        return getUnderlying();
    }

    @Override
    default Collection<PricingVariable> toStringVariables() {
        return new LinkedHashSet<>();
    }

    @Override
    default void appendToString(StringBuilder sb, ParamsKind kind) {
        sb.append(',');
        Params.super.appendToString(sb, kind);
    }
}`
```

```
public interface PricingParams extends ProcessParams {

    double getPrice();

    @Override
    default void appendToString(StringBuilder sb, ParamsKind kind) {
        switch (kind) {
            case PRICING:
                sb.append(getPrice());
                break;
            case PROCESS:
                ProcessParams.super.appendToString(sb, ParamsKind.PROCESS);
                break;
        }
    }
}
```
```
public class ParamsImpl implements PricingParams {

    @Override
    public double getUnderlying() {
        return 23;
    }

    @Override
    public double getPrice() {
        return 345;
    }
}
```
```
public enum ParamsKind {
    PROCESS, PRICING;
}
```
```
public class PricingVariable {
}
```
```
StringBuilder sb = new StringBuilder();
PricingParams params = new ParamsImpl();
params.appendToString(sb, ParamsKind.PROCESS);
nameField.setText(sb.toString());
```

If I compile this code without optimization, there are no errors, and compiled method appendToString() from interface ProcessParams looks like:
```
function $appendToString_1(this$static, sb, kind){
  sb.append_0(44);
  $appendToString(this, sb, kind);
}
```
Probably the cause of the issue?

Thanks!

**Comment by rluble** [comment]
Could you upload a small self contained project to github that exhibits the problem?

**Comment by hillfox12** [comment]
https://github.com/hillfox12/pricetest

**Comment by rluble** [comment]
code review at https://gwt-review.googlesource.com/#/c/17280/
