### ISSUE TITLE
Jetty 9.3.x removed Request.getUri(), causes junit tests to log stack trace

### ISSUE THREAD

**Issue by jschmied** [gwtproject/gwt#9457]
Using GWT 2.8.0 with spring platform which is importing jetty 9.3.11 causes:

[WARN] //localhost:51335/xxxxJunit.JUnit/resources/lupe.gif
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Request.getUri()Lorg/eclipse/jetty/http/HttpURI;
        at com.google.gwt.dev.shell.jetty.JettyLauncher$JettyRequestLogger.log(JettyLauncher.java:130)
        at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:620)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:453)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)

test are working but this stack trace is logged

**Comment by tbroyer** [comment]
I doubt you're using Spring in client-side code, so you should exclude it from your tests, and make it so that it doesn't interfere with GWT's dependencies.
Put differently, you have a dependency conflict in your project, and this is none of GWT's business (you can blame Jetty for breaking compatibility in minor releases, but that won't solve the problem either).
