### ISSUE TITLE
Improve Lambda error messages

### ISSUE THREAD

**Issue by mseele** [gwtproject/gwt#9495]
**GWT version: 2.8.0** 
**Browser (with version): Chrome 56.0.2924.87 (64-bit)** 
**Operating System: Windows 7** 

---

##### Description

Improve Lambda error messages. Please execute the example i've attached.
What i get running this as GWT, is:

Uncaught Error: java.lang.IllegalStateException: Can't assign multiple values to the same key
    at Fm.P [as s] (dmm-0.js:573:12483)
    at Fm.T [as v] (dmm-0.js:573:13033)

What i get running this in pure Java, is:

Exception in thread "main" java.lang.IllegalStateException: Duplicate key Item [id=1, name=1-Test]
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)

The code works fine, i only want highlight that the error message in Pure Java is way better than i GWT. It's much more harder to get behind the error in GWT.

##### Steps to reproduce

Run the attached Java Class as pure Java application and as GWT application.

[TestEntryPoint.txt](https://github.com/gwtproject/gwt/files/827338/TestEntryPoint.txt)

**Comment by timeu** [comment]
Is this actually related to Lambdas  and not rather a sourcemap issue ? 
I am wondering if the error message is different when you try it without lambda but with anonymous inner class instead ?

**Comment by mseele** [comment]
It's related to gwt's lambda implementation. I do it both times with lambda. One time in gwt, one time in java

**Comment by timeu** [comment]
Ok I think the issue is that [GWT's emulation](https://github.com/gwtproject/gwt/blob/9be59bb36044bff326950aa015de3e8b9797c8ea/user/super/com/google/gwt/emul/java/util/stream/Collectors.java#L321) code for `Collectors` has this signature for `toMap`: 

```JAVA
public static <T, K, U> Collector<T, ?, Map<K, U>> toMap(
      final Function<? super T, ? extends K> keyMapper,
      final Function<? super T, ? extends U> valueMapper) {
    return toMap(
        keyMapper,
        valueMapper,
        (m1, m2) -> {
          throw new IllegalStateException("Can't assign multiple values to the same key");
        });
  }
```

While [Java 8's signature looks](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/stream/Collectors.java#Collectors.toMap%28java.util.function.Function%2Cjava.util.function.Function%29) like this: 

```JAVA
public static <T, K, U> Collector<T, ?, Map<K,U>> toMap(Function<? super T, ? extends K> keyMapper,  Function<? super T, ? extends U> valueMapper) {
    return toMap(keyMapper, valueMapper, throwingMerger(), HashMap::new);
}
```
and the `throwingMerger()` function looks like [this](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/stream/Collectors.java#Collectors.throwingMerger%28%29): 

```JAVA
private static <T> BinaryOperator<T> throwingMerger() {
    return (u,v) -> { throw new IllegalStateException(String.format("Duplicate key %s", u)); };
}
```

**Comment by mseele** [comment]
Yes, this is what i mean. GWT can be better here...

**Comment by timeu** [comment]
I think the title of this issue is wrong, because it has nothing to do with Lambda, but with GWT's eumalation for the `Collectors` class and specifically the `toMap` function. 

Do you mind submitting a patch ? 

http://www.gwtproject.org/makinggwtbetter.html

**Comment by mseele** [comment]
I'm sorry, right now i have no time to submit a patch (because i have no gwt source environment set up), i just wanted to highlight that this part can be done better.
