### ISSUE TITLE
NPE at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208)

### ISSUE THREAD

**Issue by JoergOstertag** [gwtproject/gwt#9535]
**GWT version: 2.8.1
**Operating System: Windows

---

##### Description
As described in https://github.com/vaadin/framework/issues/8244 
trying to Stringify special crafted Objects with null values inside results in a NPE.

`java.lang.NullPointerException
        at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208)
        at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96)
        at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252)
        at com.vaadin.server.communication.ClientRpcWriter.write(ClientRpcWriter.java:106)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:190)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
`

Suggestion:
Add a NP Check into this method:
https://gwt.googlesource.com/gwt/+/2.8.1/elemental/src/elemental/json/impl/JsonUtil.java 

`/**
   * Safely escape an arbitrary string as a JSON string literal.
   */
  public static String quote(String value) {
    StringBuilder toReturn = new StringBuilder("\"");

///////////////
     if ( null == value ) {
 .....
}
///////////////

    for (int i = 0; i < value.length(); i++) {
`

##### Known workarounds

Remove null values from Objects before calling.

##### Links to further discussions

https://github.com/vaadin/framework/issues/8244

**Comment by tbroyer** [comment]
A `JsonString`'s `getString()` must not be `null`. This is the real cause of the exception, **not** that `JsonUtil.quote()` does not expect `null` input. So it looks like the bug is either in your code or in Vaadin, that constructs such an object.
