### ISSUE TITLE
Code coverage for maven

### ISSUE THREAD

**Issue by Shehab-Muhammad** [gwtproject/gwt#9539]
I'm using maven, and I want to find a way to get total coverage for my unit tests as I have `GwtMockitoTestRunner` and `GWTTestCase`  
I tied to use Emma with maven but it gives me an error

```
java.lang.IllegalStateException: CONSTANT_info: invalid tag value [8]
at com.vladium.jcd.cls.constant.CONSTANT_info.new_CONSTANT_info(CONSTANT_info.java:103)
at com.vladium.jcd.parser.ClassDefParser$classParser.constant_pool(ClassDefParser.java:168)
at com.vladium.jcd.parser.ClassDefParser$classParser.class_table(ClassDefParser.java:109)
at com.vladium.jcd.parser.ClassDefParser.parseClass(ClassDefParser.java:56)
at com.vladium.emma.instr.InstrProcessorST.handleFile(InstrProcessorST.java:468)
```

then I tried (Jacoco)[https://github.com/jfuerth/jacoco-gwt-maven-plugin] but it gives me 0% coverage
and this's my configuration at pom.xml file

```
<plugin>
                <groupId>org.jboss.errai</groupId>
                <artifactId>jacoco-gwt-maven-plugin</artifactId>
                <version>0.5.4.201202141554</version>
                <executions>
                    <execution>
                        <id>jacoco-initialize</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <propertyName>jacocoArgs</propertyName>
                        </configuration>
                    </execution>
                    <execution>
                        <id>jacoco-site</id>
                        <phase>site</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.17</version>
                <configuration>
                    <additionalClasspathElements>
                        <additionalClasspathElement>${project.build.sourceDirectory}</additionalClasspathElement>
                        <additionalClasspathElement>${project.build.testSourceDirectory}</additionalClasspathElement>
                    </additionalClasspathElements>
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                    <reuseForks>true</reuseForks>
                    <argLine>${jacocoArgs} -XX:MaxPermSize=512m -Xmx4g -noverify</argLine>
                </configuration>
            </plugin>
```
 
please add a way to get code coverage for maven users.

**Comment by tbroyer** [comment]
JaCoCo, like Emma, is likely to only record coverage when test are run in dev mode, and test are run in prod mode by default in GWT 2.8 (as dev mode is deprecated)

AFAIK, there's a way to generate instrumented JS code, but it's not well-integrated into any toolchain (except probably Google's internal build system).  
You enable it by setting the `gwt.coverage` system property to a file whose content is the list of Java source files to instrument, one per line, or a comma-separated list of those files, and the coverage "report" is a JSON object stored in the browser's local storage under the `gwt_coverage` key.

**Comment by jomarko** [comment]
In our project we measure coverage of tests running with `GwtMockitoTestRunner`. See the configuration below:
```xml
<plugin>
<groupId>org.jacoco<groupId>
<artifactId>jacoco-maven-plugin</artifactId>
          <version>${version.jacoco.plugin}</version>
          <executions>
            <execution>
              <id>default-instrument</id>
              <goals>
                <goal>instrument</goal>
              </goals>
            </execution>
            <execution>
              <id>default-restore-instrumented-classes</id>
              <goals>
                <goal>restore-instrumented-classes</goal>
              </goals>
            </execution>
            <execution>
              <id>default-report</id>
              <phase>prepare-package</phase>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
            <execution>
              <id>default-check</id>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                 <!-- conf here -->
              </configuration>
            </execution>
          </executions>
        </plugin>
```

**Comment by eugen-eugen** [comment]
Thank You, jomarko very much,
it seems to be essential to have **<goal>instrument</goal>** (offline-instrumentalisation) to get jacoco work properly with GWT.

Also found in https://github.com/google/gwtmockito/issues/65
