### ISSUE TITLE
Internal compiler exception when using native JsType varargs in a JsMethod

### ISSUE THREAD

**Issue by TDesjardins** [gwtproject/gwt#9544]
GWT version: 2.8.1

---

##### Description

When using varargs in constructors of native types the following compile error occures:

```
[ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
	at com.google.gwt.dev.jjs.ast.JConstructor.traverse(JConstructor.java:142)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:169)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:336)
	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:147)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1284)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1249)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.impl.ImplementJsVarargs.execImpl(ImplementJsVarargs.java:487)
	at com.google.gwt.dev.jjs.impl.ImplementJsVarargs.exec(ImplementJsVarargs.java:477)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.normalizeSemantics(JavaToJavaScriptCompiler.java:507)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:364)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError
	at com.google.gwt.dev.jjs.ast.JClassLiteral.setField(JClassLiteral.java:73)
	at com.google.gwt.dev.jjs.impl.ImplementJsVarargs$VarargsMethodNormalizer.endVisit(ImplementJsVarargs.java:377)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:85)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	... 23 more
         [ERROR] at And.java(30): {
  this.LogicalNary.LogicalNary("And", conditions);
  this.$init();
}
         [ERROR] at And.java(30): public And(Filter[] conditions);

         [ERROR] at And.java(28): ol.format.filter.And (extends LogicalNary)
         [ERROR] at Unknown(0): <JProgram>
```

##### Steps to reproduce

Using the following type hierarchy causes the compile error:

```
@JsType(isNative = true)
public class Filter {

   public Filter(String tagName) {}

}
```
```
@JsType(isNative = true)
public abstract class LogicalNary extends Filter {

    public LogicalNary(String tagName, Filter... filters) {
        super(tagName);
    }

}
```
```
@JsType(isNative = true)
public class And extends LogicalNary {

	public And(Filter... conditions) {
		super("And", conditions);
	}

}
```
Then instantiate class 'And':

`And andFilter = new And(new Filter("filter1"), new Filter("filter2"));`

**Comment by tbroyer** [comment]
FWIW, there's a similar case in https://github.com/gwtproject/gwt/blob/2.8.1/user/test/com/google/gwt/core/interop/JsTypeVarargsTest.java

**Comment by rluble** [comment]
Clearly a compiler error :) The error seems to be when processing the
native constructor. Native constructors do not produce code but sometimes
you need to write them to satisfy super/subclass constraints as in this
case where the native superclass does not have a no arg constructor.

The compiler should skip that code in native method bodies in
the ImplementJsVarargs.java.

Should be an easy change replacing line 257

if (!x.isJsMethodVarargs())

by

if (x.isJsNative() || !x.isJsMethodVarargs())

 so that bodies are skipped.

Can someone make a patch and a test for this? I'd be happy to review it.

**Comment by TDesjardins** [comment]
@rluble Good catch! Changing line [287](https://github.com/gwtproject/gwt/blob/a90832fec9a56f4cb83ed009c7048e0a8d196fe8/dev/core/src/com/google/gwt/dev/jjs/impl/ImplementJsVarargs.java#L287) and [337](https://github.com/gwtproject/gwt/blob/a90832fec9a56f4cb83ed009c7048e0a8d196fe8/dev/core/src/com/google/gwt/dev/jjs/impl/ImplementJsVarargs.java#L337) solves this issue.

A workaround is to create no arg constructors in base classes and leave the subclass constructors empty. The only issue is that you are then able to subclass a non native type which could call the no arg constructor.

**Comment by rluble** [comment]
Actually the error is broader and related to (JsType) varargs of a native JsType. 

Code review at https://gwt-review.googlesource.com/#/c/gwt/+/19220

**Comment by TDesjardins** [comment]
Thanks! 😄
