### ISSUE TITLE
ClassNotFoundException when running JettyLauncher with Java 9

### ISSUE THREAD

**Issue by TDesjardins** [gwtproject/gwt#9561]
GWT version: 2.8.2
JDK: 1.9

---

##### Description
When running GWTUnitTests with Java9 in ProdMode the following Error occures in log:

```
[ERROR] jreLeakPrevention.gcDaemonFail
java.lang.ClassNotFoundException: sun.misc.GC
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.jreLeakPrevention(JettyLauncher.java:899)
	at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:722)
	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:636)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
	at com.google.gwt.junit.JUnitShell.getUnitTestShell(JUnitShell.java:708)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:682)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
```

See also: https://travis-ci.org/TDesjardins/gwt-ol/jobs/291208146#L1547

The cause is presumably that a class (sun.misc.GC) has been moved in Java 9:

https://bugs.openjdk.java.net/browse/JDK-8153286

which is used in the JettyLauncher:

https://github.com/gwtproject/gwt/blob/a90832fec9a56f4cb83ed009c7048e0a8d196fe8/dev/core/src/com/google/gwt/dev/shell/jetty/JettyLauncher.java#L899

##### Steps to reproduce

https://travis-ci.org/TDesjardins/gwt-ol/jobs/291208146

##### Known workarounds

Use Java 8

**Comment by tbroyer** [comment]
Another "workaround" is to just ignore the message: it's only logged with error level, it's not a breakage.

I agree we should find a way to silence this though.

**Comment by MCMicS** [comment]
@TDesjardins: I fixed this and submit a patch to gerrit.

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19880

**Comment by MCMicS** [comment]
any progress here?

**Comment by MCMicS** [comment]
still happens with 2.9.0-RC1

**Comment by niloc132** [comment]
Once we update the jetty version, we can remove this GC workaround and the message will stop. For now, the error can be safely ignored.

**Comment by MCMicS** [comment]
OK
Found it during Smoke Test. WIll ignore it

**Comment by geoffreywiseman** [comment]
Is there any target version for this update / workaround / message hiding?

**Comment by diskostu** [comment]
Any update on this? It's been 3 and a half year since the patch was submitted.
I know the error can be ignored, but, you know, it's an error in the log. Not very nice.

**Comment by niloc132** [comment]
We upgraded Jetty, but failed to remove this call - it will be removed in the next version.
