### ISSUE TITLE
Illegal reflective access with Java 9 in LinkedHashMap_CustomFieldSerializer

### ISSUE THREAD

**Issue by mseele** [gwtproject/gwt#9584]
**GWT version: 2.8.2** 
**Browser (with version): Happens on server side: gwt-servlet.jar** 
**Operating System: Windows 10** 

---

##### Description

Run the following snippet with tomcat 8.5 under java 9 produces this output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.skife.jdbi.cglib.core.ReflectUtils$1 (file:/C:/dev/workspaces/dmm/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dmmWeb/WEB-INF/lib/jdbi-2.78.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.skife.jdbi.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

##### Steps to reproduce

Run the following snippet with tomcat 8.5 under java 9: 

https://gist.github.com/mseele/8ec870fa240d74a9a80a1754ed4bda9b

**Comment by tbroyer** [comment]
The warning talks about JDBI 2 (and even JDBI 3 is apparently not ready yet for JDK 9: https://github.com/jdbi/jdbi/issues/497), there's nothing about GWT in the message.

**Comment by mseele** [comment]
You're right, i've mixed up messages. Now the message is correct and contains the GWT related WARNING.
It's reproducible with my snippet and has only to do with GWT.

**Comment by niloc132** [comment]
This should fall back gracefully through the slower getAccessOrderNoReflection version, but will still emit that warning. @mseele can you confirm that this still functions if you forbid that access?

**Comment by mseele** [comment]
No, i cannot confirm. When i set

`--illegal-access=deny`

i got an exception and the rpc call results in an error:

```
Jan. 05, 2018 8:41:14 VORM. org.apache.catalina.core.ApplicationContext log
SCHWERWIEGEND: Exception while dispatching incoming RPC call
java.lang.reflect.InaccessibleObjectException: Unable to make field final boolean java.util.LinkedHashMap.accessOrder accessible: module java.base does not "opens java.util" to unnamed module @9aea04e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:337)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at com.google.gwt.user.client.rpc.core.java.util.LinkedHashMap_CustomFieldSerializer.getAccessOrder(LinkedHashMap_CustomFieldSerializer.java:112)
	at com.google.gwt.user.client.rpc.core.java.util.LinkedHashMap_CustomFieldSerializer.serialize(LinkedHashMap_CustomFieldSerializer.java:100)
	at com.google.gwt.user.client.rpc.core.java.util.LinkedHashMap_CustomFieldSerializer.serializeInstance(LinkedHashMap_CustomFieldSerializer.java:153)
	at com.google.gwt.user.client.rpc.core.java.util.LinkedHashMap_CustomFieldSerializer.serializeInstance(LinkedHashMap_CustomFieldSerializer.java:32)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeImpl(ServerSerializationStreamWriter.java:818)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:698)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:167)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:606)
	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:644)
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForSuccess(RPC.java:497)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:589)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at de.guhsoft.edhtreporter.webclient.server.LogFishTagging.doFilter(LogFishTagging.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at de.guhsoft.utils.web.FilterUtils.cachingFilter(FilterUtils.java:48)
	at de.guhsoft.edhtreporter.webclient.server.CachingFilter.doFilter(CachingFilter.java:20)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

This can be easily verified by my snippet:

https://gist.github.com/mseele/8ec870fa240d74a9a80a1754ed4bda9b

**Comment by niloc132** [comment]
Got it - that's going to be fun to fix, since `InaccessibleObjectException` is a brand new exception in Java 9, so we can't just add a "catch" for it. That said, it is just a runtime exception, so we can catch that, and check if the name matches InaccessibleObjectException, and then ignore safely, since that means the fallback will work.

Thanks for reporting and following up with more details, I'll look into this.

**Comment by niloc132** [comment]
This will also affect `EnumMap_CustomFieldSerializer`, but I don't yet see a graceful way to handle that, the state is entirely hidden to us for the case of an empty map.

**Comment by norbertroamsys** [comment]
We are just migrating all our applications from Java 8 to Java 11.
GWT 2.8.2 works as expected, but we still get the warning reported in this issue.
Is there any progress on this? Maybe in GWT 2.8.3?

**Comment by norbertroamsys** [comment]
It is great that the new GWT release 2.9.0 was released and we are already using it without having any problems.
The assumption was - because GWT now fully supports Java 11 at client side - that this warning was also fixes.
But unfortunately it is not: The message still persists!
Are there any future plans to change that?

**Comment by damonhnz** [comment]
There is a new method Field.trySetAccessible which returns a boolean instead of throwing an exception but I don't know what you're supposed to do if the code needs to work on Java 8 as well.

**Comment by damonhnz** [comment]
Here's a workaround until this issue is resolved.  It forces it to use the non-reflective method without triggering the exception first.  Just add this code to your RPC service implementation.

```
    static {
        try {
            Field field = LinkedHashMap_CustomFieldSerializer.class.getDeclaredField("reflectionHasFailed");
            field.setAccessible(true);
            ((AtomicBoolean)field.get(null)).set(true);
        } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
```

**Comment by kaluchi** [comment]
Any news? I am trying to develop gwt app on java 16 and this error bothers me a lot

**Comment by evpaassen** [comment]
As a workaround, you can reopen the `java.lang` and `java.util` packages for reflection again by adding these VM options:

```
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
```

It's not pretty, because these packages have been closed for reflection for a reason, but it seems to be the most reliable workaround. Next to `LinkedHashMap` and `EnumMap` there might be other common types from the `java.lang` and `java.util` packages that are being serialized using reflection, for example `RuntimeException` or any custom subclass of it.

Although the workaround exists, I think it's key to solve these serialization issues in the end, if the GWT project is still alive at least.

**Comment by axeluhl** [comment]
I've played with the EnumMap problem and came up with this:

<pre>
package some_package;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectStreamClass;

/**
 * A serialization-compatible mock for {@link java.util.EnumMap} that uses an equal {@link #serialVersionUID} and a
 * compatible set of fields. When de-serializing an {@link java.util.EnumMap} instance into an instance of this class,
 * e.g., by overriding {@link ObjectInputStream}'s {@link ObjectInputStream#resolveClass} method such that it delivers
 * this class instead of {@link java.util.EnumMap}, the fields are made accessible through getters; in particular,
 * {@link #getKeyType()} reveals the original {@link java.util.EnumMap}'s key type, even if the map is empty.<p>
 * 
 * The {@link EnumMap#getEnumMapKeyType(java.util.EnumMap)} method can be used to determine the key type of any
 * {@link java.util.EnumMap}, even if it's empty.
 */
public class EnumMap<K extends Enum<K>, V> extends java.util.EnumMap<K, V> {
    private final Class<K> keyType;
    private transient K[] keyUniverse;
    private transient Object[] vals;
    private transient int size = 0;
    private static final long serialVersionUID = 458661240069192865L;
    
    private static class MyObjectInputStream extends ObjectInputStream {
        public MyObjectInputStream(InputStream in) throws IOException {
            super(in);
        }

        @Override
        protected Class<?> resolveClass(ObjectStreamClass desc) throws IOException, ClassNotFoundException {
            final Class<?> result;
            if (desc.getName().equals("java.util.EnumMap")) {
                result = com.sap.sse.test.EnumMap.class;
            } else {
                result = super.resolveClass(desc);
            }
            return result;
        }
    }
    
    public static Class<?> getEnumMapKeyType(java.util.EnumMap<?, ?> enumMap) throws IOException, ClassNotFoundException {
        final Class<?> result;
        if (enumMap.isEmpty()) {
            final ByteArrayOutputStream bos = new ByteArrayOutputStream();
            final ObjectOutputStream oos = new ObjectOutputStream(bos);
            oos.writeObject(enumMap);
            oos.close();
            final ObjectInputStream ois = new MyObjectInputStream(new ByteArrayInputStream(bos.toByteArray()));
            final com.sap.sse.test.EnumMap<?, ?> readMap = (com.sap.sse.test.EnumMap<?, ?>) ois.readObject();
            final Class<?> keyType = readMap.getKeyType();
            result = keyType;
        } else {
            result = enumMap.keySet().iterator().next().getDeclaringClass();
        }
        return result;
    }

    EnumMap(Class<K> c) {
        super(c);
        keyType = null;
    }
    
    public K[] getKeyUniverse() {
        return keyUniverse;
    }

    public void setKeyUniverse(K[] keyUniverse) {
        this.keyUniverse = keyUniverse;
    }

    public Object[] getVals() {
        return vals;
    }

    public void setVals(Object[] vals) {
        this.vals = vals;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public Class<K> getKeyType() {
        return keyType;
    }

    /**
     * Reconstitute the <tt>EnumMap</tt> instance from a stream (i.e., deserialize it).
     */
    private void readObject(java.io.ObjectInputStream s) throws java.io.IOException, ClassNotFoundException {
        // Read in the key type and any hidden stuff
        s.defaultReadObject();
        System.out.println(keyType);
        // Read in size (number of Mappings)
        int size = s.readInt();
        // Read the keys and values, and put the mappings in the HashMap
        for (int i = 0; i < size; i++) {
            s.readObject(); // key
            s.readObject(); // value
        }
    }
}
</pre>

It allows me to call the static getEnumMapKeyType method with any EnumMap, empty or not, to obtain the key type. It uses java.io serialization to get at the information required. The nailing of the serialiVersionUID is not pretty; however, the JDK will probably not change this without good reason...

**Comment by axeluhl** [comment]
A few tweaks may be required to find the enum type during de-serialization depending on class loader structure. I'm working on a PR (see https://github.com/axeluhl/gwt/tree/issue-9584) and have now cascaded class lookup, eventually delegating to the current thread's context class loader which helps especially in OSGi environments.

As for the LinkedHashMap custom field serializer there is a fix possible as discussed above; however, I also see that for Java / JDK versions that support the `AccessibleObject.trySetAccessible` method already they will generate the abovementioned warning already for Java 11 when invoked successfully.

I see two ways for not producing this warning in these cases:
- launch the VM with the `--illegal-access=deny` option; this will however force the `clone()` based approach for the LinkedHashMap serialization which will be expensive for large maps
- when detecting that the `trySetAccessible` method is available, don't even consider using it but resort to `getAccessOrderNoReflection` straight away

In both cases this would produce performance penalties for Java versions 9-16 that could be avoided at the expense of seeing the warning. But with the first approach (`--illegal-access=deny`) the user can choose whether to see the warning and get better performance for serializing large `LinkedHashMap` objects, or not see the warning and get a glimpse already of how performance will degrade with Java 17 anyhow.

Working on a PR for this, see above.
