### ISSUE TITLE
RPC Deserialization of array as value in HashMap is broken.

### ISSUE THREAD

**Issue by brunneng** [gwtproject/gwt#9593]
**GWT version: 2.8.2** 
**Browser (with version): Chrome  63.0.3239.132** 
**Operating System: Windows 10** 

---

##### Description
Class ServerSerializationStreamReader skips value of array during deseriazation of RPC request if this array is set as value of HashMap\<String, Object\>. If more entries are stored in HashMap then deseriazation process is failed with error, because it attempts to parse skipped array value as next key of hash map (which is expected to be of type String, but actually is array).

##### Steps to reproduce

- Create simplest gwt project with one RPC service TestProjectService.
- put method in it 
`public String getMessage(HashMap<String, Object> data)`
- put another method 
`public void dummyMethod(TypeSignatures dummyParam) `
where
public class TypeSignatures implements Serializable, IsSerializable {
   public String[] data;
}
just to notify gwt that type signature String[] will be used in serialization. 
We will not use it anymore.
- Try to call method  getMessage with data:
```
HashMap<String, Object> data = new HashMap<>();
data.put("value", new String[] {"Hello world!"});
data.put("xxx", "1");
```
**Expected result**: method is called, and data is deserialized.
**Actual Result**: Deserialization is failed with exception:

> java.lang.ClassNotFoundException: Hello world!
> 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:427)
> 	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:634)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:592)
> 	at com.google.gwt.user.server.rpc.core.java.util.Map_ServerCustomFieldSerializerBase.deserialize(Map_ServerCustomFieldSerializerBase.java:37)
> 	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserialize(HashMap_ServerCustomFieldSerializer.java:40)
> 	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserializeInstance(HashMap_ServerCustomFieldSerializer.java:54)
> 	at com.google.gwt.user.server.rpc.core.java.util.HashMap_ServerCustomFieldSerializer.deserializeInstance(HashMap_ServerCustomFieldSerializer.java:33)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeImpl(ServerSerializationStreamReader.java:887)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserialize(ServerSerializationStreamReader.java:687)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.readObject(ServerSerializationStreamReader.java:592)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader$ValueReader$8.readValue(ServerSerializationStreamReader.java:149)
> 	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.deserializeValue(ServerSerializationStreamReader.java:434)
> 	at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:312)
> 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:296)
> 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
> 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:499)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
> 	at java.lang.Thread.run(Thread.java:748)

Sample project that reproduces the issue:
[GwtBug1.zip](https://github.com/gwtproject/gwt/files/1677467/GwtBug1.zip)

##### Known workarounds
Use ArrayList instead of array.

**Comment by brunneng** [comment]
I think problem in ServerSerializationStreamReader:892 
lines of code:
```
} else if (instanceClass.isArray()) {
      if (expectedType == null) {
        return deserializeArray(instanceClass, instance);
      }
      Type actualExpectedType = SerializabilityUtil.findActualType(expectedType, resolvedTypes);
      if (actualExpectedType instanceof GenericArrayType) {
        Type arrayType = ((GenericArrayType) actualExpectedType).getGenericComponentType();
        return deserializeArray(instanceClass, instance, arrayType, resolvedTypes);
      } else if (((Class<?>) actualExpectedType).getComponentType() != null) {
        Class<?> arrayType = ((Class<?>) actualExpectedType).getComponentType();
        return deserializeArray(instanceClass, instance, arrayType, resolvedTypes);
      }
    }
}
```
Here expectedType is java.lang.Object which doesn't satisfy any condition inside this if . and value deserialization is just skipped. As for me should be something like:
```
if (expectedType == null) {
        return deserializeArray(instanceClass, instance);
      }
      Type actualExpectedType = SerializabilityUtil.findActualType(expectedType, resolvedTypes);
      if (actualExpectedType instanceof GenericArrayType) {
        Type arrayType = ((GenericArrayType) actualExpectedType).getGenericComponentType();
        return deserializeArray(instanceClass, instance, arrayType, resolvedTypes);
      } else if (((Class<?>) actualExpectedType).getComponentType() != null) {
        Class<?> arrayType = ((Class<?>) actualExpectedType).getComponentType();
        return deserializeArray(instanceClass, instance, arrayType, resolvedTypes);
      }
      else { //##### This is added ###########################################
         return deserializeArray(instanceClass, instance);
      }
}
```

**Comment by niloc132** [comment]
Nice find! 

Related gwt mailing list thread: https://groups.google.com/d/topic/google-web-toolkit/LBUadxl9AUw/discussion - if that is you, thank you for your persistence in finding this, if not it might be helpful to reply there and let them know.

I have several other RPC fixes locally that I'll include this into - thanks for the report and the suggested fix!

**Comment by brianm-sra** [comment]
Is this bug present in GWT 2.8.1 ?
Is it fixed in a later GWT ?
Does it also apply to HashSet<String> ?
