### ISSUE TITLE
Combination of lambda an JavaScriptObject subtyping does not work hosted mode

### ISSUE THREAD

**Issue by norbertroamsys** [gwtproject/gwt#9603]
**GWT version:2.8.2** 
**Browser (with version):Firefox 26.0 (because of hosted mode support)** 
**Operating System: Windows 10** 

---

##### Description

The combination of using a sub type of *JavaScriptObject* and lambda fails at runtime.
Here is a simple test class for reproducing:

```
import com.google.gwt.core.client.JavaScriptObject;
import com.google.gwt.user.client.Window;
import java.util.ArrayList;
import java.util.List;

/**
 * Test for {@link JavaScriptObject} sub type using lambda.
 * 
 * @author nbecker
 */
public final class TestNativeWithLambda extends JavaScriptObject {

    protected TestNativeWithLambda() {
    }
    
    public void doWithoutLambda() {
        final List<String> dummy = new ArrayList<>();
        dummy.add("Hello old World 1");
        dummy.add("Hello old World 2");
        for (final String string : dummy) {
            Window.alert(string);
        }
    }

    public void doByLambda() {
        final List<String> dummy = new ArrayList<>();
        dummy.add("Hello new World 1");
        dummy.add("Hello new World 2");
        dummy.forEach(value -> Window.alert(value));
    }
    
    public static native TestNativeWithLambda create() /*-{
        return {};
    }-*/;
}
```

##### Steps to reproduce

Calling the method *doByLambda()* ...
```
final TestNativeWithLambda test = TestNativeWithLambda.create();
test.doWithoutLambda();
test.doByLambda();
```
... produces the following stack trace:

```
SEVERE: Client side exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: com.roamsys.status.gwt.client.reports.TestNativeWithLambda.lambda$0(Ljava/lang/String;)V
        at com.roamsys.status.gwt.client.reports.TestNativeWithLambda$.doByLambda$(TestNativeWithLambda.java:31)
```

If the lambda is nested some layers deeper or called via native code things getting worse!
You will get the following *NullPointerException* stack trace which is hardly to "understand".
For example the method *AbstractChartist.setData()* contains a lambda expression:
```
SEVERE: Client side exception
java.lang.NullPointerException
        at com.google.gwt.dev.shell.CompilingClassLoader$MyInstanceMethodOracle.findOriginalDeclaringClass(CompilingClassLoader.java:453)
        at com.google.gwt.dev.shell.rewrite.WriteJsoImpl.isObjectMethod(WriteJsoImpl.java:307)
        at com.google.gwt.dev.shell.rewrite.WriteJsoImpl.visitMethod(WriteJsoImpl.java:289)
        at com.google.gwt.dev.shell.rewrite.WriteJsoImpl$ForJsoInterface.visitMethod(WriteJsoImpl.java:228)
        at org.objectweb.asm.ClassVisitor.visitMethod(Unknown Source)
        at com.google.gwt.dev.shell.rewrite.RewriteJsniMethods.visitMethod(RewriteJsniMethods.java:350)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.gwt.dev.shell.rewrite.HostedModeClassRewriter.rewrite(HostedModeClassRewriter.java:253)
        at com.google.gwt.dev.shell.CompilingClassLoader.findClassBytes(CompilingClassLoader.java:1342)
        at com.google.gwt.dev.shell.CompilingClassLoader.findClass(CompilingClassLoader.java:1115)
        at com.google.gwt.dev.shell.CompilingClassLoader.loadClass(CompilingClassLoader.java:1223)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.roamsys.gwtchartist.AbstractChartist.setData(AbstractChartist.java:217)
        at com.roamsys.status.gwt.client.reports.ReportsWidget.lambda$5(ReportsWidget.java:141)

```

##### Known workarounds
Do not use Lambda if using a sub type of *JavaScriptObject*.

**Comment by jnehlmeier** [comment]
Classic DevMode is deprecated since GWT 2.8 and I don't think anyone will invest time fixing it. The code works in SuperDevMode and you should really switch to it these days.

Closing it as wontfix for now, but can be reopened if someone really wants to fix it in classic DevMode.

**Comment by norbertroamsys** [comment]
I know that Classic DevMode is deprecated. But the SuperDevMode is really really no substitution for it.
Debugging is a disaster when you used to do it in Eclipse IDE using Classic DevMode...

**Comment by norbertroamsys** [comment]
Sorry to buzzer again: I talked to our developers and the main reason why we cannot use the SuperDevMode is that we have to use HTTPS. And this still doesn't work: https://github.com/gwtproject/gwt/issues/7535

So either fixing the HTTPS issue or fixing the bug reported by me would help!

**Comment by jnehlmeier** [comment]
As a workaround and with a bit effort you can make HTTPS work with SuperDevMode using a reverse proxy as mentioned in #7535 . This could be set-up once and encapsulated in a Docker image, then every developer can use that image. 

Generally it is more likely that we add HTTPS support to SuperDevMode than investing time into deprecated DevMode.

**Comment by niloc132** [comment]
I've actually just done this work for another project with jetty embedded into it, I'll look at taking it on here.

Of course, you'll need to provide a keystore, passphrase to the dev mode process so it can make use of it, but at that point jetty works great in my experience. Probably should leave some hooks for other configuration to take place as well...

**Comment by pedy711** [comment]
Any progress with HTTPS on Super Dev mode?
