### ISSUE TITLE
dumping AST throws NPE

### ISSUE THREAD

**Issue by zak905** [gwtproject/gwt#9605]
When `gwt.jjs.dumpAst` is set to a file name, dumping the AST throws an NPE at compile time:

```
[INFO]    [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.impl.ToStringGenerationVisitor.visit(ToStringGenerationVisitor.java:611)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:777)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.impl.SourceGenerationVisitor.visit(SourceGenerationVisitor.java:87)
[INFO] 	at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:145)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.impl.SourceGenerationVisitor.visit(SourceGenerationVisitor.java:141)
[INFO] 	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1248)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO] 	at com.google.gwt.dev.jjs.impl.AstDumper.maybeDumpAST(AstDumper.java:96)
[INFO] 	at com.google.gwt.dev.jjs.impl.AstDumper.maybeDumpAST(AstDumper.java:47)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1085)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:192)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NullPointerException
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:128)
[INFO] 	... 27 more
[INFO]       [ERROR] <no source info>: <source info not available>
[INFO]       [ERROR] at Throwable.java(303): java.lang.Throwable$NativeError.equals(Ljava/lang/Object;)Z
[INFO]          com.google.gwt.dev.jjs.ast.JMethod
[INFO]       [ERROR] at Throwable.java(303): java.lang.Throwable$NativeError (extends Object)
[INFO]          com.google.gwt.dev.jjs.ast.JClassType
[INFO]       [ERROR] at Unknown(0): <JProgram>
[INFO]          com.google.gwt.dev.jjs.ast.JProgram
```

these couple of checks seem to fix it: https://github.com/zak905/gwt/commit/96bf399eff29cd1ae70d178874006d1039ab9aa1

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/c/gwt/+/21580/1
