### ISSUE TITLE
GWT Compilation failing with Enum in annotation

### ISSUE THREAD

**Issue by bendol-i3** [gwtproject/gwt#9615]
**GWT version:** 2.8.2 
**Browser (with version):** NA
**Operating System:** Windows 10

---

##### Description
Attempting to compile I receive:
```
[INFO] Caused by: java.lang.reflect.InvocationTargetException
[INFO] 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at com.google.gwt.dev.javac.AnnotationProxyFactory$AnnotationProxyInvocationHandler.invoke(AnnotationProxyFactory.java:248)
[INFO] 	... 76 more
[INFO] Caused by: java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
[INFO] 	at com.google.gwt.dev.javac.AnnotationProxyFactory$AnnotationProxyInvocationHandler.toString(AnnotationProxyFactory.java:271)
[INFO] 	... 80 more
[INFO]       Rebinding org.jboss.errai.marshalling.client.api.MarshallerFactory
[INFO]          Invoking generator org.jboss.errai.marshalling.rebind.MarshallersGenerator
[INFO]             Generating Marshallers Bootstrapper...
```

```java
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Device {

    Type value() default Type.ANY;

    enum Type {
        MOBILE,
        TABLET,
        ANY
    }
}
```

```java
@Device(Device.Type.MOBILE)
public class MyClass {

}
```

This is throwing an undescriptive exception.

Full stack trace: https://gist.github.com/bendol-i3/d80d3ef3353521b7b99519314f073136

##### Steps to reproduce
Setup the annotation like above, then inside of a code generator call:
```java
  if (getAnnotations() != null) {
        for (final Annotation a : getAnnotations()) {
          logger.info(a.toString());
        }
  }
```
Unless there is something funky going on, on my end that should throw the exception.

**Comment by niloc132** [comment]
It looks like it isn't your annotation at all, but a different one where some other property of the annotation is an `int[]`. Looks like the fix would be to branch on the component type of the array and invoke the correct Arrays.toString. Could probably "cheat" a bit and instead wrap the array in another array first, and use deepToString, then remove the outer pair of `[]`s.

**Comment by niloc132** [comment]
https://gwt-review.googlesource.com/#/c/gwt/+/20820

**Comment by bendol-i3** [comment]
@niloc132 should we be checking the primitives before Object[], seems like it will attempt to deepToString otherwise?

**Comment by niloc132** [comment]
If there is a primitive value returned from Method.invoke, it will be boxed (i.e. an Object) - that's the contract of Method.invoke. In theory we could check if method.getReturnType() is a primitive and unbox that way, but as this is just a toString(), I don't think it will matter either way.
