### ISSUE TITLE
GWT 2.8.2 and HtmlUnit 2.19 : Problem with a GWTTestCase using com.google.gwt.dom.client.InputElement::getSize()

### ISSUE THREAD

**Issue by bwnyasse** [gwtproject/gwt#9633]
**GWT version:** 2.8.2
**Browser (with version):**  All supported by HtmlUnit 2.19 
**Operating System:**  Windows

---

##### Description
After a migration from GWT 2.7 to GWT 2.8.2 , I am facing a kind of regression in a GWTTestCase.

The GWTTestcase calls the method InputElement:getSize that uses JSNI

```
       public final native int getSize () / * - {
           return this.size;
       } - * /;
```

Actually, the test fails with the following error:

```
[INFO] com.google.gwt.dev.shell.HostedModeException: Something other than an int was returned from JSNI method '@com.google.gwt.dom.client.InputElement::getSize()': JS value of type string, expected int
[INFO]  at com.google.gwt.dev.shell.JsValueGlue.getIntRange(JsValueGlue.java:267)
[INFO]  at com.google.gwt.dev.shell.JsValueGlue.get(JsValueGlue.java:144)
[INFO]  at com.google.gwt.dev.shell.ModuleSpace.invokeNativeInt(ModuleSpace.java:269)
[INFO]  at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeInt(JavaScriptHost.java:75)
[INFO]  at com.google.gwt.dom.client.InputElement$.getSize$(InputElement.java)
[...]
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:498)
[INFO]  at com.google.gwt.junit.client.impl.GWTTestAccessor.invoke(GWTTestAccessor.java:39)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner.executeTestMethod(GWTRunner.java:226)
[INFO]  at com.google.gwt.junit.client.GWTTestCase.doRunTest(GWTTestCase.java:157)
[INFO]  at junit.framework.TestCase.runTest(TestCase.java:59)
[INFO]  at com.google.gwt.junit.client.GWTTestCase.runBare(GWTTestCase.java:151)
[INFO]  at com.google.gwt.junit.client.GWTTestCase.__doRunTest(GWTTestCase.java:115)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner.runTest(GWTRunner.java:302)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner.doRunTest(GWTRunner.java:235)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner.access$9(GWTRunner.java:229)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:106)
[INFO]  at com.google.gwt.junit.client.impl.GWTRunner$TestBlockListener.onSuccess(GWTRunner.java:1)
[INFO]  at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.onResponseReceived(RequestCallbackAdapter.java:232)
[INFO]  at com.google.gwt.http.client.Request.fireOnResponseReceived(Request.java:250)
[INFO]  at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
```

So it looks like with an unknow reason , com.google.gwt.dom.client.InputElement::getSize() retrieve a `String` instead of an `int`

##### Known workarounds

The only thing for me to continue the migration is to disable the test.

**Comment by niloc132** [comment]
What element are you calling that on? Is it a bug in HtmlUnit that it is incorrectly something other than a number? Or would all browsers agree that sometimes `size` should be something other than a number?

**Comment by tbroyer** [comment]
Could you try running the test in prod mode? This is the new default in GWT 2.8, but your tooling might be forcing the legacy dev mode.
