### ISSUE TITLE
Unexpected internal compiler error

### ISSUE THREAD

**Issue by edmiikk** [gwtproject/gwt#9655]
**GWT version: 2.8.2** 
**Browser (with version): Chrome Version 72.0.3626.121 (Official Build) (64-bit)** 
**Operating System: Ubuntu 16.04 LTS** 
**IDE: Eclipse Neon.3 GWT Plugin: 3.0.0.201710131939 **
---

##### Description

        Unification traversed 8101 fields and methods and 2144 types. 236 are considered part of the current module and 287 had all of their fields and methods traversed.
         [WARN] Some stale types ([ ... 42 types here ...]) were not reprocessed as was expected. This is either a compiler bug or a Generator has legitimately stopped creating these types.
         Compiling 1 permutation
            Compiling permutation 0...
            [ERROR] Unexpected internal compiler error
java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.HasName$1.compare(HasName.java:33)
	at com.google.gwt.dev.jjs.ast.HasName$1.compare(HasName.java:30)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at com.google.gwt.dev.jjs.ast.JTypeOracle.getCastableDestinationTypes(JTypeOracle.java:734)
	at com.google.gwt.dev.jjs.impl.ComputeExhaustiveCastabilityInformation.createCompleteCastMap(ComputeExhaustiveCastabilityInformation.java:44)
	at com.google.gwt.dev.jjs.impl.ComputeExhaustiveCastabilityInformation.execImpl(ComputeExhaustiveCastabilityInformation.java:50)
	at com.google.gwt.dev.jjs.impl.ComputeExhaustiveCastabilityInformation.exec(ComputeExhaustiveCastabilityInformation.java:32)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.normalizeSemantics(JavaToJavaScriptCompiler.java:500)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:364)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
            [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:112)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:748)
            [ERROR] Not all permutation were compiled , completed (0/1)
      [WARN] recompile failed
      [WARN] continuing to serve previous version

##### Steps to reproduce

1. Refactor a client package to a sub package i.e. a.b.c.d => a.b.c.d.e
2. 𝄆 Recompiles in SuperDevMode => fail
3. Project clean, click on Try Again 𝄇

##### Known workarounds
Run GWT compile from the GWT project level menu, then refresh the launch page. 

##### References
1. https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/EGG7vT-c78w
2. https://switch-case.ru/43334540

**Comment by jnehlmeier** [comment]
I assume it works again if you clean the SDM cache by clicking the small "clean" button in the SDM UI running on localhost:9876 ?
