### ISSUE TITLE
Does GWT 2.7 supports ASM 7.x

### ISSUE THREAD

**Issue by amitajmani1** [gwtproject/gwt#9667]
We are getting following error after upgrading ASM version to 7.0 from 5.x . The GWT version is 2.7

[java] Compilation completed in 7.42 seconds
[java] [ERROR] Unexpected internal compiler error
[java] java.lang.ArrayIndexOutOfBoundsException: 9216
[java] at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3425)
[java] at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3412)
[java] at org.objectweb.asm.ClassReader.accept(ClassReader.java:559)
[java] at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
[java] at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:228)
[java] at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
[java] at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
[java] at com.google.gwt.dev.javac.Dependencies$Ref.(Dependencies.java:42)
[java] at com.google.gwt.dev.javac.Dependencies$Ref.(Dependencies.java:37)
[java] at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:114)
[java] at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:366)
[java] at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
[java] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
[java] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
[java] at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
[java] at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[java] at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[java] at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[java] at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[java] at com.google.gwt.dev.Compiler.run(Compiler.java:158)
[java] at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
[java] at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[java] at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[java] at com.google.gwt.dev.Compiler.main(Compiler.java:127)

The stacktrace doesn't tell the offending class name.

Any ideas how can we make this stacktrace more verbose or does GWT 2.7 compatible with ASM 7.0 ?

Thanks

**Comment by tbroyer** [comment]
A debugger will tell you; but out of curiosity why are you upgrading ASM?

**Comment by amitajmani1** [comment]
We are migrating Spring and hibernate to 5.x which mandates ASM 7.x. 

I have enabled the compiler log level to 'ALL' but couldnt find much info.

<target name="compile-gwt" description="GWT compile to JavaScript (production mode)">
		<delete dir="war/webclient"/>
		<delete dir="war/admin"/>
		<delete dir="${bin_dir}/gen"/>
		<ivy:cachepath organisation="org.ow2.asm" module="asm" revision="7.0"  pathid="gwt.classpath" inline="true" />

		<java failonerror="true" fork="true" classpathref="gwt.classpath" classname="com.google.gwt.dev.Compiler">
			<classpath>
				<pathelement location="${bin_dir}/main"/>
				<fileset dir="${bin_dir}/lib/compile">
					<include name="jars/*.jar"/>
					<include name="bundles/*.jar"/>
					<include name="sources/*.jar"/>
				</fileset>
				<pathelement location="src/main/java"/>
			</classpath>
			
			<jvmarg value="-Xmx640M"/>
			<jvmarg value="-XX:ReservedCodeCacheSize=128M"/>
			<arg line="-logLevel ALL"/>
			<arg line="-war war"/>
			<arg line='-gen "${bin_dir}/gen"'/>
			<arg line="-localWorkers 1"/>
			<arg line="-compileReport"/>
			<arg line="-failOnError"/>
			<arg line="-draftCompile"/>
			<arg value="ca.teranet.terranova.webclient.WebClient"/>
			<arg value="ca.teranet.terranova.webclient.Admin"/>
		</java>
	</target>

**Comment by amitajmani1** [comment]
btw, its a compile time error

**Comment by tbroyer** [comment]
Spring and hibernate are server side dependencies, you don't need them (and shouldn't add them) in your GWT (client-side) classpath.

**Comment by amitajmani1** [comment]
you are right, but its a legacy application which inherits lot of modules from server side. 

The compilation failed with the same error, even we keep the ASM version (5.x) same in GWT Module as before. 

It only works when both GWT module (client side ) and Server side both use ASM 5.x

**Comment by amitajmani1** [comment]
is there a way GWT print offending class name during compilation ?

**Comment by ibaca** [comment]
So you can choose between upgrading a legacy app configuration to correctly configure the GWT compiler classpath solving your current and future problems and probably making it compile a bit faster but you choose to investigate how to make a pretty complex and out-of-your-control compiler work with a different version of an obscure library (ASM, very major version dependant). Looks like you are choosing the non-future-useful and more difficult path! 😉 Hope you don't want to load ECJ in the server, you will get a lot of fun!

FYI you can exclude dependencies in maven, I mean, you can add the server dependency to your client code, and exclude the conflicting or even all dependencies, only depending in the source code. Not the best solution, but It might be useful in the meantime. Example to exclude all sub-dependencies of a dependency:
```
<dependency><groupId>my.company</groupId><artifactId>server</artifactId><version>${project.version}</version>
  <exclusions><exclusion><groupId>*</groupId><artifactId>*</artifactId></exclusion></exclusions>
</dependency>
```

**Comment by amitajmani1** [comment]
Thanks Ibaca, After decoupling the Server module from Client Side, fix the issue "ArrayIndexOutOfBoundException". 

Now, Compilation fail with below error 
     **[java] Shutting down PersistentUnitCache thread**

i did notice lot of instances like 

Found better fallback match for \<replace-with class='com.google.gwt.dom.client.StyleInjector.StyleInjectorImplIE'\/\>
     [java]          Checking rule \<replace-with class='com.google.gwt.dom.client.DOMImplMozilla'\/\>
     [java]             Checking if all subconditions are true (\<all\>)
     [java]                \<when-type-is class='com.google.gwt.dom.client.DOMImpl'\/\>
     [java]                   Not an exact match
     [java]                No: One or more subconditions was false
     [java]          Rule did not match
     [java]          Found better fallback match for \<replace-with class='com.google.gwt.dom.client.DOMImplMozilla'\/\>
     [java]          Checking rule \<replace-with class='com.google.gwt.dom.client.DOMImplIE8'\/\>
     [java]             Checking if all subconditions are true (\<all\>)
     [java]                \<when-type-is class='com.google.gwt.dom.client.DOMImpl'\/\>
     [java]                   Not an exact match
     [java]                No: One or more subconditions was false
     [java]          Rule did not match
     [java]          Found better fallback match for \<replace-with class='com.google.gwt.dom.client.DOMImplIE8'\/\>
     [java]          Checking rule \<replace-with class='com.google.gwt.dom.client.DOMImplIE9'\/\>
     [java]             Checking if all subconditions are true (\<all\>)
     [java]                \<when-type-is class='com.google.gwt.dom.client.DOMImpl'\/\>
     [java]                   Not an exact match
     [java]                No: One or more subconditions was false
     [java]          Rule did not match

Any suggestions, what are these and how to address them

**Comment by amitajmani1** [comment]
Looks like deleting **gwt-intcache** resolve this issue, build completed successfully. 

but I am still interested to know the cause of this "Shutting down PersistentUnitCache" issue, if you can suggest some good read about the GWT compilation lifecycle.

**Comment by zbynek** [comment]
The original issue reported here is fixed by decoupling server and client code.

@amitajmani1 in case  the secondary issue with PersistentUnitCache is still relevant after 6 years please open a new ticket -- the message itself is printed even if GWT works correctly, so more information would be needed.
https://github.com/gwtproject/gwt/blob/4a85a120b586a15029deea15e07a43a8809684ee/dev/core/src/com/google/gwt/dev/javac/PersistentUnitCache.java#L469
