### ISSUE TITLE
Proper JAVA_CLASS_PATH split in ResourceLoaders

### ISSUE THREAD

**Issue by eliasbalasis** [gwtproject/gwt#9678]
**GWT version:** 2.8.2
**Browser (with version):** Chrome 79.0.3945.88
**Operating System:** Windows 10

##### Description
When running GWT applications in "Spring Tools 4" (latest) using "GWT Eclipse Plugin" (latest),
the "java.class.path" Java property is somehow constructed in quotes.

This is not handled well by
getClassPath() method of com.google.gwt.dev.cfg.ResourceLoaders class
which expects the classpath not to be quotes enclosed
see https://github.com/gwtproject/gwt/blob/2.8.2/dev/core/src/com/google/gwt/dev/cfg/ResourceLoaders.java

Latest version of same class at https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/cfg/ResourceLoaders.java remains unchanged, still not handling the quotes enclosed classpath.

The error produced is:
`
Exception in thread "Thread-3" java.nio.file.InvalidPathException: Illegal char <"> at index 0: "HIDDEN\src\main\java
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.gwt.dev.cfg.ResourceLoaders$ContextClassLoaderAdapter.getClassPath(ResourceLoaders.java:62)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.addAllClassPathEntries(ResourceOracleImpl.java:315)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.getAllClassPathEntries(ResourceOracleImpl.java:353)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.preload(ResourceOracleImpl.java:216)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.preload(ResourceOracleImpl.java:207)
	at com.google.gwt.dev.DevMode$1.run(DevMode.java:539)
	at java.lang.Thread.run(Thread.java:748)
java.nio.file.InvalidPathException: Illegal char <"> at index 0: "HIDDEN\src\main\java
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.google.gwt.dev.cfg.ResourceLoaders$ContextClassLoaderAdapter.getClassPath(ResourceLoaders.java:62)
	at com.google.gwt.dev.cfg.ResourceLoaders$PrefixLoader.getClassPath(ResourceLoaders.java:114)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.addAllClassPathEntries(ResourceOracleImpl.java:315)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.getAllClassPathEntries(ResourceOracleImpl.java:353)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.<init>(ResourceOracleImpl.java:387)
	at com.google.gwt.dev.cfg.ModuleDef.normalize(ModuleDef.java:678)
	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:200)
	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:151)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:445)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
`

This is currently blocking our development work and is jeopardizing delivery of our commercial projects because our developers cannot run the applications on their development machines.

It is worth mentioning that we didn't have such problems until we recently updated "Spring Tools 4".
Therefore, we suspect that the classpath is long enough and something is enclosing it in quotes.
So we tried to use the "Use temporary JAR to specify classpath (to avoid classpath length limitations)" option in "GWT Development Mode" launch configuration under Eclipse IDE but started getting the following error:

[ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

Further investigation revealed that when using the "Use temporary JAR to specify classpath (to avoid classpath length limitations)" option, the "java.class.path" property has the value of the Eclipse generated classpath-only JAR which is not enough.
As a result, this cannot be a workaround.

An alternative, but perhaps more demanding approach, would be having gwt-dev search the actual classh path instead of the "java.class.path" Java property

We are really at a dead end here.
Please asisst as soon as possible

##### Steps to reproduce
No particular steps, any GWT application running in Eclipse IDE may inevitably have a command line with a classpath enclosed in quotes under "java.class.path" Java property (from CLASSPATH environment variable)

##### Links to further discussions
https://bugs.eclipse.org/bugs/show_bug.cgi?id=558712
https://stackoverflow.com/questions/59566589/eclipse-launch-java-classpath-enclosed-in-quotes-breaks-3rd-party-tools

**Comment by eliasbalasis** [comment]
This was finally identified as an "Eclipse" bug.

There is no change required on "GWT" side.
