### ISSUE TITLE
GWTTestCase & DevMode unable to handle expression in the form: "some string" + (someCondition ? "aValue" : aNonStringValue)

### ISSUE THREAD

**Issue by rdeangelis83** [gwtproject/gwt#9694]
[helloworld-gwt.zip](https://github.com/gwtproject/gwt/files/4757020/helloworld-gwt.zip)

**GWT version: 2.9.0** 
**Browser (with version): All** 
**Operating System: All** 

---

##### Description

Code in GWTTestCases that contains expression in the form "some string" + (someCondition ? "aValue" : aNonStringValue) can not be compiled in DevMode. 

As result an assertion in com.google.gwt.dev.javac.JdtUtil#signature() will be fired.

##### Steps to reproduce

See attached helloworld-gwt.zip. Or simply add following expression into your code GWTTestCase code and run in in devMode: "some string" + (someCondition ? "aValue" : aNonStringValue) 

##### Known workarounds
Disable assertions solves the problem.
E.g. using the net.ltgt.gwt.maven:gwt-maven-plugin
```
<enableAssertions>false</enableAssertions>
```

**Comment by tbroyer** [comment]
“Classic” DevMode has been deprecated for nearly 4 years now (http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0_RC1; a bit less if you only account for non-RC versions, but still) so as long as it works in webMode I don't think this is something that's going to ever be fixed or even investigated.

**Comment by rdeangelis83** [comment]
As far what I understand is that it seems to be an bug in the eclipse compiler. It should also happen in non devMode but because the assertions are disabled it doesn't appear. But I'm not 100% sure.

**Comment by realityforge** [comment]
We experience in superdev mode, I guess we must enable assertions by default ;)

Our workaround was just to eliminate the intersection type by always using/converting to strings.

**Comment by rdeangelis83** [comment]
> We experience in superdev mode, I guess we must enable assertions by default ;)
> 
> Our workaround was just to eliminate the intersection type by always using/converting to strings.

Yeah it really seems that the assertions are disabled per default in superdev mode. Because the super dev mode works in my small attached example.

**Comment by kevzlou7979** [comment]
We are having similar issues too on GWT  2.9.0 when running our Unit Tests

```
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:4033)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:647)
	at org.eclipse.jdt.internal.compiler.ast.ConditionalExpression.traverse(ConditionalExpression.java:827)
	at org.eclipse.jdt.internal.compiler.ast.BinaryExpression.traverse(BinaryExpression.java:1919)
	at org.eclipse.jdt.internal.compiler.ast.BinaryExpression.traverse(BinaryExpression.java:1919)
	at org.eclipse.jdt.internal.compiler.ast.BinaryExpression.traverse(BinaryExpression.java:1919)
	at org.eclipse.jdt.internal.compiler.ast.BinaryExpression.traverse(BinaryExpression.java:1919)
	at org.eclipse.jdt.internal.compiler.ast.CombinedBinaryExpression.traverse(CombinedBinaryExpression.java:370)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1107)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:365)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1448)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3969)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:4007)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:128)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:322)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:575)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1020)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:322)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:210)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
	at com.google.gwt.junit.JUnitShell.compileForWebMode(JUnitShell.java:1093)
	at com.google.gwt.junit.JUnitShell.maybeCompileForWebMode(JUnitShell.java:1158)
	at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl2(CompileStrategy.java:183)
	at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl(CompileStrategy.java:113)
	at com.google.gwt.junit.SimpleCompileStrategy.maybeCompileModule(SimpleCompileStrategy.java:36)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1349)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1317)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:681)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.AssertionError
	at com.google.gwt.dev.javac.JdtUtil.signature(JdtUtil.java:369)
	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:121)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:641)
	... 49 more

com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)

	at com.google.gwt.junit.JUnitShell.compileForWebMode(JUnitShell.java:1098)
	at com.google.gwt.junit.JUnitShell.maybeCompileForWebMode(JUnitShell.java:1158)
	at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl2(CompileStrategy.java:183)
	at com.google.gwt.junit.CompileStrategy.maybeCompileModuleImpl(CompileStrategy.java:113)
	at com.google.gwt.junit.SimpleCompileStrategy.maybeCompileModule(SimpleCompileStrategy.java:36)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1349)
	at com.google.gwt.junit.JUnitShell.runTestImpl(JUnitShell.java:1317)
	at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:681)
	at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Comment by Greunlis** [comment]
> A more correct solution would be to add the handling in `GwtAstBuilder#endVisit(ConditionalExpression x, BlockScope scope)`, and insert an intersection cast there, similar to what @niloc132 suggested; in that case the assertion should remain.
> 
> I am happy to review the code.

I am experiencing the same issue using SDM with a construct like `"params: " + java.util.Arrays.asList(1, "1", true)`
The intersection type for varargs I see is `java.lang.Object & Comparable<?> & java.io.Serializable`

```
Caused by: java.lang.AssertionError
	at com.google.gwt.dev.javac.JdtUtil.signature(JdtUtil.java:369)
	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:121)
	at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:138)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.popCallArguments(GwtAstBuilder.java:3229)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1536)
```
I can't seem to find the correct place to insert the intersection cast as I don't really understand the compiler that much.
Is there a chance of fixing this?

Thanks.
