### ISSUE TITLE
GWT 2.8.0 -> 2.9.0 Update com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST

### ISSUE THREAD

**Issue by jproples** [gwtproject/gwt#9699]
**GWT version: 2.9.0** 
**Browser (with version):** 
**Operating System: Windows IntelliJ 2019.3.5** 

---

##### Description
I updated our gwt application from 2.8.0 to 2.9.0. Now the application doesn't compiles anymore.

GWT Dependencies we using in this application:

com.allen-sauer.gwt.log:gwt-log:3.3.2

com.google.code.gson:gson:2.8.6
com.google.errorprone:error_prone_annotations:2.1.3
com.google.guava:guava:25.0-jre
com.google.gwt.eventbinder:eventbinder:1.1.0
com.google.gwt.inject:gin:2.1.2
com.google.gwt:gwt-dev:2.9.0
com.google.gwt:gwt-servlet:2.9.0
com.google.gwt:gwt-user:2.9.0
com.google.inject.extensions:guice-assistedinject:3.0
com.google.inject:guice:3.0
com.google.j2objc:j2objc-annotations:1.1
com.google.jsinterop:jsinterop-annotations:2.0.0
com.google.web.bindery:requestfactory-apt:2.9.0
com.google.web.bindery:requestfactory-server:2.9.0
com.googlecode.gwtquery:gwtquery:1.5-beta1

This error will thrown on start the application in IntelliJ
`
 Loading Java files in de.evosec.vici.ViciDev.
com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:4033)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:2190)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.traverse(TryStatement.java:1127)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:354)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1478)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1351)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3969)
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:4007)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:128)
	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:322)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:550)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:462)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1020)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:322)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:213)
	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:785)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:888)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:705)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
Caused by: java.lang.NoSuchFieldError: resources
	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:2165)
	... 35 more
`

This output generates our Jenkins on failed build.
`
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:4033)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:2190)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TryStatement.traverse(TryStatement.java:1127)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:354)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1367)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3969)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:4007)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:128)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:322)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:550)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:462)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1020)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:322)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:210)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:132)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:110)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:113)
[INFO] Caused by: java.lang.NoSuchFieldError: resources
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:2165)
[INFO] 	... 25 more
[INFO]    [ERROR] at StringQuoter.java(74): try
[INFO]   {
[INFO]     return new Date(Long.parseLong(date));
[INFO]   }
[INFO] catch (NumberFormatException ignored)
[INFO]   {
[INFO]   }
[INFO]       org.eclipse.jdt.internal.compiler.ast.TryStatement
`

**Comment by jnehlmeier** [comment]
```java
Caused by: java.lang.NoSuchFieldError: resources 
at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:2165)
```
So `TryStatement.resources` does not seem to exist during compilation. Given that `TryStatement` is a class of Eclipse JDT it seems like your app has a version of Eclipse JDT in class path that is incompatible with the one GWT depends on.

**Comment by jproples** [comment]
Hey jnehlmeier, yes i had the org.eclipse.jdt.core.compiler : ecj : 4.6.1 dependency in my project. But the gwt-dev dependency contains org.eclipse.jdt.core as static code.

I exclude the 4.6.1 out of all parent dependencies so only the gwt version is on classpath. Now the compiler starts working.

Thanks!
