### ISSUE TITLE
SDM hangs.

### ISSUE THREAD

**Issue by michael-newsrx** [gwtproject/gwt#9704]
**GWT version:** 2.9.0
**Browser (with version):** Firefox 9.0 (64-bit)
**Operating System:**  Ubuntu-Mate / stable

---

##### Description

This is a Gradle setup. JDK 11. JDK is set to "-release 8" in the build.gradle files.

I'm running gretty plugin for tomcat and in a separate window I'm running SDM via gradle clientproject:gwts

While I can't determine the combination of events which cause it, Gwt SDM will hang on a recompile request and just sit there.

I've tried switching JDK's (adopt vs stock), no effect.

###### Good compile followed up by a hung compile

It never makes it to the bind step.

```java
GET /sourcemaps/gwt/4D3B566A0CBDC031DBDFA1CA5793488A_sourcemap.json
   sent source map for module 'gwt' in 79 ms
GET /recompile/gwt
   Job com.newsrx.ButterAdmin_1_2
      starting job: com.newsrx.ButterAdmin_1_2
      binding: locale=default
      binding: user.agent=safari
      Compiling module com.newsrx.ButterAdmin
         Unification traversed 2613 fields and methods and 824 types. 3 are considered part of the current module and 41 had all of their fields and methods traversed.
         Compiling 1 permutation
            Compiling permutation 0...
            Linking per-type JS with 3 new/changed types.
            Source Maps Enabled
         Compile of permutations succeeded
         Compilation succeeded -- 1.993s
      Linking into /home/michael/git/ButterAdmin/ButterAdmin-client/build/gwt/work/com.newsrx.ButterAdmin/compile-4/war/gwt; Writing extras to /home/michael/git/ButterAdmin/ButterAdmin-client/build/gwt/work/com.newsrx.ButterAdmin/compile-4/extras/gwt
         Link succeeded
         Linking succeeded -- 0.161s
      2.390s total -- Compile completed
GET /sourcemaps/gwt/064A779E42406BB86B7113092B03EC4E_sourcemap.json
   sent source map for module 'gwt' in 60 ms
GET /recompile/gwt
   Job com.newsrx.ButterAdmin_1_3
      starting job: com.newsrx.ButterAdmin_1_3
```

##### Steps to reproduce

As I don't know a sure fire way other than doing a compile, doing edits, then waiting a few minutes or so, doing a new compile, repeating these steps until the problem triggers.

**Comment by tbroyer** [comment]
What's your Gradle setup? Are you using some GWT plugin (which one?) or a JavaExec task?

**Comment by michael-newsrx** [comment]
```bash
../gradlew -version

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (AdoptOpenJDK 11.0.8+10)
OS:           Linux 5.4.0-42-generic amd64
```

```groovy
apply plugin: 'com.diffplug.eclipse.apt' //Required for apt processing in Eclipse.
apply plugin: 'gwt'

buildscript {	
    dependencies {
        classpath 'org.wisepersist:gwt-gradle-plugin:1.+'
        classpath "gradle.plugin.org.gretty:gretty:2.3.1"
        classpath "com.diffplug.gradle:goomph:3.24.0" //Required for apt processing in Eclipse.
    }
}
```

Here's a fully copy of the build.gradle file.

[build.gradle.zip](https://github.com/gwtproject/gwt/files/5059254/build.gradle.zip)

**Comment by michael-newsrx** [comment]
I don't know if it is related or not, but I sometimes get missing file errors, as the SDM doesn't seem to wait on apt processing?

```java
binding: locale=default
binding: user.agent=safari
Compiling module com.newsrx.ButterAdmin
   Ignored 2 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   Finding entry point classes
      Tracing compile failure path for type 'com.newsrx.client.AppEntryPoint'
         [ERROR] Errors in 'file:/home/michael/git/ButterAdmin/ButterAdmin-client/src/main/java/com/newsrx/client/AppEntryPoint.java'
            [ERROR] Line 34: No source code is available for type com.newsrx.client.dagger.DaggerAppComponents; did you forget to inherit a required module?
      [ERROR] Hint: Check the inheritance chain from your module; it may not be inheriting a required module or a module may not be adding its source path entries properly
[ERROR] Compiler returned false
```

**Comment by jnehlmeier** [comment]
> I don't know if it is related or not, but I sometimes get missing file errors, as the SDM doesn't seem to wait on apt processing?

Seems logical. SDM does not know about APT for client side code so APT must be finished before you trigger a recompile in SDM.

**Comment by michael-newsrx** [comment]
> > I don't know if it is related or not, but I sometimes get missing file errors, as the SDM doesn't seem to wait on apt processing?
> 
> Seems logical. SDM does not know about APT for client side code so APT must be finished before you trigger a recompile in SDM.

Ok, so to keep SDM happy, I really need to point it to the IDE generated source files instead of the main build's generated source files. Like so:

```groovy
gwt {
	// ...	
	compiler {
		//for building via Gradle
		src += files(compileJava.options.annotationProcessorGeneratedSourcesDirectory)
	}
	
	superDev {
		//to pick up IDE initiated changes caused by edits for building via SDM
		src += files(project.eclipse.jdt.apt.genSrcDir)		
		}
}
```

**Comment by michael-newsrx** [comment]
When the UI Binder XMLs are reprocessing, does SDM try and pull the DOCTYPE referenced if it is in the XML file?

```xml
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
```

**Comment by tbroyer** [comment]
Not that one: https://github.com/gwtproject/gwt/blob/7de9ce8930d029cef35a41f79202213a736b9e86/user/src/com/google/gwt/uibinder/rebind/GwtResourceEntityResolver.java#L43-L46

**Comment by michael-newsrx** [comment]
Well, so far today, no forever hangs, but my SDM compile times are all over the place. 10 minutes for one?

34.944s total -- Compile completed
56.377s total -- Compile completed
9.843s total -- Compile completed
9.554s total -- Compile completed
156.363s total -- Compile completed
646.053s total -- Compile completed
9.715s total -- Compile completed
362.437s total -- Compile completed
9.810s total -- Compile completed
610.234s total -- Compile completed
9.754s total -- Compile completed
9.187s total -- Compile completed

**Comment by michael-newsrx** [comment]
> Not that one:
> 
> https://github.com/gwtproject/gwt/blob/7de9ce8930d029cef35a41f79202213a736b9e86/user/src/com/google/gwt/uibinder/rebind/GwtResourceEntityResolver.java#L43-L46

Good to know.

My Eclipse started having issues with the entities DTD, (like it couldn't download it or something), and I ended up removing all the DOCTYPE declarations out of the UI files. (Only had a couple of entities, and switched those to UTF-8).

**Comment by jnehlmeier** [comment]
> Well, so far today, no forever hangs, but my SDM compile times are all over the place. 10 minutes for one?
> 
> 34.944s total -- Compile completed
> 56.377s total -- Compile completed
> 9.843s total -- Compile completed
> 9.554s total -- Compile completed
> 156.363s total -- Compile completed
> 646.053s total -- Compile completed
> 9.715s total -- Compile completed
> 362.437s total -- Compile completed
> 9.810s total -- Compile completed
> 610.234s total -- Compile completed
> 9.754s total -- Compile completed
> 9.187s total -- Compile completed

Weird. Never seen this. Maybe connect to SDM using JVisualVM/MissionControl to see how the heap behaves over time. Maybe there was a large amount of garbage collection going on. This could also cause SDM to appear hanging if the JVM continuously does garbage collects.

**Comment by michael-newsrx** [comment]
Heap seems to cycle over and over, like it is doing a set of ops, then starts over.

![image](https://user-images.githubusercontent.com/5214185/90252839-334fd600-de0e-11ea-8d9a-8819eb2921ba.png)

**Comment by michael-newsrx** [comment]
The heap allocation/release seems to be related to a byte[] and a sun.nio.fs.UnixPath allocation repeating cycle.

![image](https://user-images.githubusercontent.com/5214185/90253166-b83aef80-de0e-11ea-9498-1b92f8d93e53.png)

**Comment by michael-newsrx** [comment]
![image](https://user-images.githubusercontent.com/5214185/90253371-0bad3d80-de0f-11ea-8d9a-efea2a12bbd5.png)

![image](https://user-images.githubusercontent.com/5214185/90253407-1b2c8680-de0f-11ea-9da8-6336c473f5d8.png)

**Comment by jnehlmeier** [comment]
> Heap seems to cycle over and over, like it is doing a set of ops, then starts over.
> 
> ![image](https://user-images.githubusercontent.com/5214185/90252839-334fd600-de0e-11ea-8d9a-8819eb2921ba.png)

So this is while it hangs or makes a very slow compile? 

You could try disabling file watching in SDM. Once disabled SDM will always do a full directory scan and won't rely on Java's FileWatcher API.

To disable it add the system property `-Dgwt.watchFileChanges=false' to SDM command line.

**Comment by realityforge** [comment]
I had a poke around to see what I could see and it is a deadlock. Here's a trace of the two threads that seem to be the issue (the lock being `0x0000000743e70170`).

```
"Thread-6" #24 prio=5 os_prio=31 tid=0x00007fa2ef211000 nid=0x941f waiting for monitor entry [0x0000700010732000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.disable(PollingWatchService.java:296)
	- waiting to lock <0x00000007b79aa718> (a sun.nio.fs.PollingWatchService$PollingWatchKey)
	at sun.nio.fs.PollingWatchService.implClose(PollingWatchService.java:183)
	- locked <0x00000007b79aa888> (a java.util.HashMap)
	at sun.nio.fs.AbstractWatchService.close(AbstractWatchService.java:153)
	- locked <0x00000007b79aa878> (a java.lang.Object)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.stopWatchService(ResourceAccumulator.java:107)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.maybeInitializeWatchService(ResourceAccumulator.java:96)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.fullRefresh(ResourceAccumulator.java:89)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.refresh(ResourceAccumulator.java:123)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.refreshResources(ResourceAccumulator.java:67)
	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager.refreshResources(ResourceAccumulatorManager.java:128)
	- locked <0x0000000743e70170> (a java.lang.Class for com.google.gwt.dev.resource.impl.ResourceAccumulatorManager)
	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager$1.run(ResourceAccumulatorManager.java:91)

```

and 

```
"pool-5-thread-1" #53 prio=5 os_prio=31 tid=0x00007fa2ec135000 nid=0x8c23 waiting for monitor entry [0x0000700012411000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager.getResources(ResourceAccumulatorManager.java:104)
	- waiting to lock <0x0000000743e70170> (a java.lang.Class for com.google.gwt.dev.resource.impl.ResourceAccumulatorManager)
	at com.google.gwt.dev.resource.impl.DirectoryClassPathEntry.findApplicableResources(DirectoryClassPathEntry.java:49)
	at com.google.gwt.dev.resource.impl.ResourceOracleImpl.scanResources(ResourceOracleImpl.java:256)
	- locked <0x000000074a1d6110> (a com.google.gwt.dev.resource.impl.ResourceOracleImpl)
	at com.google.gwt.dev.cfg.ModuleDef.ensureResourcesScanned(ModuleDef.java:729)
	- locked <0x0000000747f0ecd8> (a com.google.gwt.dev.cfg.ModuleDef)
	at com.google.gwt.dev.cfg.ModuleDef.getSourceResourceOracle(ModuleDef.java:567)
	- locked <0x0000000747f0ecd8> (a com.google.gwt.dev.cfg.ModuleDef)
	at com.google.gwt.dev.CompilerContext$Builder.initializeResourceOracles(CompilerContext.java:100)
	at com.google.gwt.dev.CompilerContext$Builder.build(CompilerContext.java:48)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:447)
	at com.google.gwt.dev.codeserver.Recompiler.getRecompileJs(Recompiler.java:297)
	- locked <0x000000074116f318> (a com.google.gwt.dev.codeserver.Recompiler)
	at com.google.gwt.dev.codeserver.Outbox.getRecompileJs(Outbox.java:307)
	at com.google.gwt.dev.codeserver.JobRunner$1.call(JobRunner.java:69)
	at com.google.gwt.dev.codeserver.JobRunner$1.call(JobRunner.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

If I get time later in the week I may dig deeper to see what the fix is but in case anyone else is interested...

**Comment by niloc132** [comment]
It looks like something is missing from your thread dumps - I see that the second trace is stuck waiting for `ResourceAccumulatorManager`, which the first thread still holds, but the first thread is stuck waiting for a `sun.nio.fs.PollingWatchService$PollingWatchKey` instance, and the other thread doesn't hold that instance. Somewhere else in the entire thread dump should be the info on which thread holds the PollingWatchKey, and why _that_ thread won't give it back yet.

**Comment by michael-newsrx** [comment]
> You could try disabling file watching in SDM. Once disabled SDM will always do a full directory scan and won't rely on Java's FileWatcher API.
> 
> To disable it add the system property `-Dgwt.watchFileChanges=false' to SDM command line.

After a big of Googling combined with guessed config attempets, finally figured how to add the define to the JVM running SDM. I'll see how it goes today and let you know.

For those interested:

```groovy
tasks.withType(org.wisepersist.gradle.plugins.gwt.GwtSuperDev) {
	args "-style", "PRETTY", "-strict"
	//, "-logLevel", "ALL"
	jvmArgs "-Dgwt.watchFileChanges=false"
}
```

**Comment by michael-newsrx** [comment]
> To disable it add the system property `-Dgwt.watchFileChanges=false' to SDM command line.

The SDM compile times a) have improved dramatically, b) seem pretty consistent, c) no "hangs" or "long compile delays" so far.

```bash
10.606s total -- Compile completed (first compile)
5.449s total -- Compile completed
3.445s total -- Compile completed
3.249s total -- Compile completed
3.404s total -- Compile completed
3.262s total -- Compile completed
4.828s total -- Compile completed
3.261s total -- Compile completed
3.100s total -- Compile completed
2.741s total -- Compile completed
3.481s total -- Compile completed
```

**Comment by jnehlmeier** [comment]
@michael-newsrx Are you on Mac OS? I have disabled it long ago on Mac OS since the implementation of the FileWatcher API in JDK wasn't great on Mac. With SSDs a full directory scan doesn't hurt that much anyway.

**Comment by realityforge** [comment]
@niloc132 You are right. I will try and get back to have a look in the near future. Unfortunately stuck keycloak upgrade hell in the day job so it may be a while ;)

**Comment by realityforge** [comment]
Ok - had a few minutes to spin up after work. So it seems that the bug is entirely within the poller. It seems that the locks are not acquired in a stable order and thus deadlocks happen. Dang. 

```
"Thread-12" #30 daemon prio=5 os_prio=31 tid=0x00007fcd7b48f000 nid=0x12803 waiting for monitor entry [0x000070000ed65000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.cancel(PollingWatchService.java:306)
	- waiting to lock <0x0000000742465bf8> (a java.util.HashMap)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.poll(PollingWatchService.java:329)
	- locked <0x0000000742465f90> (a sun.nio.fs.PollingWatchService$PollingWatchKey)
	at sun.nio.fs.PollingWatchService$PollingWatchKey$1.run(PollingWatchService.java:288)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
"Thread-6" #24 prio=5 os_prio=31 tid=0x00007fcd7b92c000 nid=0xd607 waiting for monitor entry [0x000070000e753000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.nio.fs.PollingWatchService$PollingWatchKey.disable(PollingWatchService.java:297)
	- waiting to lock <0x0000000742465f90> (a sun.nio.fs.PollingWatchService$PollingWatchKey)
	at sun.nio.fs.PollingWatchService.implClose(PollingWatchService.java:183)
	- locked <0x0000000742465bf8> (a java.util.HashMap)
	at sun.nio.fs.AbstractWatchService.close(AbstractWatchService.java:153)
	- locked <0x0000000742465be8> (a java.lang.Object)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.stopWatchService(ResourceAccumulator.java:107)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.maybeInitializeWatchService(ResourceAccumulator.java:96)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.fullRefresh(ResourceAccumulator.java:89)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.refresh(ResourceAccumulator.java:123)
	at com.google.gwt.dev.resource.impl.ResourceAccumulator.refreshResources(ResourceAccumulator.java:67)
	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager.refreshResources(ResourceAccumulatorManager.java:128)
	- locked <0x0000000742189328> (a java.lang.Class for com.google.gwt.dev.resource.impl.ResourceAccumulatorManager)
	at com.google.gwt.dev.resource.impl.ResourceAccumulatorManager$1.run(ResourceAccumulatorManager.java:91)
```
