### ISSUE TITLE
Using "Integer::parseInt" inside map function breaks line

### ISSUE THREAD

**Issue by TJBrunson** [gwtproject/gwt#9715]
**GWT version:2.9.0** 
**Chrome (with version):87.0.4280.88** 
**Operating System: Mac OS 10.15.7 (19H15)** 

---

##### Description
Uncaught 
znc_g$ {stackTrace_1_g$: null, writetableStackTrace_1_g$: true, backingJsObject_1_g$: Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: For input string: "undefine…, cause_1_g$: Q3e_g$, detailMessage_0_g$: "Exception caught: For input string: "undefined"", …}
backingJsObject_1_g$: Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: For input string: "undefined" at znc_g$.OD_g$ [as createError_0_g$] (Browser-0.js:10174:10) at znc_g$.YD_g$ [as initializeBackingError_0_g$] (Browser-0.js:10229:43) at znc_g$.ID_g$ (Browser-0.js:10090:8) at znc_g$.mE_g$ (Browser-0.js:10328:9) at znc_g$.uE_g$ (Browser-0.js:10375:9) at znc_g$.snc_g$ (Browser-0.js:26091:9) at new znc_g$ (Browser-0.js:26155:10) at eHj_g$.gmc_g$ [as castFireEventFromSource_0_g$] (Browser-0.js:25614:20) at eHj_g$.nnc_g$ [as fireEventFromSource_1_g$] (Browser-0.js:26068:8) at eHj_g$.gHj_g$ [as fireEventFromSource_1_g$] (Browser-0.js:172190:40) at iNj_g$.lNj_g$ [as flagItems_0_g$] (Browser-0.js:174640:26) at lKn_g$.mKn_g$ [as flag_19_g$] (Browser-0.js:266279:23) at FKn_g$.TKn_g$ [as updateView_3_g$] (Browser-0.js:266498:22) at qLn_g$.tLn_g$ [as onObjectLoaded_0_g$] (Browser-0.js:266658:25) at FXn_g$.sAm_g$ [as lambda$0_107_g$] (Browser-0.js:238607:18) at GSn_g$.HSn_g$ [as execute_2_g$] (Browser-0.js:268884:25) at wO_g$ (Browser-0.js:12459:27) at aO_g$ (Browser-0.js:12181:9) at RN_g$.XN_g$ [as flushPostEventPumpCommands_0_g$] (Browser-0.js:12273:5) at nO_g$.oO_g$ [as execute_3_g$] (Browser-0.js:12412:22) at UN_g$ (Browser-0.js:12149:19) at DM_g$ (Browser-0.js:11835:28) at GM_g$ (Browser-0.js:11905:14) at Browser-0.js:11871:14 at callback_0_g$ (Browser-0.js:12200:38)
cause_1_g$: Q3e_g$ {stackTrace_1_g$: null, writetableStackTrace_1_g$: true, backingJsObject_1_g$: Error: java.lang.NumberFormatException: For input string: "undefined" at Q3e_g$.OD_g$ [as creat…, detailMessage_0_g$: "For input string: "undefined"", $H: 7379}
causes_1_g$: Zyf_g$ {map_5_g$: Qyf_g$}
detailMessage_0_g$: "Exception caught: For input string: "undefined""
stackTrace_1_g$: null
writetableStackTrace_1_g$: true
__proto__: Object

##### Steps to reproduce
I wanted to combine steps to split a string on "," map each part of that array to an int, and then collect it as a list. So here is the exact line I wrote.

List<Integer> dataDescKeys = Arrays.stream(numString.split(",")).map(Integer::parseInt).collect(Collectors.toList());

##### Known workarounds
I transformed the line to this and it compiled and ran perfectly:

List<Integer> dataDescKeys = Arrays.stream(numString.split(",")).map(num -> Integer.parseInt(num)).collect(Collectors.toList());

**Comment by zbynek** [comment]
I just tried this and couldn't reproduce it. Can you maybe try to place the call directly to your `onModuleLoad` method and see if you can reproduce it there? Also is this reproducible in SuperDevMode or just compiled?

**Comment by TJBrunson** [comment]
this happened in SuperDevMode, but I noticed the project where this happened was on GWT version 2.8.2, not 2.9.0, like I thought. So this may have been potentially fixed.
