### ISSUE TITLE
Only in PROD mode, only in Chrome: (TypeError) : ((intermediate value)(intermediate value) , b).sp is not a function

### ISSUE THREAD

**Issue by NorbertSandor** [gwtproject/gwt#9737]
**GWT version:** 2.9.0
**Browser (with version):** Chrome 93.0.4577.82 (64 bits)
**Operating System:** Windows 7 / 10

---

##### Description
We get the following error: `(TypeError) : ((intermediate value)(intermediate value) , b).sp is not a function`

It appears only in Chrome, Firefox 88.0b2 (64 bits) works correctly.
And only in production compilation mode, development mode works correctly.

Do you have any suggestions how can I track the root of the problem?
The project is a very complex private project, I cannot share it (and otherwise it would be too large as a sample project).
Thanks.

**Comment by niloc132** [comment]
I'm afraid we will need more details about what is happening here, what sort of code `b` and `sp` might have been, so as to understand what might have caused this.

One possible explanation might be that your gwt-unitCache is stale and that this is a lambda or method reference - we have seen bugs like this before, and deleting that cache can fix it (usually just doing a clean build is enough, but it might depend on how you are building, if your IDE or build tool happens to store that cache somewhere that doesnt get cleaned correctly). Building on a completely different machine or fresh checkout would also help remove this possibility. 

Another avenue to helping explore and understand this could be building with `-style PRETTY` or `DETAILED` so that the variables are readable and we can see what sort of code they used to be, and you could perhaps give us sanitized snippets.

**Comment by NorbertSandor** [comment]
Thanks, I will try it with PRETTY, I hope the issue is reproducible with this setting.
(It's sure that the issue is not because of a stale cache because we clean the whole project before production builds.)

**Comment by NorbertSandor** [comment]
I could not reproduce with PRETTY setting. The strange thing is: the error is gone even with OBF setting.
As I know nothing happened that would influence the related part of the application, so I have absolutely no idea what solved it.
Anyway, thanks for your help, I hope the issue will never pop up again :)

**Comment by niloc132** [comment]
Thanks for checking back, and glad you got it resolved.

**Comment by NorbertSandor** [comment]
We've just run into a very similar issue: `(TypeError) : ((intermediate value)(intermediate value) , b).Ap is not a function`
It occurs only in Chrome 95.0.4638.69, Firefox 88.0b2 works as expected.
:(

I will try to make my browsers upgraded to the latest versions (I cannot do it on my own because I have no privileges on the corporate machine :\ ).

**Comment by NorbertSandor** [comment]
> One possible explanation might be that your gwt-unitCache is stale and that this is a lambda or method reference - we have seen bugs like this before

Yes, I have a "feeling" that this issue is related to method references.
The issue comes and goes, it is not always reproducible.
But it always occurs where method references are used.

Today I run into another similar problem with method references:

```
Caused by: java.lang.RuntimeException: Cannot set property: object=EntityId[id=0], value=77436698, setter=EntityIdPeer$1methodref$setId$Type@9b1
    at Unknown.vb_g$(Throwable.java:76)
    at Unknown.cc_g$(Exception.java:33)
    at Unknown.kc_g$(RuntimeException.java:33)
    at Unknown.q4c_g$(DefaultPropertyAccessor.java:31)
    at Unknown.UUmb_g$(EntityIdCloner.java:33)
    at Unknown.VUmb_g$(EntityIdCloner.java:31)
    at Unknown.L3c_g$(CloningContextImpl.java:133)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError) : cNh_g$(...).setId_1_g$ is not a function
```

In this case a utility 'cloner' function (generated by a GWT generator) tries to set a property by calling `java.util.function.BiConsumer#accept` on the method reference of `EntityId::setId`.
It worked perfectly until recently but now it started to fail.

> usually just doing a clean build is enough

In the case above cleaning the SDM cache solved the problem.
But the same error happens sometimes in production builds as well :|

**Comment by niloc132** [comment]
Method references and "cleaning sdm cache" both strongly point to #9670 - I encourage you to take a closer look at your CI process and where it happens to be putting its gwt-unitCache, or completely disable that feature in your CI builds. From time to time I take a look at this - I think I have a hunch now where the bug is, but haven't yet been able to prove it.

Pass the system property `gwt.persistentunitcache`=`false` to your gwt compiler process (likely as a jvm arg, `-Dgwt.persistentunitcache=false`) to disable it outright, or set the path to somewhere you explicitly clean and control with `gwt.persistentunitcachedir`. See `com.googlegwt.dev.javac.UnitCacheSingleton` for these system property names and how they are used.

**Comment by NorbertSandor** [comment]
> completely disable that feature in your CI builds
Thanks for the tip, I will.

Should I use the same configuration option in SuperDev mode to prevent similar errors?

**Comment by niloc132** [comment]
That's really up to you - just cleaning the cache should be enough to make it go away when it does happen, and presumably cleaning the cache is easier locally than on your CI box.
