### ISSUE TITLE
GWT-DEV (JDK 1.8 IBM): ClassNotFoundException: com.google.gwt.dev.jjs.ast.JPrimitiveType

### ISSUE THREAD

**Issue by insidex** [gwtproject/gwt#9789]
**GWT version:** 2.10.0
**Browser (with version):** Any
**Operating System:** Windows
**JDK version:** openjdk version 1.8.0_352 (or smth close)

---

##### Description

Compilation of GWT module is failed when running under the specific JDK.

##### Steps to reproduce

1.  Install following JDK 1.8 (latest at the moment):

openjdk version "1.8.0_352"
IBM Semeru Runtime Open Edition (build 1.8.0_352-b08)
Eclipse OpenJ9 VM (build openj9-0.35.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20221101_526 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - b213334935 based on jdk8u352-b08)

2. Create any simple GWT module (client/server RPC) and try to compile it.

3. Check the GWT compiler stack trace:

 [22/12/16 19:19:21.825 MSK] main     Server        I org.eclipse.jetty.server.Server doStart Started @85714ms
Dev Mode initialized. Startup URL:
http://127.0.0.1:8888/accounting.jsp
GET /recompile/accounting
   Job com.de.accounting.AccountingDev_1_0
      starting job: com.de.accounting.AccountingDev_1_0
      Compiling module com.de.accounting.AccountingDev
         Ignored 8 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
         [ERROR] Unexpected internal compiler error
java.lang.RuntimeException: Unexpected error deserializing AST for 'java.lang.Throwable'
	at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:373)
	at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1022)
	at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483)
	at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528)
	at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440)
	at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033)
	at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483)
	at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528)
	at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440)
	at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033)
	at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483)
	at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528)
	at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440)
	at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033)
	at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483)
	at com.google.gwt.dev.jjs.impl.UnifyAst.findType(UnifyAst.java:1466)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.synthesizeEntryMethodHolderInit(JavaToJavaScriptCompiler.java:1347)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1402)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:243)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
	at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:826)
Caused by: java.lang.ClassNotFoundException: com.google.gwt.dev.jjs.ast.JPrimitiveType
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:411)
	at java.io.ClassByNameCache$FutureValue.get(ClassByNameCache.java:189)
	at java.io.ClassByNameCache.get(ClassByNameCache.java:160)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:877)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2108)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1972)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2306)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2558)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2480)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2333)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:586)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:496)
	at java.util.ArrayList.readObject(ArrayList.java:799)
	at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2447)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2333)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:586)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:496)
	at com.google.gwt.dev.jjs.ast.JDeclaredType.readMembers(JDeclaredType.java:550)
	at com.google.gwt.dev.jjs.ast.JProgram.deserializeTypes(JProgram.java:237)
	at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:369)
	... 36 more
      [ERROR] Compiler returned false
      [WARN] recompile failed
      [WARN] continuing to serve previous version

##### Known workarounds

Disable caching for java.io.ObjectInputStream by running GWT compiler with "-Dcom.ibm.enableClassCaching=false"

**Comment by insidex** [comment]
any updates ?

**Comment by niloc132** [comment]
If this is specific to the IBM jdk 1.8, and has an easy-to-use workaround, this might not be fixed - that JDK is relatively uncommon, and 1.8 is not likely to be supported by GWT for too much longer (1.8 will prevent us from using any newer JDT or Jetty, for example), so this might not get a lot of attention without more detail. 

The fact that the property is com.ibm specific makes me suspect that this optimization just doesn't work with something about how gwt's classloaders are working? Probably worth a closer look, but you might need someone with working knowledge of the ibm jdk, or someone with time to learn.

**Comment by baldimir** [comment]
We are experiencing the same problem on IBM Semeru Runtime Open Edition 11.0.18.0 (build 11.0.18+10).

**Comment by niloc132** [comment]
@baldimir barring someone with time/interest to dig in to this, and given that we have a pretty simple workaround, I'm not aware of any efforts underway to fix this. Can you confirm that the workaround is sufficient for your use case?

**Comment by baldimir** [comment]
Yes, the workaround is enough. Thanks.

**Comment by previl13** [comment]
> **GWT version:** 2.10.0 **Browser (with version):** Any **Operating System:** Windows **JDK version:** openjdk version 1.8.0_352 (or smth close)
> 
> ##### Description
> Compilation of GWT module is failed when running under the specific JDK.
> 
> ##### Steps to reproduce
> 1. Install following JDK 1.8 (latest at the moment):
> 
> openjdk version "1.8.0_352" IBM Semeru Runtime Open Edition (build 1.8.0_352-b08) Eclipse OpenJ9 VM (build openj9-0.35.0, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20221101_526 (JIT enabled, AOT enabled) OpenJ9 - e04a7f6c1 OMR - 85a21674f JCL - b213334935 based on jdk8u352-b08)
> 
> 2. Create any simple GWT module (client/server RPC) and try to compile it.
> 3. Check the GWT compiler stack trace:
> 
> [22/12/16 19:19:21.825 MSK] main Server I org.eclipse.jetty.server.Server doStart Started @85714ms Dev Mode initialized. Startup URL: http://127.0.0.1:8888/accounting.jsp GET /recompile/accounting Job com.de.accounting.AccountingDev_1_0 starting job: com.de.accounting.AccountingDev_1_0 Compiling module com.de.accounting.AccountingDev Ignored 8 units with compilation errors in first pass. Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors. [ERROR] Unexpected internal compiler error java.lang.RuntimeException: Unexpected error deserializing AST for 'java.lang.Throwable' at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:373) at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1022) at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483) at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528) at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440) at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033) at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483) at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528) at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440) at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033) at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483) at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1528) at com.google.gwt.dev.jjs.impl.UnifyAst.resolveType(UnifyAst.java:1440) at com.google.gwt.dev.jjs.impl.UnifyAst.assimilateSourceUnit(UnifyAst.java:1033) at com.google.gwt.dev.jjs.impl.UnifyAst.internalFindType(UnifyAst.java:1483) at com.google.gwt.dev.jjs.impl.UnifyAst.findType(UnifyAst.java:1466) at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.synthesizeEntryMethodHolderInit(JavaToJavaScriptCompiler.java:1347) at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1402) at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222) at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140) at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255) at com.google.gwt.dev.Precompile.precompile(Precompile.java:243) at com.google.gwt.dev.Precompile.precompile(Precompile.java:190) at com.google.gwt.dev.Precompile.precompile(Precompile.java:131) at com.google.gwt.dev.Compiler.compile(Compiler.java:192) at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362) at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175) at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134) at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135) at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113) at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37) at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:826) Caused by: java.lang.ClassNotFoundException: com.google.gwt.dev.jjs.ast.JPrimitiveType at java.lang.Class.forNameImpl(Native Method) at java.lang.Class.forName(Class.java:411) at java.io.ClassByNameCache$FutureValue.get(ClassByNameCache.java:189) at java.io.ClassByNameCache.get(ClassByNameCache.java:160) at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:877) at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2108) at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1972) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2306) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789) at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2558) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2480) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2333) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:586) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:496) at java.util.ArrayList.readObject(ArrayList.java:799) at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184) at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2447) at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2333) at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1789) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:586) at java.io.ObjectInputStream.readObject(ObjectInputStream.java:496) at com.google.gwt.dev.jjs.ast.JDeclaredType.readMembers(JDeclaredType.java:550) at com.google.gwt.dev.jjs.ast.JProgram.deserializeTypes(JProgram.java:237) at com.google.gwt.dev.javac.CompilationUnit.getTypes(CompilationUnit.java:369) ... 36 more [ERROR] Compiler returned false [WARN] recompile failed [WARN] continuing to serve previous version
> 
> ##### Known workarounds
> Disable caching for java.io.ObjectInputStream by running GWT compiler with "-Dcom.ibm.enableClassCaching=false"
> 
> ##### Links to further discussions

We are using IBM JDK 1.8.0_352 and GWT 2.10.0, Initially we were having build issues with the above stack trace, after applying the above workaround build was successful but started seeing MID errors in runtime.

Could you please suggest if anything needs to be done to resolve this issue.

**Comment by jnehlmeier** [comment]
Given the above output and a quick check it seems that Eclipse OpenJ9 VM has this issue from time to time.

See 
https://github.com/eclipse-openj9/openj9/issues/8454
https://github.com/eclipse-openj9/openj9/issues/9912

There is also a comment with some fixes for various JDK versions: https://github.com/eclipse-openj9/openj9/issues/8454#issuecomment-580825276

But given that there is still an open issue for JDK 11 it could very well be that it is not fully fixed for JDK 8 as well.

So I think it is out of scope for GWT to invest time in this and fix it somehow. Either use the workaround above, try using a newer Eclipse OpenJ9 VM or create a reproduction project and file an issue in their repository so they can further fix OpenJ9 VM.

**Comment by niloc132** [comment]
> but started seeing MID errors in runtime.

Can you give more detail about what this means? The runtime of the compiler, as above, or server-side code after startup, or client-side code in the browser? If it isnt an error when compiling, it is likely unrelated.

I don't think we're necessarily opposed to trying to help from GWT, but if it is a bug in OpenJ9 it is likely hard for us to do much to fix it on our end. 

From the second issue linked by Jens, the JPrimitiveType class is somewhat interesting in terms of serialization as it has a readResolve() method which basically makes JPrimitiveType behave like an enum - deserialized instances are replaced with a specific single instance for each supported java primitive type. I don't see anything else interesting about this type or its supertypes in terms of serialization though.

**Comment by LukeSavefrogs** [comment]
Had this problem on a Jenkins build for a Vaadin 8 project. Making that specific build use an OpenJDK 1.8 java build instead of IBM Semeru 1.8 fixed the problem for us

**Comment by zbynek** [comment]
Java 8 is not supported since https://github.com/gwtproject/gwt/pull/9899

**Comment by tbroyer** [comment]
This is only about build time though right? GWT is still built with `--release 8`.

**Comment by niloc132** [comment]
GWT is built with `--release 8`, but recent GWT releases use a version of JDT that require Java 11+. Building Java 8 bytecode only makes it possible (as far as we know, with limited testing) to use the server jars in a Java 8 runtime, any other usage (dev mode, testing, compiling a project, etc) require Java 11+.

The workaround above is the correct answer, until the IBM JDK fixes their bug, and not something we're actively looking at.

**Comment by tbroyer** [comment]
Yeah, definitely not challenging the decision to close 👍, only the reason that was advanced for it (the specific PR)
