### ISSUE TITLE
Serialization fails with Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible.

### ISSUE THREAD

**Issue by mike-targetr** [gwtproject/gwt#9793]
Throwables and exceptions can no longer be serialized and returned to the browser using servlet containers running on newer JVMs.

gwt-2.10.0
Java 17
All browsers, all operating systems

---

##### Description

Throwables and sub classes cause the following exception when being serialized by GWT in Java 17.

`java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @1e44b638
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeClass(ServerSerializationStreamWriter.java:781)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeImpl(ServerSerializationStreamWriter.java:826)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeClass(ServerSerializationStreamWriter.java:799)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeImpl(ServerSerializationStreamWriter.java:826)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeClass(ServerSerializationStreamWriter.java:799)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeImpl(ServerSerializationStreamWriter.java:826)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:698)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:167)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:606)
	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:644)
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:419)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)`

##### Steps to reproduce

Trigger an exception from any RemoteService method.

e.g.

`public List<User> loadUsers(ViewState state) throws PermissionException;`

If the permission exception is thrown, the above error occurs.

##### Known workarounds

Start Java with the following command line argument:

--add-opens=java.base/java.lang=ALL-UNNAMED

**Comment by niloc132** [comment]
For GWT-RPC to work, it needs to be able to read and write relevant fields. The `detailMessage` field is non-final, but it has no setter or any other way to assign it after the Throwable constructor has completed. It can, however, be read through the `Throwable.getMessage()` method, but we still need some way to write it to deserialize the whole object.

The other option is constructor deserialization, where instead of GWT-RPC always requiring a no-arg constructor that it can call, offer a a method that reliably can take a message parameter, and assume that it will be passed up to Throwable. This doesn't really work out very nicely in practice - there are plenty of cases of exception constructors that call super(...) with some constant strings concatenated with constructor arguments. We would need to require that all serializable Throwables always have a constructor that only takes a String, and always calls super(message) with it, and this would have to be true for every intermediate superclass. A very quick survey of java.* and com.google.gwt.* classes shows these cases that would break this (whether or not you would intend to serialize these is besides the point, _someone_ might):

* `com.google.gwt.http.client.RequestTimeoutException`
* `com.google.gwt.http.client.RequestPermissionException` - particularly irritating, since it takes a string arg, but adds other strings to it
* `java.util.EmptyStackException`
* `java.text.ParseException`

Without an accessor to write that, either extending GWT-RPC to support setting fields via the constructor (not a small task), the only other option besides reflection is omitting the field, which makes throwables a whole lot less useful to serialize at all. They end up only transporting their own declared members (like other serializable types) - and for https://github.com/Vertispan/gwt-rpc this is the route I took, suggesting that some kind of "either" type is preferable to actually throwing exceptions. Rather than `AsyncCallback<T>`, that project encourages `Callback<T, F>` to support failure messages that might not even be exceptions. It does cause more irritations on the server though, since you can't just throw arbitrary exceptions any more and plan on the rpc system sending them in some way to the other side.

... I guess one more option would be to lobby for Java to add a `Throwable.setMessage(String)` method? That seems like a long shot ;).

**Comment by jnehlmeier** [comment]
What about not caring about the stack trace? Instead of sending the exception we could only send the message (`getMessage()`) + type from server to client internally. Then we use JS to reconstruct the exception on the client without the server stack trace but with the correct message.

At least in apps I have written I have usually removed the stack trace from the exception anyways since I don't think it is relevant on the client and leaks server information.

**Comment by Onyx-Scott** [comment]
Since exceptions are only thrown by the server and delivered to the client, couldn't you just read the getMessage() to populate the javascript equivalent of the detailed message?
