### ISSUE TITLE
GWT compatibility issue with jetty version 9.4.9

### ISSUE THREAD

**Issue by RaviGupta8080** [gwtproject/gwt#9842]
Upgraded jetty version from 9.2.14.v20151106 to 9.4.9.v20180320 and GWT is not working 

GWT version : 2.8.1
CROME
MAC

---

I started getting this error , when i have upgraded my jetty , it is causing error with GWT 

error is : 

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
Running CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.8, -bindAddress, 127.0.0.1, -launcherDir, /Users/vishal.gupta/Library/Caches/JetBrains/IntelliJIdea2022.3/gwt/pacman.5d2bcea7/webui-smartgwt.d2604de1/run/www, -logLevel, INFO, -style, OBFUSCATED, com.bazaarvoice.pacman.webui.PacmanWebAppHosted]
Super Dev Mode starting up
   workDir: /var/folders/8t/xqs98hy5369c10jnt80ygzs40000gr/T/gwt-codeserver-6450024326853743083.tmp
   Loading Java files in com.bazaarvoice.pacman.webui.PacmanWebAppHosted.
   Module setup completed in 36953 ms
java.lang.NoClassDefFoundError: org/eclipse/jetty/http/pathmap/PathSpec
	at org.eclipse.jetty.servlet.ServletContextHandler.newServletHandler(ServletContextHandler.java:341)
	at org.eclipse.jetty.servlet.ServletContextHandler.getServletHandler(ServletContextHandler.java:405)
	at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:269)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:176)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:132)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:120)
	at com.google.gwt.dev.codeserver.WebServer.start(WebServer.java:129)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:162)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.http.pathmap.PathSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 22 more

My pom file configration is this:

```
<properties>
        <java.minimum.version>1.8</java.minimum.version>
        <gwt.version>2.8.1</gwt.version>
        <smartgwt.version>12.1-p20200521</smartgwt.version>
        <spring.version>4.3.1.RELEASE</spring.version>
        <spring.security.version>4.1.2.RELEASE</spring.security.version>
        <letterpress.version>1.48</letterpress.version>
        <yammer.metrics.version>2.2.0</yammer.metrics.version>
        <ostrich.version>1.9.3</ostrich.version>
        <jackson.version>2.10.5</jackson.version>
        <jetty.version>9.4.9.v20180320</jetty.version>
        <commons.dao>4.4</commons.dao>
        <dependency-check.skip>false</dependency-check.skip>
   </properties>

<!-- GWT -->
            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt-user</artifactId>
                <version>${gwt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt-servlet</artifactId>
                <version>${gwt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.jsinterop</groupId>
                <artifactId>jsinterop-annotations</artifactId>
                <version>1.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.google.gwt</groupId>
                <artifactId>gwt-dev</artifactId>
                <version>${gwt.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- SmartGWT -->
            <dependency>
                <groupId>com.isomorphic.smartgwt.lgpl</groupId>
                <artifactId>smartgwt-lgpl</artifactId>
                <version>${smartgwt.version}</version>
            </dependency>
            <dependency>
                <groupId>com.isomorphic.smartgwt.lgpl</groupId>
                <artifactId>smartgwt-skins</artifactId>
                <version>${smartgwt.version}</version>
            </dependency>
```
            
            
            
            
           Please help me out , how should i resolve this issue.

**Comment by bpetridean** [comment]
You're using a pretty old version 2.8.1 (3 new releases since then), thus why not update to gwt 2.10.0?
Jetty was upgraded to version 9.4.44 in [gwt-2.10.0](https://www.gwtproject.org/release-notes.html#Release_Notes_2_10_0)

**Comment by tbroyer** [comment]
You can't just update Jetty and expect it works: Jetty regularly introduces breaking changes in minor or even bugfix releases.

Secondly, you should separate the classpath used by GWT for the client-side code from the classpath of your server-side code; to do this with Maven, you have to split your code into separate Maven modules: one for the client code, another for the server code (and possibly a third for the code shared between them). That way, you can use whichever version of Jetty you want as your server, without forcing GWT to use that version.
