### ISSUE TITLE
GWT snapshot builds cannot be used in Java 8

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9850]
As reported by @tbroyer at https://matrix.to/#/!AvXTCxQwVkniJBaCEi:gitter.im/$yYZu3vwk0KH6y3GXggOAxwmvmrYhdhKRkiGktQt6cxw

> Fwiw, the GWT snapshots now being built with JDK 17 and without using --release means that they're not compatible with earlier JDKs due to a binary incompatibility: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer; was apparently added in JDK 13; previously ByteBuffer inherited the flip()Ljava/nio/Buffer; from java.nio.Buffer, causing a NoSuchMethoderror in JDK 8 or JDK 11.
> 
> See https://github.com/tbroyer/gwt-maven-plugin/actions/runs/6136747840

Stack trace:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at com.google.gwt.dev.util.Util.computeStrongName(Util.java:121)
        at com.google.gwt.dev.util.Util.computeStrongName(Util.java:94)
        at com.google.gwt.dev.javac.CompilationUnitBuilder$ResourceCompilationUnitBuilder.doGetSource(CompilationUnitBuilder.java:153)
        at com.google.gwt.dev.javac.CompilationUnitBuilder.getSource(CompilationUnitBuilder.java:285)
        at com.google.gwt.dev.javac.JdtCompiler$Adapter.getContents(JdtCompiler.java:148)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11943)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:11915)
        at com.google.gwt.dev.javac.JdtCompiler$ParserImpl.parse(JdtCompiler.java:204)
        at org.eclipse.jdt.internal.compiler.parser.Parser.dietParse(Parser.java:10325)
        at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:840)
        at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:394)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:444)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
        at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1020)
        at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:322)
        at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
        at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
        at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:210)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
        at com.google.gwt.junit.JUnitShell.compileForWebMode(JUnitShell.java:1093)
```
This results from running on Java8 8 with bytecode compiled for Java 8 on a newer Java, using only `-source 8` and `-target 8` instead of `--release 8` - the signature of ByteBuffer.flip() has changed, and old source-compatible bytecode is no longer binary compatible.

The fix is to pass the `--release` flag to javac when using Java 9+, while still temporarily using the `-source`/`-target` flags while we still support building on Java. My current thinking is to keep building on Java 8 as long as we intend to support running on Java 8, as the easiest way to support running tests.

**Comment by tbroyer** [comment]
Fyi, I re-ran the gwt-maven-plugin job using the snapshots, and it passed :tada: 
https://github.com/tbroyer/gwt-maven-plugin/actions/runs/6145001205/job/16782835427
