### ISSUE TITLE
Error on compile Java 8 - GWT 2.11

### ISSUE THREAD

**Issue by RemiFermentin** [gwtproject/gwt#9927]
Hello, I have a weird error in 2.11 (works fine in 2.10 & 2.10.1). On my gradle task to compile in java 8 I have this error. I never had this before and I don't know from where I should start.  (FYI: GwT is downloaded from MavenCentral ). 

Task :sciforma-webapp:compileGwt
Using gwt_max_memory=4096M
Using gwt_local_workers=2
Compiling module com.sciforma.gwt.Main
[ERROR] Unexpected internal compiler error
java.lang.IllegalArgumentException: Unsupported api 589824
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
        at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57)
        at com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor.<init>(BytecodeSignatureMaker.java:59)
        at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:227)
        at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
        at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
        at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:41)
        at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:36)
        at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:100)
        at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:349)
        at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:532)
        at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:464)
        at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:210)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:190)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:131)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:192)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
        at com.google.gwt.dev.Compiler.compile(Compiler.java:132)
        at com.google.gwt.dev.Compiler$1.run(Compiler.java:110)
        at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
        at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
        at com.google.gwt.dev.Compiler.main(Compiler.java:113)

**Comment by jnehlmeier** [comment]
GWT 2.11 has updated its ASM dependency to version 9.2. Check if your application has an older ASM on class path.

**Comment by RemiFermentin** [comment]
Thanks for your fast response,
I'll check tomorrow the details of my dependencies, it could be as I see asm 7.1 in my dependencies (a bit surprise though). (even in 2.10.1 where we should have 9.2 from maven).  I'll get the issue resolved if I figure out the issue tomorrow.

**Comment by RemiFermentin** [comment]
It is working after moving asm to 9.6 . Thanks a lot
